import { mkdtemp, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, join } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import { JobStore, RESULT_CHUNK_BYTES } from '../src/job-store.ts';
import { runWorker } from '../src/worker.ts';
import type { JsonRequest, JsonTransport } from '../src/transport.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
async function fixture() { const root = await mkdtemp(join(tmpdir(), 'nb-search-artifact-')); roots.push(root); const env = { NB_SEARCH_EXA_API_KEY: 'key' }; const transport: JsonTransport = { async send<T>(request: JsonRequest) { const query = String((request.body as Record<string, unknown>)['query']); return { status: 200, headers: {}, body: { results: [{ title: query, url: `https://x/${query}`, highlights: [query] }] } as T }; } }; const app = createRuntimeComposition(env, { cwd: root, homeDirectory: root, transport, launcher: { async launch() {} }, config: { home: root, jobs_root: join(root, 'jobs'), defaults: { search_lane: 'exa.search' }, execution: { retry_count: 0 } } }); const started = await app.runtime.search({ action: 'run', query: 'q', execution: 'async', idempotency_key: 'job' }); if (started.action !== 'run' || started.execution !== 'async' || started.job === undefined) throw new Error(); return { root, env, transport, app, jobId: started.job.job_id }; }
describe('immutable artifact store', () => {
  it('retries transient Windows result-directory rename failures', async () => { const f = await fixture(); const attempts: number[] = []; const renamePath: typeof rename = async (from, to) => { if (basename(String(to)) === 'result' && attempts.length < 2) { attempts.push(attempts.length); const error = new Error('busy') as NodeJS.ErrnoException; error.code = 'EPERM'; throw error; } return await rename(from, to); }; const store = new JobStore(f.app.store.root, () => new Date(), { rename_path: renamePath, sleep: async () => {} }); const artifact = await store.writeResult(f.jobId, { text: 'ok' }, 3600); expect(artifact.sha256).toHaveLength(64); expect(attempts).toHaveLength(2); await expect(store.writeResult(f.jobId, { text: 'second' }, 3600)).rejects.toBeTruthy(); });
  it('keeps the public ref minimal and applies page size to byte-offset chunk cursors', async () => { const f = await fixture(); const artifact = await f.app.store.writeResult(f.jobId, { text: '内容🙂'.repeat(RESULT_CHUNK_BYTES) }, 3600); expect(Object.keys(artifact).sort()).toEqual(['byte_length', 'expires_at', 'media_type', 'sha256']); expect(Object.keys((await f.app.store.read(f.jobId)).artifact!).sort()).toEqual(['byte_length', 'expires_at', 'media_type', 'sha256']); const first = await f.app.store.readResult(f.jobId, 0, 2); expect(first.chunks).toHaveLength(2); expect(first.chunks.map((chunk) => chunk.offset)).toEqual([0, RESULT_CHUNK_BYTES]); expect(first.next_offset).toBe(2 * RESULT_CHUNK_BYTES); const second = await f.app.store.readResult(f.jobId, first.next_offset!, 2); expect(second.chunks).toHaveLength(2); expect(second.chunks[0]?.offset).toBe(2 * RESULT_CHUNK_BYTES); await expect(f.app.store.readResult(f.jobId, 1, 1)).rejects.toMatchObject({ code: 'INVALID_INPUT' }); });
  it.each(['hash', 'chunk-length', 'manifest-length'] as const)('rejects %s corruption before returning artifact chunks', async (mode) => { const f = await fixture(); await f.app.store.writeResult(f.jobId, { text: 'x'.repeat(RESULT_CHUNK_BYTES * 2) }, 3600); const resultDir = join(f.app.store.root, f.jobId, 'result'); const chunkPath = join(resultDir, '000000.bin'); const manifestPath = join(resultDir, 'manifest.json'); if (mode === 'hash') { const bytes = await readFile(chunkPath); bytes[0] = bytes[0]! ^ 1; await writeFile(chunkPath, bytes); } else if (mode === 'chunk-length') { const bytes = await readFile(chunkPath); await writeFile(chunkPath, bytes.subarray(0, bytes.length - 1)); } else { const manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as { artifact: { byte_length: number } }; manifest.artifact.byte_length += 1; await writeFile(manifestPath, JSON.stringify(manifest)); } await expect(f.app.store.readResult(f.jobId, 0, 1)).rejects.toMatchObject({ code: 'JOB_STORE_ERROR' }); });
  it('runs prune on query start and worker entry paths without an environment TTL override', async () => { const f = await fixture(); const prune = vi.spyOn(f.app.store, 'prune'); await f.app.runtime.search({ action: 'run', query: 'second', execution: 'async', idempotency_key: 'second' }); expect(prune).toHaveBeenCalledWith(); await expect(runWorker('00000000-0000-4000-8000-000000000001', { NB_SEARCH_RETENTION_HOURS: '0' }, f.app.store.root)).rejects.toMatchObject({ code: 'JOB_NOT_FOUND' }); expect((await f.app.store.read(f.jobId)).request.result_ttl_seconds).toBe(72 * 3600); });
});
