import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import type { JsonTransport } from '../src/transport.ts';
import { mockConfig, mockRegistration } from './helpers.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
describe('minimal static capabilities', () => {
  it('returns only the model-facing catalog and limits', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-capabilities-')); roots.push(root); let network = 0; const transport: JsonTransport = { async send<T>() { network += 1; throw new Error() as never; } }; const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, transport, config: mockConfig(root), provider_registrations: [mockRegistration()] }); const value = await app.runtime.capabilities(); expect(Object.keys(value).sort()).toEqual(['fetch', 'jobs', 'revision', 'schema_version', 'search']); expect(value.search.default_lane).toBe('mock.results'); expect(value.fetch.chain).toEqual(['mock.fetch']); expect(value.fetch.limits.quality).toEqual({ min_content_chars: 0, blocked_markers: 0 }); expect(value.search.presets).toEqual([{ name: 'cross', lanes: ['mock.results'], execution_modes: ['sync'], availability: 'ready', issues: [] }]); expect(value.jobs).toEqual({ result_ttl_seconds: 259200, cancel_supported: true }); for (const lane of value.search.lanes) expect(Object.keys(lane.output).sort()).toEqual(['channel', 'schema_id']); const text = JSON.stringify(value); expect(text).not.toMatch(/"answer"|"deep"|"healthy"|provider_instance|registered|configured|selectable|heartbeat|retry|persistence|canonical_path|provenance/); expect(network).toBe(0); });
  it('reports built-in async from operation descriptors and custom operations as sync-only', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-cap-modes-')); roots.push(root); const app = createRuntimeComposition({ NB_SEARCH_EXA_API_KEY: 'key' }, { cwd: root, homeDirectory: root, config: { home: root, jobs_root: join(root, 'jobs'), provider_instances: { 'mock.default': { provider_id: 'mock', enabled: true, options: {} } }, lanes: { 'mock.results': { provider_instance_id: 'mock.default', operation_id: 'results', latency: 'fast', cost: 'free' } } }, provider_registrations: [mockRegistration()] }); const value = await app.runtime.capabilities(); expect(value.search.lanes.find((lane) => lane.id === 'exa.search')?.execution_modes).toEqual(['sync', 'async']); expect(value.search.lanes.find((lane) => lane.id === 'mock.results')?.execution_modes).toEqual(['sync']); });
});
