import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import type { ProviderRegistration } from '../src/provider-registry.ts';
import type { JsonTransport } from '../src/transport.ts';
import { mockConfig, mockRegistration } from './helpers.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
describe('minimal static capabilities', () => {
  it('returns the provider, lane, pipeline, default, and limit catalog without runtime secrets', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-capabilities-')); roots.push(root); let network = 0; const transport: JsonTransport = { async send<T>() { network += 1; throw new Error() as never; } }; const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, transport, config: mockConfig(root), provider_registrations: [mockRegistration()] }); const value = await app.runtime.capabilities(); expect(Object.keys(value).sort()).toEqual(['fetch', 'jobs', 'providers', 'revision', 'schema_version', 'search']); expect(value.providers.descriptors.find((provider) => provider.provider_id === 'mock')).toMatchObject({ activation: { credential: 'none', endpoint: 'none' }, option_keys: [] }); expect(value.providers.instances.find((provider) => provider.id === 'mock.default')).toEqual({ id: 'mock.default', provider_id: 'mock', enabled: true, availability: 'ready', issues: [], credential: { requirement: 'none', configured: false }, endpoint: { requirement: 'none', configured: false } }); expect(value.search.default_lane).toBe('mock.results'); expect(value.fetch.default_representation).toBe('markdown'); expect(value.fetch.chains).toContainEqual({ input_kind: 'url', representation: 'markdown', pipelines: ['mock.fetch'] }); expect(value.fetch.pipelines.find((pipeline) => pipeline.id === 'mock.fetch')).toMatchObject({ representations: ['markdown', 'text'], egress: 'url' }); expect(value.search.presets).toEqual([{ name: 'cross', lanes: ['mock.results'], execution_modes: ['sync'], availability: 'ready', issues: [] }]); expect(value.jobs).toEqual({ result_ttl_seconds: 259200, cancel_supported: true }); for (const lane of value.search.lanes) expect(Object.keys(lane.output).sort()).toEqual(['channel', 'schema_id']); const text = JSON.stringify(value); expect(text).not.toMatch(/"answer"|"deep"|"healthy"|heartbeat|retry|persistence|canonical_path|provenance/); expect(network).toBe(0); });
  it('does not project a mismatched secret binding as configured', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-cap-credential-')); roots.push(root); const secret = 'capability-secret'; const app = createRuntimeComposition({ NB_SEARCH_EXA_API_KEY: secret }, { cwd: root, homeDirectory: root, config: { home: root, jobs_root: join(root, 'jobs') } }); const bindings = app.config.resolved.secret_bindings as Map<string, { credential_slot_id: string; provider_id: string; value: string; worker_grant: { kind: 'environment'; name: string } }>; bindings.set('exa.default', { credential_slot_id: 'exa.default', provider_id: 'tavily', value: secret, worker_grant: { kind: 'environment', name: 'NB_SEARCH_EXA_API_KEY' } }); const value = await app.runtime.capabilities(); expect(value.providers.instances.find((provider) => provider.id === 'exa.default')).toMatchObject({ availability: 'unavailable', credential: { requirement: 'required', configured: false }, issues: expect.arrayContaining([{ code: 'CREDENTIAL_NOT_CONFIGURED' }]) }); expect(JSON.stringify(value)).not.toContain(secret); });
  it('reports built-in async from operation descriptors and custom operations as sync-only', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-cap-modes-')); roots.push(root); const app = createRuntimeComposition({ NB_SEARCH_EXA_API_KEY: 'key' }, { cwd: root, homeDirectory: root, config: { home: root, jobs_root: join(root, 'jobs'), provider_instances: { 'mock.default': { provider_id: 'mock', enabled: true, options: {} } }, lanes: { 'mock.results': { provider_instance_id: 'mock.default', operation_id: 'results', latency: 'fast', cost: 'free' } } }, provider_registrations: [mockRegistration()] }); const value = await app.runtime.capabilities(); expect(value.search.lanes.find((lane) => lane.id === 'exa.search')?.execution_modes).toEqual(['sync', 'async']); expect(value.search.lanes.find((lane) => lane.id === 'mock.results')?.execution_modes).toEqual(['sync']); });
  it('marks an empty realized provider unavailable and a partially realized provider ready with issues', async () => { for (const mode of ['empty', 'partial'] as const) { const root = await mkdtemp(join(tmpdir(), `nb-search-cap-${mode}-`)); roots.push(root); const base = mockRegistration({}, mode); const registration: ProviderRegistration = { ...base, create(context: Parameters<typeof base.create>[0]) { const ports = base.create(context); return mode === 'empty' ? { query: {} as Record<string, never>, fetch: {} } : { query: { results: ports.query['results']! }, fetch: {} }; } }; const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, config: mockConfig(root, { provider_instances: { 'mock.default': { provider_id: mode, enabled: true, options: {} } } }), provider_registrations: [registration] }); const value = await app.runtime.capabilities(); const instance = value.providers.instances.find((provider) => provider.id === 'mock.default'); const issueCodes = instance?.issues.map((issue) => issue.code); if (mode === 'empty') { expect(instance?.availability).toBe('unavailable'); expect(issueCodes).toEqual(expect.arrayContaining(['PROVIDER_PORTS_UNAVAILABLE', 'LANE_NOT_CONFIGURED'])); expect(value.search.lanes.find((lane) => lane.id === 'mock.results')?.availability).toBe('unavailable'); } else { expect(instance?.availability).toBe('ready'); expect(issueCodes).toEqual(expect.arrayContaining(['PROVIDER_PORTS_PARTIAL', 'LANE_NOT_CONFIGURED'])); expect(value.search.lanes.find((lane) => lane.id === 'mock.results')?.availability).toBe('ready'); expect(value.search.lanes.find((lane) => lane.id === 'mock.typed')?.availability).toBe('unavailable'); } } });
  it('propagates browser optional-dependency readiness to the provider instance', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-cap-browser-')); roots.push(root); const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, test_only_browser_render_io: { available: false, async resolve() { return []; }, async render() { throw new Error('must not render'); } }, config: { home: root, jobs_root: join(root, 'jobs') } }); const value = await app.runtime.capabilities(); const instance = value.providers.instances.find((provider) => provider.id === 'browser-render.default'); expect(instance?.availability).toBe('unavailable'); expect(instance?.issues.map((issue) => issue.code)).toEqual(expect.arrayContaining(['PROVIDER_PORTS_UNAVAILABLE', 'BROWSER_NOT_INSTALLED'])); expect(value.fetch.pipelines.find((pipeline) => pipeline.id === 'browser.render')).toMatchObject({ availability: 'unavailable', issues: [{ code: 'BROWSER_NOT_INSTALLED' }] }); });
});
