import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { describe, expect, it, vi } from 'vitest';
import { runCli } from '../src/cli.ts';
import { createNbSearchMcpServer } from '../src/mcp-server.ts';
import type { NbSearchRuntime } from '../src/runtime.ts';
import type { CapabilityEnvelope, FetchEnvelope, SearchEnvelope } from '../src/types.ts';
const jobId = '00000000-0000-4000-8000-000000000000';
describe('three-capability CLI', () => {
  it('routes fetch run/get/read/cancel and URL convenience', async () => { const runtime = fakeRuntime(); for (const argv of [['fetch', 'https://example.com', '--pipeline', 'direct.fetch'], ['fetch', 'run', 'https://example.com', '--representation', 'text'], ['fetch', 'get', jobId], ['fetch', 'read', jobId, '--page-size', '2'], ['fetch', 'cancel', jobId]] as const) expect(await runCli(argv, captureIo(), () => runtime)).toBe(0); expect(runtime.fetch).toHaveBeenNthCalledWith(1, { action: 'run', source: { kind: 'url', url: 'https://example.com' }, pipeline: 'direct.fetch' }); expect(runtime.fetch).toHaveBeenNthCalledWith(2, { action: 'run', source: { kind: 'url', url: 'https://example.com' }, representation: 'text' }); expect(runtime.fetch).toHaveBeenNthCalledWith(3, { action: 'get', job_id: jobId }); expect(runtime.fetch).toHaveBeenNthCalledWith(4, { action: 'read', job_id: jobId, page_size: 2 }); expect(runtime.fetch).toHaveBeenNthCalledWith(5, { action: 'cancel', job_id: jobId }); });
  it('keeps exactly three top-level commands', async () => { const runtime = fakeRuntime(); for (const command of ['document', 'extract', 'convert', 'list']) expect(await runCli([command], captureIo(), () => runtime)).toBe(2); const io = captureIo(); await runCli(['--help'], io, () => runtime); expect(io.stdout.value).toContain('nb-search fetch get'); expect(io.stdout.value).not.toMatch(/nb-search (document|extract|convert)\b/); });
});
describe('three-tool MCP server', () => {
  it('publishes fetch action/source unions and dispatches normalized input', async () => { const runtime = fakeRuntime(); const server = createNbSearchMcpServer(runtime); const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair(); const client = new Client({ name: 'test', version: '1.0.0' }); await server.connect(serverTransport); await client.connect(clientTransport); try { const listed = await client.listTools(); expect(listed.tools.map((tool) => tool.name)).toEqual(['search', 'fetch', 'capabilities']); const fetchTool = listed.tools.find((tool) => tool.name === 'fetch')!; expect(JSON.stringify(fetchTool.inputSchema)).toContain('inline_bytes'); expect(JSON.stringify(fetchTool.inputSchema)).toContain('cancel'); const result = await client.callTool({ name: 'fetch', arguments: { action: 'run', source: { kind: 'inline_text', content: 'hello', media_type: 'text/plain' } } }); expect(result.isError).not.toBe(true); expect(runtime.fetch).toHaveBeenCalledWith({ action: 'run', source: { kind: 'inline_text', content: 'hello', media_type: 'text/plain' } }, { signal: expect.any(AbortSignal) }); } finally { await client.close(); await server.close(); } });
});
function fakeRuntime(): NbSearchRuntime & { search: ReturnType<typeof vi.fn>; fetch: ReturnType<typeof vi.fn>; capabilities: ReturnType<typeof vi.fn> } { const search = vi.fn(async (): Promise<SearchEnvelope> => ({ schema_version: '3.0', action: 'run', execution: 'sync', status: 'empty', hints: [] })); const fetch = vi.fn(async (input): Promise<FetchEnvelope> => input.action === 'get' ? { schema_version: '3.0', mode: 'fetch', action: 'get', job_id: input.job_id, state: 'queued', cancel_requested: false, created_at: '2026-01-01T00:00:00.000Z', updated_at: '2026-01-01T00:00:00.000Z' } : input.action === 'read' ? { schema_version: '3.0', mode: 'fetch', action: 'read', job_id: input.job_id, state: 'queued', chunks: [] } : input.action === 'cancel' ? { schema_version: '3.0', mode: 'fetch', action: 'cancel', job_id: input.job_id, state: 'cancelled', cancel_requested: true } : { schema_version: '3.0', mode: 'fetch', action: 'run', execution: 'sync', selection: { source: 'default' }, status: 'succeeded', lane_outcomes: [], documents: [], hints: [] }); const capabilities = vi.fn(async (): Promise<CapabilityEnvelope> => ({ schema_version: '3.0', revision: 'r', search: { lanes: [], presets: [], limits: { max_queries: 64, max_results: 100, max_timeout_ms: 3_600_000, max_inline_bytes: 1024 } }, fetch: { default_representation: 'markdown', inputs: [], chains: [], pipelines: [], limits: { max_source_bytes: 1024, max_response_bytes: 1024, max_content_chars: 256, max_redirects: 5, max_timeout_ms: 120_000, max_inline_bytes: 1024 } }, jobs: { result_ttl_seconds: 3600, cancel_supported: true } })); return { search, fetch, capabilities }; }
function captureIo() { const stdout = { value: '', write(value: string) { this.value += value; } }; const stderr = { value: '', write(value: string) { this.value += value; } }; return { stdout, stderr }; }
