import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { loadConfiguration } from '../src/config.ts';
import { defaultConfiguration, resolveConfiguration } from '../src/config-sources.ts';
import { mockConfig, mockRegistration } from './helpers.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
async function root() { const value = await mkdtemp(join(tmpdir(), 'nb-search-config-v4-')); roots.push(value); return value; }
describe('schema v4 configuration', () => {
  it('uses operation bindings and input-specific fetch chains', () => { const config = defaultConfiguration('C:/tmp/nb-search'); expect(config.schema_version).toBe('4'); expect(Object.keys(config.lanes).sort()).toEqual(['brave.search', 'browser.render', 'context7.docs', 'direct.fetch', 'direct.local', 'exa.contents', 'exa.search', 'exa.synthesis', 'firecrawl.scrape', 'firecrawl.search', 'github.repositories', 'gma.research', 'grok.synthesis', 'grok.x-synthesis', 'jina.reader', 'oac.fetch', 'oac.synthesis', 'parallel.search', 'searxng.search', 'tavily.extract', 'tavily.search', 'tavily.synthesis', 'wayback.fetch', 'zhipu.search']); expect(config.defaults.fetch_chain).toContainEqual({ input_kind: 'url', pipelines: ['direct.fetch', 'jina.reader'] }); expect(config.defaults.fetch_chain).toContainEqual({ input_kind: 'file', pipelines: ['direct.local'] }); expect(config.fetch.file_scopes).toEqual([]); expect(config.execution.fetch).toMatchObject({ max_source_bytes: 2 * 1024 * 1024, quality: { min_content_chars: 500 } }); expect(config.lanes['exa.search']).toEqual({ provider_instance_id: 'exa.default', operation_id: 'search', latency: 'fast', cost: 'cheap', evidence_groups: ['exa'] }); });
  it('rejects the removed fetch_lane field', async () => { const home = await root(); expect(() => resolveConfiguration({ env: { NB_SEARCH_HOME: home }, cwd: home, homeDirectory: home, config: { defaults: { fetch_lane: 'direct.fetch' } } as never })).toThrow(/fetch_lane/); });
  it('ignores every legacy credential and routing environment alias', async () => { const home = await root(); const baseline = resolveConfiguration({ env: { NB_SEARCH_HOME: home }, cwd: home, homeDirectory: home }); const injected = resolveConfiguration({ env: { NB_SEARCH_HOME: home, SEARCH_LAYER_CREDENTIALS: 'x', EXA_API_KEY: 'legacy', TAVILY_API_KEY: 'legacy', GROK_API_KEY: 'legacy', GROK_MODEL: 'legacy', SEARCH_LAYER_REQUEST_TIMEOUT_SECONDS: '1' }, cwd: home, homeDirectory: home }); expect(injected.config_fingerprint).toBe(baseline.config_fingerprint); expect(injected.secret_bindings.size).toBe(0); expect(JSON.stringify(injected)).not.toMatch(/legacy_path|LEGACY_NOT_FOUND|LEGACY_INVALID|legacy-json/); });
  it('uses canonical provider environment names only', async () => { const home = await root(); const resolved = resolveConfiguration({ env: { NB_SEARCH_HOME: home, NB_SEARCH_EXA_API_KEY: 'canonical', NB_SEARCH_EXA_BASE_URL: 'https://exa.example' }, cwd: home, homeDirectory: home }); expect(resolved.secret_bindings.get('exa.default')?.value).toBe('canonical'); expect(resolved.config.provider_instances['exa.default']?.base_url).toBe('https://exa.example'); });
  it('uses provider-scoped Grok credential slots backed by the same environment grant', async () => { const home = await root(); const app = loadConfiguration({ NB_SEARCH_HOME: home, NB_SEARCH_GROK_API_KEY: 'shared', NB_SEARCH_GROK_BASE_URL: 'https://api.x.ai/v1', NB_SEARCH_GROK_MULTI_AGENT_BASE_URL: 'https://api.x.ai/v1' }, undefined, { cwd: home, homeDirectory: home }); expect(app.resolved.config.provider_instances['grok.default']?.credential_slot_id).toBe('grok.default'); expect(app.resolved.config.provider_instances['grok-multi-agent.default']?.credential_slot_id).toBe('grok-multi-agent.default'); expect(app.resolved.secret_bindings.get('grok.default')).toMatchObject({ provider_id: 'grok', value: 'shared' }); expect(app.resolved.secret_bindings.get('grok-multi-agent.default')).toMatchObject({ provider_id: 'grok-multi-agent', value: 'shared' }); expect(app.resolved.secret_bindings.size).toBe(2); expect(app.lanes['grok.synthesis']?.availability).toBe('ready'); expect(app.lanes['grok.x-synthesis']?.availability).toBe('ready'); expect(app.lanes['gma.research']?.availability).toBe('ready'); });
  it('rejects a credential slot declared for a different provider', async () => { const home = await root(); expect(() => resolveConfiguration({ env: { HOST_SECRET: 'must-not-escape' }, cwd: home, homeDirectory: home, config: { credential_slots: { 'wrong.slot': { provider_id: 'tavily', env: 'HOST_SECRET' } }, provider_instances: { 'exa.default': { credential_slot_id: 'wrong.slot' } } } })).toThrow(/credential slot provider does not match/); });
  it('rejects a typed lane inside a preset during configuration loading', async () => { const home = await root(); const base = mockConfig(home); expect(() => loadConfiguration({}, undefined, { cwd: home, homeDirectory: home, provider_registrations: [mockRegistration()], config: { ...base, presets: { bad: { lanes: ['mock.results', 'mock.typed'] } } } })).toThrow(/results lanes only/); });
});
