import { mkdtemp, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import type { CanonicalConfigPatch } from '../src/config-schema.ts';
import { fetchInputSchema } from '../src/contracts.ts';
import type { ProviderRegistration } from '../src/provider-registry.ts';
import { document } from './helpers.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
describe('rich fetch semantics', () => {
  it('accepts all source variants and rejects invalid inline MIME', () => { for (const source of [{ kind: 'url', url: 'https://example.com' }, { kind: 'inline_text', content: 'x', media_type: 'text/plain' }, { kind: 'inline_bytes', content_base64: 'eA==', media_type: 'text/plain' }, { kind: 'file', path: 'a.txt', scope: 'docs' }]) expect(fetchInputSchema.safeParse({ action: 'run', source }).success).toBe(true); expect(fetchInputSchema.safeParse({ action: 'run', source: { kind: 'inline_text', content: 'x', media_type: 'application/json' } }).success).toBe(false); });
  it('reads inline and scoped files, blocks escapes, and keeps roots private', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-rich-files-')); roots.push(root); const scope = join(root, 'scope'); const outside = join(root, 'outside.txt'); const { mkdir } = await import('node:fs/promises'); await mkdir(scope); await writeFile(join(scope, 'inside.md'), '# Hello'); await writeFile(outside, 'outside'); const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, config: { home: root, jobs_root: join(root, 'jobs'), fetch: { file_scopes: [{ id: 'docs', root: scope, media_types: ['text/markdown'] }] }, execution: { fetch: { quality: { min_content_chars: 0, blocked_markers: [] } } } } }); const inline = await app.runtime.fetch({ action: 'run', source: { kind: 'inline_text', content: '<p>Hello <a href="guide">Docs</a></p><script>bad()</script>', media_type: 'text/html', base_url: 'https://example.com/base/' } }); expect(inline).toMatchObject({ status: 'succeeded', documents: [{ content: 'Hello [Docs](https://example.com/base/guide)', representation: 'markdown', media_type: 'text/html' }] }); expect(await app.runtime.fetch({ action: 'run', source: { kind: 'file', path: 'inside.md', scope: 'docs' } })).toMatchObject({ status: 'succeeded', documents: [{ content: '# Hello', media_type: 'text/markdown' }] }); expect(JSON.stringify(await app.runtime.capabilities())).not.toContain(scope); expect(await app.runtime.fetch({ action: 'run', source: { kind: 'file', path: '../outside.txt', scope: 'docs' } })).toMatchObject({ status: 'failed', error: { code: 'FETCH_FILE_BLOCKED' } }); expect(await app.runtime.fetch({ action: 'run', source: { kind: 'file', path: 'inside.md', scope: 'missing' } })).toMatchObject({ status: 'failed', error: { code: 'FETCH_SCOPE_NOT_FOUND' } }); });
  it('rejects symlink escape and oversized inline bytes', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-rich-link-')); roots.push(root); const scope = join(root, 'scope'); const outside = join(root, 'outside.txt'); const { mkdir } = await import('node:fs/promises'); await mkdir(scope); await writeFile(outside, 'outside'); try { await symlink(outside, join(scope, 'link.txt')); } catch { return; } const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, config: { home: root, jobs_root: join(root, 'jobs'), fetch: { file_scopes: [{ id: 'docs', root: scope }] }, execution: { fetch: { max_source_bytes: 2, quality: { min_content_chars: 0, blocked_markers: [] } } } } }); expect(await app.runtime.fetch({ action: 'run', source: { kind: 'file', path: 'link.txt', scope: 'docs' } })).toMatchObject({ status: 'failed', error: { code: 'FETCH_FILE_BLOCKED' } }); expect(await app.runtime.fetch({ action: 'run', source: { kind: 'inline_bytes', content_base64: Buffer.from('large').toString('base64'), media_type: 'text/plain' } })).toMatchObject({ status: 'failed', error: { code: 'FETCH_BYTES_LIMIT' } }); });
  it('falls back by representation and fails explicit unsupported selection', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-rich-representation-')); roots.push(root); const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, config: config(root), provider_registrations: [registration('text-only', ['text']), registration('markdown-only', ['markdown'])] }); const value = await app.runtime.fetch({ action: 'run', source: { kind: 'url', url: 'https://example.com' }, representation: 'markdown' }); expect(value.documents[0]?.source_lane).toBe('markdown.fetch'); expect(await app.runtime.fetch({ action: 'run', source: { kind: 'url', url: 'https://example.com' }, pipeline: 'text.fetch', representation: 'markdown' })).toMatchObject({ status: 'failed', error: { code: 'FETCH_PIPELINE_UNSUPPORTED' } }); });
  it('returns FETCH_CHAIN_UNAVAILABLE without provider calls when no chain matches', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-rich-chain-')); roots.push(root); let calls = 0; const provider = registration('text-only', ['text'], () => { calls += 1; }); const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, config: { ...config(root), defaults: { fetch_chain: [{ input_kind: 'inline_text', pipelines: ['text.fetch'] }] } }, provider_registrations: [provider, registration('markdown-only', ['markdown'])] }); expect(await app.runtime.fetch({ url: 'https://example.com' })).toMatchObject({ status: 'failed', error: { code: 'FETCH_CHAIN_UNAVAILABLE' } }); expect(calls).toBe(0); });
});
function config(root: string): CanonicalConfigPatch { return { home: root, jobs_root: join(root, 'jobs'), provider_instances: { 'text.default': { provider_id: 'text-only', enabled: true, options: {} }, 'markdown.default': { provider_id: 'markdown-only', enabled: true, options: {} } }, lanes: { 'text.fetch': { provider_instance_id: 'text.default', operation_id: 'fetch', latency: 'fast', cost: 'free' }, 'markdown.fetch': { provider_instance_id: 'markdown.default', operation_id: 'fetch', latency: 'fast', cost: 'free' } }, defaults: { fetch_chain: [{ input_kind: 'url', pipelines: ['text.fetch', 'markdown.fetch'] }] }, execution: { retry_count: 0, fetch: { quality: { min_content_chars: 0, blocked_markers: [] } } } }; }
function registration(id: string, representations: Array<'markdown' | 'text'>, called: () => void = () => {}): ProviderRegistration { return { descriptor: { provider_id: id, adapter_version: '1', query_operations: [], fetch_operations: [{ operation_id: 'fetch', schema_id: 'nb-search.fetch@1', input_kinds: ['url'], media_types: ['text/plain'], representations, execution_modes: ['sync'], egress: 'url', stages: [{ id: `${id}.fetch`, role: 'reader' }] }], activation: { credential: 'none', endpoint: 'none' }, option_keys: [] }, create: () => ({ query: {}, fetch: { fetch: { name: id, async fetch(request) { called(); if (request.source.kind !== 'url') throw new Error(); return document(request.source.url, id, request.representation); } } } }) }; }
