import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import type { ProviderRegistration } from '../src/provider-registry.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
describe('fetch egress boundary', () => {
  it('skips egressing chain pipelines and rejects explicit selection without calls', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-egress-')); roots.push(root); let calls = 0; const registration: ProviderRegistration = { descriptor: { provider_id: 'egress-test', adapter_version: '1', query_operations: [], fetch_operations: [{ operation_id: 'send', schema_id: 'nb-search.fetch@1', input_kinds: ['inline_text'], media_types: ['text/plain'], representations: ['markdown'], execution_modes: ['sync'], egress: 'content', stages: [{ id: 'send', role: 'reader' }] }], activation: { credential: 'none', endpoint: 'none' }, option_keys: [] }, create: () => ({ query: {}, fetch: { send: { name: 'egress-test', async fetch() { calls += 1; throw new Error(); } } } }) }; const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, provider_registrations: [registration], config: { home: root, jobs_root: join(root, 'jobs'), provider_instances: { 'egress.default': { provider_id: 'egress-test', enabled: true, options: {} } }, lanes: { 'egress.send': { provider_instance_id: 'egress.default', operation_id: 'send', latency: 'fast', cost: 'free' } }, defaults: { fetch_chain: [{ input_kind: 'inline_text', representation: 'markdown', pipelines: ['egress.send', 'direct.local'] }] }, execution: { fetch: { quality: { min_content_chars: 0, blocked_markers: [] } } } } }); const source = { kind: 'inline_text' as const, content: 'safe', media_type: 'text/plain' as const }; const chained = await app.runtime.fetch({ action: 'run', source }); expect(chained).toMatchObject({ status: 'succeeded', lane_outcomes: [{ lane: 'egress.send', state: 'skipped', error: { code: 'FETCH_EGRESS_DENIED' } }, { lane: 'direct.local', state: 'succeeded' }] }); const explicit = await app.runtime.fetch({ action: 'run', source, pipeline: 'egress.send' }); expect(explicit).toMatchObject({ status: 'failed', error: { code: 'FETCH_EGRESS_DENIED' } }); expect(calls).toBe(0); });
});
