import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createFetchJobRunnerFromSnapshot, createRuntimeComposition } from '../src/app.ts';
import { mockConfig, mockRegistration } from './helpers.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
async function fixture() { const root = await mkdtemp(join(tmpdir(), 'nb-search-fetch-jobs-')); roots.push(root); const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, launcher: { async launch() {} }, config: { home: root, jobs_root: join(root, 'jobs'), execution: { fetch: { quality: { min_content_chars: 0, blocked_markers: [] } } } } }); return app; }
async function readAll(app: Awaited<ReturnType<typeof fixture>>, jobId: string): Promise<unknown> { const chunks: Buffer[] = []; let cursor: string | undefined; do { const page = await app.runtime.fetch({ action: 'read', job_id: jobId, ...(cursor === undefined ? {} : { cursor }), page_size: 1 }); if (page.action !== 'read') throw new Error(); chunks.push(...page.chunks.map((chunk) => Buffer.from(chunk.data_base64, 'base64'))); cursor = page.next_cursor; } while (cursor !== undefined); return JSON.parse(Buffer.concat(chunks).toString('utf8')) as unknown; }
describe('fetch jobs on the unified substrate', () => {
  it('reuses idempotent async fetches and publishes pageable artifacts', async () => { const app = await fixture(); const input = { action: 'run' as const, source: { kind: 'inline_text' as const, content: '# Hello', media_type: 'text/markdown' as const }, execution: 'async' as const, idempotency_key: 'same' }; const first = await app.runtime.fetch(input); const second = await app.runtime.fetch(input); expect(first).toMatchObject({ mode: 'fetch', action: 'run', execution: 'async', status: 'queued', reused: false }); expect(second).toMatchObject({ reused: true }); if (first.action !== 'run' || first.execution !== 'async' || first.job === undefined) throw new Error(); const snapshot = await app.store.readExecutionSnapshot(first.job.job_id); expect(snapshot.kind).toBe('fetch'); await createFetchJobRunnerFromSnapshot(snapshot, app.store).run(first.job.job_id); expect(await app.runtime.fetch({ action: 'get', job_id: first.job.job_id })).toMatchObject({ mode: 'fetch', state: 'succeeded', artifact: { media_type: 'application/json' } }); expect(await readAll(app, first.job.job_id)).toMatchObject({ mode: 'fetch', action: 'run', execution: 'sync', status: 'succeeded', documents: [{ content: '# Hello', representation: 'markdown' }] }); });
  it('supports cancellation and keeps search/fetch job namespaces distinct', async () => { const app = await fixture(); const started = await app.runtime.fetch({ action: 'run', source: { kind: 'inline_text', content: 'cancel', media_type: 'text/plain' }, execution: 'async', idempotency_key: 'cancel' }); if (started.action !== 'run' || started.execution !== 'async' || started.job === undefined) throw new Error(); expect(await app.runtime.fetch({ action: 'cancel', job_id: started.job.job_id })).toMatchObject({ mode: 'fetch', state: 'cancelled', cancel_requested: true }); await expect(app.runtime.search({ action: 'get', job_id: started.job.job_id })).rejects.toMatchObject({ code: 'JOB_NOT_FOUND' }); });
  it('rejects sync idempotency and async URL pipelines before creating jobs', async () => { const app = await fixture(); await expect(app.runtime.fetch({ action: 'run', source: { kind: 'inline_text', content: 'x', media_type: 'text/plain' }, idempotency_key: 'bad' } as never)).rejects.toBeTruthy(); const result = await app.runtime.fetch({ action: 'run', source: { kind: 'url', url: 'https://example.com' }, execution: 'async', idempotency_key: 'url' }); expect(result).toMatchObject({ status: 'failed', error: { code: 'FETCH_CHAIN_UNAVAILABLE' } }); expect(await app.store.listRecords()).toHaveLength(0); });
  it('keeps custom fetch pipelines sync-only even when their descriptor advertises async', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-custom-fetch-job-')); roots.push(root); const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, launcher: { async launch() { throw new Error(); } }, config: mockConfig(root), provider_registrations: [mockRegistration()] }); const result = await app.runtime.fetch({ action: 'run', source: { kind: 'url', url: 'https://example.com' }, pipeline: 'mock.fetch', execution: 'async', idempotency_key: 'custom' }); expect(result).toMatchObject({ status: 'failed', error: { code: 'LANE_EXECUTION_UNSUPPORTED' } }); expect(await app.store.listRecords()).toHaveLength(0); });
});
