import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import { ExaContentsFetchProvider, FirecrawlScrapeFetchProvider, JinaReaderFetchProvider, TavilyExtractFetchProvider } from '../src/fetch-providers.ts';
import type { JsonRequest, JsonResponse, JsonTransport } from '../src/transport.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
const signal = new AbortController().signal;
const request = () => ({ source: { kind: 'url' as const, url: 'https://example.com/page' }, representation: 'markdown' as const, signal, max_source_bytes: 4096, max_response_bytes: 4096, max_content_chars: 1000, max_redirects: 5, file_scopes: [] });
describe('fetch provider adapters', () => {
  it('preserves Jina request shape and normalizes representation metadata', async () => { const transport = new CaptureTransport({ status: 200, body: 'reader content', headers: { 'content-type': 'text/plain; charset=utf-8' } }); const value = await new JinaReaderFetchProvider({ apiKey: 'jina-secret', transport }).fetch(request()); expect(transport.requests[0]).toMatchObject({ url: 'https://r.jina.ai/https://example.com/page', method: 'GET', headers: { Authorization: 'Bearer jina-secret' }, response_type: 'text' }); expect(value).toMatchObject({ content: 'reader content', representation: 'markdown', media_type: 'text/plain' }); });
  it('preserves Tavily Extract request shape', async () => { const transport = new CaptureTransport({ status: 200, body: { results: [{ url: 'https://final.test', raw_content: 'tavily content', title: 'T' }] } }); const value = await new TavilyExtractFetchProvider({ apiKey: 'secret', transport }).fetch(request()); expect(transport.requests[0]).toMatchObject({ url: 'https://api.tavily.com/extract', body: { urls: ['https://example.com/page'], format: 'text' } }); expect(value).toMatchObject({ final_url: 'https://final.test', content: 'tavily content' }); });
  it('preserves Exa Contents request shape', async () => { const transport = new CaptureTransport({ status: 200, body: { results: [{ url: 'https://final.test', text: 'exa content', title: 'E' }] } }); const value = await new ExaContentsFetchProvider({ apiKey: 'secret', transport }).fetch(request()); expect(transport.requests[0]).toMatchObject({ url: 'https://api.exa.ai/contents', body: { urls: ['https://example.com/page'], text: { maxCharacters: 1000 } } }); expect(value.content).toBe('exa content'); });
  it('preserves Firecrawl Scrape request shape', async () => { const transport = new CaptureTransport({ status: 200, body: { success: true, data: { markdown: '# Firecrawl', metadata: { sourceURL: 'https://final.test' } } } }); const value = await new FirecrawlScrapeFetchProvider({ apiKey: 'secret', transport }).fetch(request()); expect(transport.requests[0]).toMatchObject({ url: 'https://api.firecrawl.dev/v2/scrape', body: { url: 'https://example.com/page', formats: ['markdown'] } }); expect(value).toMatchObject({ content: '# Firecrawl', media_type: 'text/markdown' }); });
  it.each([['jina', (transport: JsonTransport) => new JinaReaderFetchProvider({ transport })], ['tavily', (transport: JsonTransport) => new TavilyExtractFetchProvider({ apiKey: 'secret', transport })], ['exa', (transport: JsonTransport) => new ExaContentsFetchProvider({ apiKey: 'secret', transport })], ['firecrawl', (transport: JsonTransport) => new FirecrawlScrapeFetchProvider({ apiKey: 'secret', transport })]] as const)('maps %s upstream errors to FETCH_HTTP_ERROR', async (_name, create) => { for (const status of [404, 429, 500]) await expect(create(new CaptureTransport({ status, body: {} })).fetch(request())).rejects.toMatchObject({ code: 'FETCH_HTTP_ERROR', retryable: status >= 500, data: { status } }); });
  it('reports static availability without network probes', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-fetch-availability-')); roots.push(root); let network = 0; const transport: JsonTransport = { async send<T>() { network += 1; throw new Error() as never; } }; const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, transport }); const capabilities = await app.runtime.capabilities(); expect(Object.fromEntries(capabilities.fetch.pipelines.map((pipeline) => [pipeline.id, pipeline.availability]))).toMatchObject({ 'direct.fetch': 'ready', 'direct.local': 'ready', 'jina.reader': 'ready', 'exa.contents': 'unavailable' }); expect(network).toBe(0); });
});
class CaptureTransport implements JsonTransport { readonly requests: JsonRequest[] = []; constructor(private readonly response: JsonResponse) {} async send<T>(value: JsonRequest): Promise<JsonResponse<T>> { this.requests.push(value); return this.response as JsonResponse<T>; } }
