import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import type { CanonicalConfigPatch } from '../src/config-schema.ts';
import { NbSearchError } from '../src/errors.ts';
import type { ProviderRegistration } from '../src/provider-registry.ts';
import type { FetchProviderResult } from '../src/types.ts';
import { document } from './helpers.ts';

const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
describe('fetch serial pipeline chain', () => {
  it('runs pipelines in order and preserves fallback classification', async () => { const calls = { a: 0, b: 0 }; const app = await runtime(['a.fetch', 'b.fetch'], { a: async () => { calls.a += 1; throw new NbSearchError('FETCH_HTTP_ERROR', '403', false, 'a', { data: { status: 403 } }); }, b: async (url, _signal, representation) => { calls.b += 1; return document(url, 'b'.repeat(600), representation); } }); const value = await app.runtime.fetch({ url: 'https://example.com' }); expect(value).toMatchObject({ action: 'run', execution: 'sync', status: 'succeeded', documents: [{ source_lane: 'b.fetch', representation: 'markdown' }], lane_outcomes: [{ lane: 'a.fetch', state: 'failed' }, { lane: 'b.fetch', state: 'succeeded' }] }); expect(calls).toEqual({ a: 1, b: 1 }); });
  it.each([404, 410])('terminates after HTTP %s', async (status) => { let second = 0; const app = await runtime(['a.fetch', 'b.fetch'], { a: async () => { throw new NbSearchError('FETCH_HTTP_ERROR', 'terminal', false, 'a', { data: { status } }); }, b: async (url, _signal, representation) => { second += 1; return document(url, 'b', representation); } }); expect((await app.runtime.fetch({ url: 'https://example.com' })).status).toBe('failed'); expect(second).toBe(0); });
  it('applies quality gates and shares the provider-call budget', async () => { let calls = 0; const app = await runtime(['a.fetch', 'b.fetch'], { a: async (url, _signal, representation) => document(url, 'short', representation), b: async (url, _signal, representation) => { calls += 1; return document(url, 'qualified content', representation); } }, { quality: { min_content_chars: 10, blocked_markers: [] }, max_provider_calls: 2 }); const value = await app.runtime.fetch({ url: 'https://example.com' }); expect(value.documents[0]?.source_lane).toBe('b.fetch'); expect(value.lane_outcomes[0]?.error?.code).toBe('QUALITY_GATE_FAILED'); expect(calls).toBe(1); });
  it('uses an explicit pipeline without touching the configured chain', async () => { const calls = { a: 0, c: 0 }; const app = await runtime(['a.fetch'], { a: async (url, _signal, representation) => { calls.a += 1; return document(url, 'a', representation); }, c: async (url, _signal, representation) => { calls.c += 1; return document(url, 'c', representation); } }, { quality: { min_content_chars: 0, blocked_markers: [] } }); const value = await app.runtime.fetch({ action: 'run', source: { kind: 'url', url: 'https://example.com' }, pipeline: 'c.fetch' }); expect(value).toMatchObject({ selection: { source: 'pipeline', pipeline: 'c.fetch' }, documents: [{ source_lane: 'c.fetch' }] }); expect(calls).toEqual({ a: 0, c: 1 }); });
  it('returns FETCH_CHAIN_UNAVAILABLE with zero calls when no chain matches', async () => { let calls = 0; const app = await runtime(['a.fetch'], { a: async (url, _signal, representation) => { calls += 1; return document(url, 'a', representation); } }, { chainKind: 'inline_text' }); const value = await app.runtime.fetch({ url: 'https://example.com' }); expect(value).toMatchObject({ status: 'failed', error: { code: 'FETCH_CHAIN_UNAVAILABLE' } }); expect(calls).toBe(0); });
  it('falls back when the first pipeline does not support the representation', async () => { const app = await runtime(['a.fetch', 'b.fetch'], { b: async (url, _signal, representation) => document(url, 'b', representation) }, { representations: { a: ['text'], b: ['markdown'] }, quality: { min_content_chars: 0, blocked_markers: [] } }); const value = await app.runtime.fetch({ action: 'run', source: { kind: 'url', url: 'https://example.com' }, representation: 'markdown' }); expect(value.documents[0]?.source_lane).toBe('b.fetch'); const explicit = await app.runtime.fetch({ action: 'run', source: { kind: 'url', url: 'https://example.com' }, pipeline: 'a.fetch', representation: 'markdown' }); expect(explicit).toMatchObject({ status: 'failed', error: { code: 'FETCH_PIPELINE_UNSUPPORTED' } }); });
});
type FetchBehavior = (url: string, signal: AbortSignal, representation: 'markdown' | 'text') => Promise<FetchProviderResult>;
async function runtime(chain: string[], behaviors: Record<string, FetchBehavior> = {}, options: { quality?: { min_content_chars: number; blocked_markers: string[] }; max_provider_calls?: number; chainKind?: 'url' | 'inline_text'; representations?: Record<string, Array<'markdown' | 'text'>> } = {}) { const root = await mkdtemp(join(tmpdir(), 'nb-search-fetch-chain-')); roots.push(root); const ids = [...new Set([...chain.map(prefix), ...Object.keys(behaviors)])]; const registrations = ids.map((id) => registration(id, behaviors[id], options.representations?.[id])); const provider_instances: Record<string, { provider_id: string; enabled: boolean; options: {} }> = {}; const lanes: Record<string, { provider_instance_id: string; operation_id: string; latency: 'fast'; cost: 'free' }> = {}; for (const id of ids) { provider_instances[`${id}.default`] = { provider_id: id, enabled: true, options: {} }; lanes[`${id}.fetch`] = { provider_instance_id: `${id}.default`, operation_id: 'fetch', latency: 'fast', cost: 'free' }; } const config: CanonicalConfigPatch = { home: root, jobs_root: join(root, 'jobs'), provider_instances, lanes, defaults: { fetch_chain: [{ input_kind: options.chainKind ?? 'url', pipelines: chain }] }, execution: { retry_count: 0, max_provider_calls: options.max_provider_calls ?? 64, fetch: { quality: options.quality ?? { min_content_chars: 500, blocked_markers: [] } } } }; return createRuntimeComposition({}, { cwd: root, homeDirectory: root, config, provider_registrations: registrations }); }
function registration(id: string, behavior: FetchBehavior | undefined, representations: Array<'markdown' | 'text'> = ['markdown', 'text']): ProviderRegistration { return { descriptor: { provider_id: id, adapter_version: 'test-1', query_operations: [], fetch_operations: [{ operation_id: 'fetch', schema_id: 'nb-search.fetch@1', input_kinds: ['url'], media_types: ['text/plain'], representations, execution_modes: ['sync'], egress: 'url', stages: [{ id: `${id}.fetch`, role: 'reader' }] }], activation: { credential: 'none', endpoint: 'none' }, option_keys: [] }, create: () => ({ query: {}, fetch: { fetch: { name: id, async fetch(request) { if (request.source.kind !== 'url') throw new Error(); return await (behavior?.(request.source.url, request.signal, request.representation) ?? Promise.resolve(document(request.source.url, 'default'.repeat(100), request.representation))); } } } }) }; }
function prefix(lane: string): string { return lane.split('.')[0]!; }
