import { mkdtemp, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import { fetchInputSchema } from '../src/contracts.ts';
import { DirectFetchProvider, htmlToText, isPublicAddress, type DirectFetchIo } from '../src/fetch-security.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
const signal = new AbortController().signal;
const request = (url: string) => ({ source: { kind: 'url' as const, url }, representation: 'markdown' as const, signal, max_source_bytes: 1024, max_response_bytes: 1024, max_content_chars: 100, max_redirects: 1, file_scopes: [] });
describe('fetch contract and safety', () => {
  it('accepts all source variants and rejects invalid source combinations', () => { for (const source of [{ kind: 'url', url: 'https://example.com' }, { kind: 'inline_text', content: 'x', media_type: 'text/plain' }, { kind: 'inline_bytes', content_base64: 'eA==', media_type: 'text/plain' }, { kind: 'file', path: 'a.txt', scope: 'docs' }]) expect(fetchInputSchema.safeParse({ action: 'run', source }).success).toBe(true); expect(fetchInputSchema.safeParse({ action: 'run', source: { kind: 'inline_text', content: 'x', media_type: 'application/json' } }).success).toBe(false); expect(fetchInputSchema.safeParse({ url: 'https://example.com' }).success).toBe(true); });
  it('blocks non-public and non-HTTP targets', async () => { for (const address of ['127.0.0.1', '10.0.0.1', '169.254.169.254', '::1', 'fc00::1', '2001:db8::1']) expect(isPublicAddress(address)).toBe(false); const provider = new DirectFetchProvider({ async resolve() { return ['127.0.0.1']; }, async request() { throw new Error('no request'); } }); await expect(provider.fetch(request('https://example.com'))).rejects.toMatchObject({ code: 'FETCH_BLOCKED' }); });
  it('revalidates redirects and rejects binary MIME', async () => { const io: DirectFetchIo = { async resolve(host) { return host === 'public.example' ? ['8.8.8.8'] : ['10.0.0.1']; }, async request() { return { status: 302, headers: { location: 'https://private.example' }, body: new Uint8Array(), truncated: false }; } }; await expect(new DirectFetchProvider(io).fetch(request('https://public.example'))).rejects.toMatchObject({ code: 'FETCH_BLOCKED' }); const binary = new DirectFetchProvider({ async resolve() { return ['8.8.8.8']; }, async request() { return { status: 200, headers: { 'content-type': 'application/pdf' }, body: new Uint8Array([1]), truncated: false }; } }); await expect(binary.fetch(request('https://example.com/a.pdf'))).rejects.toMatchObject({ code: 'FETCH_CONTENT_TYPE_REJECTED' }); });
  it('performs HTML text conversion without scripts', async () => { const html = '<title>A &amp; B</title><style>hidden</style><h1>Hello</h1><script>bad()</script><p>World</p>'; expect(htmlToText(html)).toMatchObject({ title: 'A & B' }); expect(htmlToText(html).content).not.toContain('bad()'); });
  it('reads inline and scoped files without exposing physical roots', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-files-')); roots.push(root); const scope = join(root, 'scope'); const outside = join(root, 'outside.txt'); await import('node:fs/promises').then(({ mkdir }) => mkdir(scope)); await writeFile(join(scope, 'inside.md'), '# Hello'); await writeFile(outside, 'outside'); const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, config: { home: root, jobs_root: join(root, 'jobs'), fetch: { file_scopes: [{ id: 'docs', root: scope, media_types: ['text/markdown'] }] }, execution: { fetch: { quality: { min_content_chars: 0, blocked_markers: [] } } } } }); const inline = await app.runtime.fetch({ action: 'run', source: { kind: 'inline_text', content: '<p>Hello <a href="guide">Docs</a></p><script>bad()</script>', media_type: 'text/html', base_url: 'https://example.com/base/' } }); expect(inline).toMatchObject({ status: 'succeeded', documents: [{ content: 'Hello [Docs](https://example.com/base/guide)', representation: 'markdown', media_type: 'text/html' }] }); const file = await app.runtime.fetch({ action: 'run', source: { kind: 'file', path: 'inside.md', scope: 'docs' } }); expect(file).toMatchObject({ status: 'succeeded', documents: [{ content: '# Hello', media_type: 'text/markdown' }] }); expect(JSON.stringify(await app.runtime.capabilities())).not.toContain(scope); const escape = await app.runtime.fetch({ action: 'run', source: { kind: 'file', path: '../outside.txt', scope: 'docs' } }); expect(escape).toMatchObject({ status: 'failed', error: { code: 'FETCH_FILE_BLOCKED' } }); const unknown = await app.runtime.fetch({ action: 'run', source: { kind: 'file', path: 'inside.md', scope: 'missing' } }); expect(unknown).toMatchObject({ status: 'failed', error: { code: 'FETCH_SCOPE_NOT_FOUND' } }); });
  it('rejects symlink escape and oversized inline bytes before pipeline execution', async () => { const root = await mkdtemp(join(tmpdir(), 'nb-search-file-link-')); roots.push(root); const scope = join(root, 'scope'); const outside = join(root, 'outside.txt'); const { mkdir } = await import('node:fs/promises'); await mkdir(scope); await writeFile(outside, 'outside'); try { await symlink(outside, join(scope, 'link.txt')); } catch { return; } const app = createRuntimeComposition({}, { cwd: root, homeDirectory: root, config: { home: root, jobs_root: join(root, 'jobs'), fetch: { file_scopes: [{ id: 'docs', root: scope }] }, execution: { fetch: { max_source_bytes: 2, quality: { min_content_chars: 0, blocked_markers: [] } } } } }); expect(await app.runtime.fetch({ action: 'run', source: { kind: 'file', path: 'link.txt', scope: 'docs' } })).toMatchObject({ status: 'failed', error: { code: 'FETCH_FILE_BLOCKED' } }); expect(await app.runtime.fetch({ action: 'run', source: { kind: 'inline_bytes', content_base64: Buffer.from('large').toString('base64'), media_type: 'text/plain' } })).toMatchObject({ status: 'failed', error: { code: 'FETCH_BYTES_LIMIT' } }); });
});
