import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import { builtInProviderRegistrations, ProviderRegistry, type ProviderRegistration } from '../src/provider-registry.ts';
import { mockConfig, mockRegistration } from './helpers.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
async function root() { const value = await mkdtemp(join(tmpdir(), 'nb-search-registry-v1-')); roots.push(value); return value; }
describe('query operation registry', () => {
  it('is the output-channel and schema-id source of truth', () => { const registry = new ProviderRegistry(builtInProviderRegistrations()); expect(registry.operation('exa', 'search')).toEqual({ operation_id: 'search', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }); expect(registry.operation('exa', 'synthesis')?.output).toEqual({ channel: 'typed', schema_id: 'nb-search.synthesis@1' }); expect(registry.operation('tavily', 'synthesis')?.output.schema_id).toBe('nb-search.synthesis@1'); expect(registry.operation('grok-multi-agent', 'research')?.output.schema_id).toBe('nb-search.multi-agent-research@1'); });
  it('rejects invalid schemas and extra operation/output descriptor keys at registration', () => { for (const operation of [{ operation_id: 'bad', output: { channel: 'results', schema_id: 'wrong.results@1' }, built_in_async: false }, { operation_id: 'bad', output: { channel: 'typed', schema_id: '   ' }, built_in_async: false }, { operation_id: 'bad', output: { channel: 'results', schema_id: 'nb-search.results@1', extra: true }, built_in_async: false }, { operation_id: 'bad', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: false, extra: true }]) { const base = mockRegistration(); const malformed = { ...base, descriptor: { ...base.descriptor, query_operations: [operation] } } as unknown as ProviderRegistration; expect(() => new ProviderRegistry([], [malformed])).toThrow(/descriptor is invalid/); } });
  it('clones and freezes descriptors so caller mutation cannot alter the registry', () => { const registration = mockRegistration(); const registry = new ProviderRegistry([], [registration]); const mutable = registration.descriptor as unknown as { provider_id: string; query_operations: Array<{ operation_id: string; output: { channel: string; schema_id: string } }> }; mutable.provider_id = 'mutated'; mutable.query_operations[0]!.operation_id = 'mutated'; mutable.query_operations[0]!.output.schema_id = 'mutated@1'; expect(registry.descriptor('mock')?.provider_id).toBe('mock'); expect(registry.operation('mock', 'results')).toEqual({ operation_id: 'results', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }); expect(Object.isFrozen(registry.descriptor('mock'))).toBe(true); expect(Object.isFrozen(registry.operation('mock', 'results')?.output)).toBe(true); });
  it('rejects a mismatched credential at the provider factory boundary', () => { let calls = 0; const base = mockRegistration(); const registration: ProviderRegistration = { ...base, create(context) { calls += 1; return base.create(context); } }; const registry = new ProviderRegistry([], [registration]); let caught: unknown; try { registry.create('mock.default', { provider_id: 'mock', enabled: true, credential_slot_id: 'mock.slot', options: {} }, { credential: { credential_slot_id: 'mock.slot', provider_id: 'other-provider', value: 'factory-secret', worker_grant: { kind: 'environment', name: 'FACTORY_SECRET' } }, transports: { http: { async send() { throw new Error('must not send'); } } }, clock: () => new Date() }); } catch (error) { caught = error; } expect(caught).toMatchObject({ code: 'CONFIGURATION_ERROR' }); expect(String(caught)).not.toContain('factory-secret'); expect(calls).toBe(0); });
  it('reports custom query registrations as sync-only even when descriptor claims built-in async', async () => { const home = await root(); const app = createRuntimeComposition({}, { cwd: home, homeDirectory: home, config: mockConfig(home), provider_registrations: [mockRegistration()] }); const capabilities = await app.runtime.capabilities(); expect(capabilities.search.lanes.find((lane) => lane.id === 'mock.results')?.execution_modes).toEqual(['sync']); expect(capabilities.search.lanes.find((lane) => lane.id === 'mock.typed')?.execution_modes).toEqual(['sync']); });
  it('fails an execution unit when provider output channel disagrees with the descriptor', async () => { const home = await root(); const base = mockRegistration(); const mismatch: ProviderRegistration = { ...base, create(context) { const ports = base.create(context); return { ...ports, query: { ...ports.query, results: { name: 'mock', async execute() { return { channel: 'typed', data: { wrong: true } }; } } } }; } }; const app = createRuntimeComposition({}, { cwd: home, homeDirectory: home, config: mockConfig(home), provider_registrations: [mismatch] }); const result = await app.runtime.search({ action: 'run', query: 'q', lane: 'mock.results' }); expect(result).toMatchObject({ status: 'failed', output: { channel: 'results', status: 'failed', results: [], lane_outcomes: [{ state: 'failed', error: { code: 'PROVIDER_UNAVAILABLE' } }] } }); });
  it('rejects custom typed async before execution without fabricating resolved contract fields', async () => { const home = await root(); let calls = 0; const app = createRuntimeComposition({}, { cwd: home, homeDirectory: home, config: mockConfig(home), provider_registrations: [mockRegistration({ async typed() { calls += 1; return {}; } })], launcher: { async launch() { throw new Error('must not launch'); } } }); const result = await app.runtime.search({ action: 'run', query: 'q', lane: 'mock.typed', execution: 'async', idempotency_key: 'custom-typed-async' }); expect(result).toMatchObject({ action: 'run', execution: 'async', status: 'failed', error: { code: 'LANE_EXECUTION_UNSUPPORTED' } }); expect(result).not.toHaveProperty('selection'); expect(result).not.toHaveProperty('channel'); expect(result).not.toHaveProperty('schema_id'); expect(calls).toBe(0); expect(await app.store.listRecords()).toHaveLength(0); });
});
