import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { createRuntimeComposition } from '../src/app.ts';
import type { LaneBinding } from '../src/config.ts';
import { searchInputSchema } from '../src/contracts.ts';
import { outputByteLength, outputExceedsInlineLimit } from '../src/core.ts';
import { NbSearchError } from '../src/errors.ts';
import { mergeResultLists } from '../src/planner.ts';
import type { ProviderResult } from '../src/types.ts';
import { mockConfig, mockRegistration } from './helpers.ts';
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
async function setup(behavior = {}, execution = {}) { const root = await mkdtemp(join(tmpdir(), 'nb-search-search-v3-')); roots.push(root); const base = mockConfig(root); return { root, app: createRuntimeComposition({}, { cwd: root, homeDirectory: root, config: { ...base, execution: { retry_count: 0, ...execution } }, provider_registrations: [mockRegistration(behavior)] }) }; }
describe('search discriminated runtime', () => {
  it('accepts only run/get/read/cancel and rejects removed request fields', () => { const id = '00000000-0000-4000-8000-000000000000'; for (const value of [{ action: 'run', query: 'q' }, { action: 'get', job_id: id }, { action: 'read', job_id: id }, { action: 'cancel', job_id: id }]) expect(searchInputSchema.safeParse(value).success).toBe(true); for (const value of [{ action: 'status', job_id: id }, { action: 'run', query: 'q', output_kind: 'typed' }, { action: 'run', query: 'q', view: 'full' }, { action: 'run', query: 'q', external_results: [] }]) expect(searchInputSchema.safeParse(value).success).toBe(false); });
  it('requires async idempotency and forbids it for sync without creating jobs', async () => { const { app } = await setup(); await expect(app.runtime.search({ action: 'run', query: 'q', execution: 'async' } as never)).rejects.toThrow(); await expect(app.runtime.search({ action: 'run', query: 'q', execution: 'sync', idempotency_key: 'bad' } as never)).rejects.toThrow(); expect(await app.store.listRecords()).toHaveLength(0); });
  it('returns canonical results output with an exact merge summary projection', async () => { const { app } = await setup(); const envelope = await app.runtime.search({ action: 'run', query: ['one', 'two'], lane: 'mock.results' }); expect(envelope).toMatchObject({ action: 'run', execution: 'sync', status: 'succeeded', selection: { source: 'lane', lanes: ['mock.results'] }, output: { channel: 'results', schema_id: 'nb-search.results@1', status: 'succeeded', merge_summary: { result_count: 2 } } }); if (envelope.action !== 'run' || envelope.execution !== 'sync' || envelope.output?.channel !== 'results') throw new Error(); expect(Object.keys(envelope.output.merge_summary).sort()).toEqual(['canonical_dedup', 'independent_evidence_groups', 'input_rows', 'result_count']); expect(envelope.output.merge_summary).not.toHaveProperty('results'); });
  it('returns schema-bound JSON for a single typed lane', async () => { const { app } = await setup({ async typed(query: string) { return { text: `typed:${query}`, citation_status: { semantic_verification: false } }; } }); const envelope = await app.runtime.search({ action: 'run', query: 'q', lane: 'mock.typed' }); expect(envelope).toMatchObject({ action: 'run', execution: 'sync', output: { channel: 'typed', lane: 'mock.typed', schema_id: 'test.typed@1', data: { text: 'typed:q', citation_status: { semantic_verification: false } } } }); });
  it('rejects typed lanes in lanes and mixed selections before execution', async () => { let calls = 0; const { app } = await setup({ async typed() { calls += 1; return {}; } }); const result = await app.runtime.search({ action: 'run', query: 'q', lanes: ['mock.results', 'mock.typed'] }); expect(result).toMatchObject({ status: 'failed', error: { code: 'MIXED_OUTPUT_UNSUPPORTED' } }); expect(result).not.toHaveProperty('selection'); expect(calls).toBe(0); });
  it('returns OUTPUT_TOO_LARGE without truncation, persistence, or automatic async', async () => { let calls = 0; const { app } = await setup({ async typed() { calls += 1; return { text: 'x'.repeat(5000), tail: 'preserve' }; } }, { max_inline_bytes: 1024 }); const result = await app.runtime.search({ action: 'run', query: 'q', lane: 'mock.typed' }); expect(result).toMatchObject({ execution: 'sync', status: 'failed', error: { code: 'OUTPUT_TOO_LARGE' } }); expect('output' in result).toBe(false); expect(calls).toBe(1); expect(await app.store.listRecords()).toHaveLength(0); });
  it('accepts an inline output at the exact byte limit and rejects one byte below it', () => { const value = { text: 'boundary🙂' }; const bytes = outputByteLength(value); expect(outputExceedsInlineLimit(value, bytes)).toBe(false); expect(outputExceedsInlineLimit(value, bytes - 1)).toBe(true); });
  it('counts retries in max_provider_calls at zero-call preflight', async () => { let calls = 0; const { app } = await setup({ async results() { calls += 1; return []; } }, { retry_count: 1, max_provider_calls: 1 }); const result = await app.runtime.search({ action: 'run', query: 'q' }); expect(result).toMatchObject({ status: 'failed', error: { code: 'BUDGET_EXCEEDED' } }); expect(calls).toBe(0); });
  it('normalizes deadline and caller abort during retry backoff without a second call', async () => { for (const mode of ['deadline', 'cancel'] as const) { let calls = 0; const { app } = await setup({ async results() { calls += 1; throw new NbSearchError('PROVIDER_UNAVAILABLE', 'retry', true, 'mock'); } }, { retry_count: 1, max_provider_calls: 2 }); const controller = new AbortController(); if (mode === 'cancel') setTimeout(() => controller.abort(), 10); const result = await app.runtime.search({ action: 'run', query: 'q', timeout_ms: 100 }, { signal: mode === 'cancel' ? controller.signal : undefined }); expect(result).toMatchObject({ status: mode === 'cancel' ? 'cancelled' : 'timed_out' }); await new Promise((resolve) => setTimeout(resolve, 120)); expect(calls).toBe(1); } });
});
describe('results fusion assets', () => {
  const lane = (id: string, provider: string, groups?: string[]): LaneBinding => ({ id, config: { provider_instance_id: id, operation_id: 'results', latency: 'fast', cost: 'free', ...(groups === undefined ? {} : { evidence_groups: groups }) }, instance: { provider_id: provider, enabled: true, options: {} }, provider_id: provider, built_in: true, query_operation: { operation_id: 'results', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }, query_provider: { name: provider, async execute() { throw new Error(); } }, availability: 'ready', issues: [], execution_modes: ['sync', 'async'] });
  it('deduplicates within each list before RRF while retaining provenance', () => { const rows: ProviderResult[] = [{ title: 'A', url: 'https://x/a', snippet: '' }, { title: 'A2', url: 'https://x/a?utm_source=x', snippet: 'filled' }]; const merged = mergeResultLists([{ lane: lane('one', 'one', ['same']), query_index: 0, rows }, { lane: lane('two', 'two', ['same']), query_index: 0, rows: [{ title: 'A', url: 'https://x/a' }] }], 10); expect(merged.results[0]?.rrf_score).toBeCloseTo(2 / 61, 12); expect(merged.results[0]?.provenance).toHaveLength(3); expect(merged.results[0]?.snippet).toBe('filled'); });
});
