import { randomUUID } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CanonicalConfigPatch } from './config-schema.ts';
import { CONFIG_SCHEMA_VERSION } from './config-schema.ts';
import { loadConfiguration, type AppConfiguration, type LaneBinding } from './config.ts';
import { QueryEngine } from './core.ts';
import { assertSnapshotOperations, resolveSnapshotBindings, type ExecutionSnapshot } from './execution-snapshot.ts';
import type { DirectFetchIo } from './fetch-security.ts';
import { JobStore } from './job-store.ts';
import { builtInProviderRegistrations, ProviderRegistry, type ProviderPorts, type ProviderRegistration } from './provider-registry.ts';
import { DetachedWorkerLauncher, inputFromSnapshot, QueryJobRunner, QueryJobService, type WorkerLauncher } from './query-jobs.ts';
import { NbSearchRuntimeImpl } from './runtime.ts';
import { FetchJsonTransport, type JsonTransport } from './transport.ts';

export interface RuntimeComposition { config: AppConfiguration; runtime: NbSearchRuntimeImpl; store: JobStore }
export interface CompositionOptions { transport?: JsonTransport; launcher?: WorkerLauncher; now?: () => Date; config?: CanonicalConfigPatch; overrides?: CanonicalConfigPatch; provider_registrations?: readonly ProviderRegistration[]; test_only_direct_fetch_io?: DirectFetchIo; cwd?: string; homeDirectory?: string }
export function createRuntimeComposition(env: NodeJS.ProcessEnv = process.env, options: CompositionOptions = {}): RuntimeComposition { const config = loadConfiguration(env, options.transport, { ...(options.config === undefined ? {} : { config: options.config }), ...(options.overrides === undefined ? {} : { overrides: options.overrides }), ...(options.provider_registrations === undefined ? {} : { provider_registrations: options.provider_registrations }), ...(options.test_only_direct_fetch_io === undefined ? {} : { test_only_direct_fetch_io: options.test_only_direct_fetch_io }), ...(options.now === undefined ? {} : { now: options.now }), ...(options.cwd === undefined ? {} : { cwd: options.cwd }), ...(options.homeDirectory === undefined ? {} : { homeDirectory: options.homeDirectory }) }); const store = new JobStore(config.jobs_root, options.now); const workerPath = resolve(dirname(fileURLToPath(import.meta.url)), 'worker.mjs'); const launcher = options.launcher ?? new DetachedWorkerLauncher(workerPath, env); const jobs = new QueryJobService(store, launcher, config); const runtime = new NbSearchRuntimeImpl(config, jobs, options.now); return { config, runtime, store }; }
export function createQueryJobRunnerFromSnapshot(snapshot: ExecutionSnapshot, store: JobStore, env: NodeJS.ProcessEnv = process.env, options: Pick<CompositionOptions, 'transport' | 'now'> = {}): QueryJobRunner {
  const retentionHours = snapshot.request.result_ttl_seconds / 3600; const registry = new ProviderRegistry(builtInProviderRegistrations()); assertSnapshotOperations(snapshot, registry); const bindings = resolveSnapshotBindings(snapshot, env); const ports = new Map<string, ProviderPorts>(); const lanes: Record<string, LaneBinding> = {}; const instances: Record<string, import('./config-schema.ts').ProviderInstanceConfig> = {}; const laneConfigs: Record<string, import('./config-schema.ts').LaneConfig> = {};
  for (const selected of snapshot.selected) { instances[selected.provider_instance_id] = selected.provider_instance; laneConfigs[selected.lane_id] = selected.lane; let instancePorts = ports.get(selected.provider_instance_id); if (instancePorts === undefined) { const credential = selected.provider_instance.credential_slot_id === undefined ? undefined : bindings.get(selected.provider_instance.credential_slot_id); instancePorts = registry.create(selected.provider_instance_id, selected.provider_instance, { ...(credential === undefined ? {} : { credential }), transports: { http: options.transport ?? new FetchJsonTransport() }, clock: options.now ?? (() => new Date()) }); ports.set(selected.provider_instance_id, instancePorts); } const provider = instancePorts.query[selected.lane.operation_id]; if (provider === undefined) throw new Error(`Worker operation missing: ${selected.lane_id}`); lanes[selected.lane_id] = { id: selected.lane_id, config: selected.lane, instance: selected.provider_instance, provider_id: selected.provider_instance.provider_id, built_in: true, query_operation: selected.operation, query_provider: provider, availability: 'ready', issues: [], execution_modes: ['sync', 'async'] }; }
  const config = { schema_version: CONFIG_SCHEMA_VERSION, home: store.root, jobs_root: store.root, retention_hours: retentionHours, log_level: 'warn' as const, provider_instances: instances, credential_slots: {}, lanes: laneConfigs, defaults: {}, presets: {}, execution: { max_provider_calls: snapshot.request.max_provider_calls, max_concurrency: snapshot.request.max_concurrency, retry_count: snapshot.request.retry_count, search_timeout_ms: snapshot.request.timeout_ms, fetch_timeout_ms: 60_000, max_inline_bytes: 64 * 1024, fetch: { max_response_bytes: 2 * 1024 * 1024, max_content_chars: 200_000, max_redirects: 5, quality: { min_content_chars: 500, blocked_markers: [] } } } };
  const app: AppConfiguration = { home: store.root, jobs_root: store.root, retention_hours: retentionHours, log_level: 'warn', resolved: { config, config_revision: 'snapshot', config_fingerprint: snapshot.snapshot_fingerprint, secret_bindings: bindings, canonical_path: '' }, registry, ports_by_instance: ports, lanes };
  const selected = { selection: { source: snapshot.selected.length === 1 ? 'lane' as const : 'lanes' as const, lanes: snapshot.selected.map((item) => item.lane_id) }, lanes: snapshot.selected.map((item) => lanes[item.lane_id]!), channel: snapshot.selected[0]!.operation.output.channel, schema_id: snapshot.selected[0]!.operation.output.schema_id }; const input = inputFromSnapshot(snapshot); return new QueryJobRunner(store, new QueryEngine(app, options.now), selected, input, snapshot.request.result_ttl_seconds);
}
