import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { BrowserRenderIo } from './browser-render.ts';
import type { CanonicalConfigPatch } from './config-schema.ts';
import { CONFIG_SCHEMA_VERSION } from './config-schema.ts';
import { loadConfiguration, configurationFromResolved, type AppConfiguration, type LaneBinding } from './config.ts';
import { FetchService, QueryEngine } from './core.ts';
import { assertSnapshotOperations, resolveSnapshotBindings, type ExecutionSnapshot, type FetchJobRequest, type QueryJobRequest } from './execution-snapshot.ts';
import type { DirectFetchIo } from './fetch-security.ts';
import { JobStore } from './job-store.ts';
import { builtInProviderRegistrations, builtInProviderRegistrationsForInternalTest, ProviderRegistry, type ProviderPorts, type ProviderRegistration } from './provider-registry.ts';
import { DetachedWorkerLauncher, fetchInputFromSnapshot, FetchJobRunner, inputFromSnapshot, QueryJobRunner, QueryJobService, type WorkerLauncher } from './query-jobs.ts';
import { NbSearchRuntimeImpl } from './runtime.ts';
import { FetchJsonTransport, type JsonTransport } from './transport.ts';

export interface RuntimeComposition { config: AppConfiguration; runtime: NbSearchRuntimeImpl; store: JobStore }
export interface CompositionOptions { transport?: JsonTransport; disable_detached_async?: boolean; launcher?: WorkerLauncher; now?: () => Date; config?: CanonicalConfigPatch; overrides?: CanonicalConfigPatch; provider_registrations?: readonly ProviderRegistration[]; test_only_direct_fetch_io?: DirectFetchIo; test_only_browser_render_io?: BrowserRenderIo; cwd?: string; homeDirectory?: string }
export function createRuntimeComposition(env: NodeJS.ProcessEnv = process.env, options: CompositionOptions = {}): RuntimeComposition { const config = loadConfiguration(env, options.transport, { ...(options.config === undefined ? {} : { config: options.config }), ...(options.overrides === undefined ? {} : { overrides: options.overrides }), ...(options.provider_registrations === undefined ? {} : { provider_registrations: options.provider_registrations }), ...(options.test_only_direct_fetch_io === undefined ? {} : { test_only_direct_fetch_io: options.test_only_direct_fetch_io }), ...(options.test_only_browser_render_io === undefined ? {} : { test_only_browser_render_io: options.test_only_browser_render_io }), ...(options.now === undefined ? {} : { now: options.now }), ...(options.cwd === undefined ? {} : { cwd: options.cwd }), ...(options.homeDirectory === undefined ? {} : { homeDirectory: options.homeDirectory }) }); return composeConfiguration(config, env, options); }
export function createCapturedRuntimeComposition(resolved: import('./config-sources.ts').ResolvedConfiguration, env: NodeJS.ProcessEnv, options: CompositionOptions = {}): RuntimeComposition { return composeConfiguration(configurationFromResolved(resolved, options.transport, options), { ...env }, options); }
function composeConfiguration(config: AppConfiguration, env: NodeJS.ProcessEnv, options: CompositionOptions): RuntimeComposition {
  if (options.disable_detached_async) for (const lane of Object.values(config.lanes)) {
    lane.execution_modes = lane.execution_modes.filter((mode) => mode !== 'async');
    if (lane.fetch_operation?.execution_modes.includes('async') && !lane.fetch_operation.execution_modes.includes('sync')) {
      lane.availability = 'unavailable'; lane.issues.push('LANE_EXECUTION_UNSUPPORTED');
    }
  }
  const store = new JobStore(config.jobs_root, options.now); const workerPath = resolve(dirname(fileURLToPath(import.meta.url)), 'worker.mjs'); const launcher = options.launcher ?? new DetachedWorkerLauncher(workerPath, env); const jobs = new QueryJobService(store, launcher, config); const runtime = new NbSearchRuntimeImpl(config, jobs, options.now, options.disable_detached_async); return { config, runtime, store };
}
export function createQueryJobRunnerFromSnapshot(snapshot: ExecutionSnapshot, store: JobStore, env: NodeJS.ProcessEnv = process.env, options: Pick<CompositionOptions, 'transport' | 'now'> = {}): QueryJobRunner {
  if (snapshot.kind !== 'search') throw new Error('Expected search snapshot.'); const app = appFromSnapshot(snapshot, store, env, options); const request = snapshot.request as QueryJobRequest; const selected = { selection: { source: snapshot.selected.length === 1 ? 'lane' as const : 'lanes' as const, lanes: snapshot.selected.map((item) => item.lane_id) }, lanes: snapshot.selected.map((item) => app.lanes[item.lane_id]!), channel: (snapshot.selected[0]!.operation as import('./types.ts').QueryOperationDescriptor).output.channel, schema_id: (snapshot.selected[0]!.operation as import('./types.ts').QueryOperationDescriptor).output.schema_id }; return new QueryJobRunner(store, new QueryEngine(app, options.now), selected, inputFromSnapshot(snapshot), request.result_ttl_seconds);
}
export function createFetchJobRunnerFromSnapshot(snapshot: ExecutionSnapshot, store: JobStore, env: NodeJS.ProcessEnv = process.env, options: Pick<CompositionOptions, 'transport' | 'now' | 'test_only_browser_render_io'> = {}): FetchJobRunner {
  if (snapshot.kind !== 'fetch') throw new Error('Expected fetch snapshot.'); const app = appFromSnapshot(snapshot, store, env, options); const request = snapshot.request as FetchJobRequest; const pipelines = request.pipelines.map((id) => app.lanes[id]!); return new FetchJobRunner(store, new FetchService(app), { source: request.selection, lanes: pipelines, ...(request.selection === 'pipeline' ? { requested: request.pipelines[0]! } : {}) }, fetchInputFromSnapshot(snapshot), request.result_ttl_seconds);
}
function appFromSnapshot(snapshot: ExecutionSnapshot, store: JobStore, env: NodeJS.ProcessEnv, options: Pick<CompositionOptions, 'transport' | 'now' | 'test_only_browser_render_io'>): AppConfiguration {
  const retentionHours = snapshot.request.result_ttl_seconds / 3600; const builtIns = options.test_only_browser_render_io === undefined ? builtInProviderRegistrations() : builtInProviderRegistrationsForInternalTest(undefined, options.test_only_browser_render_io); const registry = new ProviderRegistry(builtIns); assertSnapshotOperations(snapshot, registry); const bindings = resolveSnapshotBindings(snapshot, env); const ports = new Map<string, ProviderPorts>(); const lanes: Record<string, LaneBinding> = {}; const instances: Record<string, import('./config-schema.ts').ProviderInstanceConfig> = {}; const laneConfigs: Record<string, import('./config-schema.ts').LaneConfig> = {};
  for (const selected of snapshot.selected) { instances[selected.provider_instance_id] = selected.provider_instance; laneConfigs[selected.lane_id] = selected.lane; let instancePorts = ports.get(selected.provider_instance_id); if (instancePorts === undefined) { const credential = selected.provider_instance.credential_slot_id === undefined ? undefined : bindings.get(selected.provider_instance.credential_slot_id); instancePorts = registry.create(selected.provider_instance_id, selected.provider_instance, { ...(credential === undefined ? {} : { credential }), transports: { http: options.transport ?? new FetchJsonTransport() }, clock: options.now ?? (() => new Date()) }); ports.set(selected.provider_instance_id, instancePorts); } const queryOperation = registry.operation(selected.provider_instance.provider_id, selected.lane.operation_id); const fetchOperation = registry.fetchOperation(selected.provider_instance.provider_id, selected.lane.operation_id); const queryProvider = instancePorts.query[selected.lane.operation_id]; const fetchProvider = instancePorts.fetch[selected.lane.operation_id]; lanes[selected.lane_id] = { id: selected.lane_id, config: selected.lane, instance: selected.provider_instance, provider_id: selected.provider_instance.provider_id, built_in: true, ...(queryOperation === undefined ? {} : { query_operation: queryOperation }), ...(fetchOperation === undefined ? {} : { fetch_operation: fetchOperation }), ...(queryProvider === undefined ? {} : { query_provider: queryProvider }), ...(fetchProvider === undefined ? {} : { fetch_provider: fetchProvider }), availability: 'ready', issues: [], execution_modes: ['sync', 'async'] }; }
  const search = snapshot.kind === 'search' ? snapshot.request as QueryJobRequest : undefined; const fetch = snapshot.kind === 'fetch' ? snapshot.request as FetchJobRequest : undefined;
  const config = { schema_version: CONFIG_SCHEMA_VERSION, home: store.root, jobs_root: store.root, retention_hours: retentionHours, log_level: 'warn' as const, provider_instances: instances, credential_slots: {}, lanes: laneConfigs, defaults: {}, presets: {}, fetch: { file_scopes: fetch?.file_scopes ?? [] }, execution: { max_provider_calls: search?.max_provider_calls ?? fetch!.max_provider_calls, max_concurrency: search?.max_concurrency ?? 1, retry_count: search?.retry_count ?? fetch!.retry_count, search_timeout_ms: search?.timeout_ms ?? 30_000, fetch_timeout_ms: fetch?.timeout_ms ?? 60_000, max_inline_bytes: 64 * 1024, fetch: { max_source_bytes: fetch?.max_source_bytes ?? 2 * 1024 * 1024, max_response_bytes: fetch?.max_response_bytes ?? 2 * 1024 * 1024, max_content_chars: fetch?.max_content_chars ?? 200_000, max_redirects: fetch?.max_redirects ?? 5, quality: fetch?.quality ?? { min_content_chars: 500, blocked_markers: [] } } } };
  return { home: store.root, jobs_root: store.root, retention_hours: retentionHours, log_level: 'warn', resolved: { config, config_revision: 'snapshot', config_fingerprint: snapshot.snapshot_fingerprint, secret_bindings: bindings, canonical_path: '' }, registry, ports_by_instance: ports, lanes };
}
