#!/usr/bin/env node
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { invalidInput, publicError } from './errors.ts';
import { createNbSearchRuntime } from './index.ts';
import type { NbSearchRuntime } from './runtime.ts';

export interface CliIo { stdout: { write(value: string): unknown }; stderr: { write(value: string): unknown } }
export async function runCli(argv: readonly string[], io: CliIo = process, createRuntime: () => NbSearchRuntime = () => createNbSearchRuntime()): Promise<number> { try { if (argv.length === 0 || argv.includes('--help') || argv.includes('-h')) { io.stdout.write(HELP); return 0; } const runtime = createRuntime(); const command = argv[0]; let output: unknown; if (command === 'search') output = await runSearch(runtime, argv.slice(1)); else if (command === 'fetch') output = await runFetch(runtime, argv.slice(1)); else if (command === 'capabilities') { if (argv.length !== 1) throw invalidInput('capabilities does not accept arguments.'); output = await runtime.capabilities(); } else throw invalidInput(`Unknown command: ${String(command)}.`); io.stdout.write(`${JSON.stringify(output)}\n`); return failed(output) ? 2 : 0; } catch (error) { io.stderr.write(`${JSON.stringify({ error: publicError(error, error instanceof Error ? error.message : 'The command failed.') })}\n`); return 2; } }
async function runSearch(runtime: NbSearchRuntime, argv: readonly string[]): Promise<unknown> { const action = argv[0]; if (action === 'get') return await runtime.search({ action: 'get', job_id: exactlyOne(argv.slice(1), 'search get requires one job_id.') }); if (action === 'cancel') return await runtime.search({ action: 'cancel', job_id: exactlyOne(argv.slice(1), 'search cancel requires one job_id.') }); if (action === 'read') { const parsed = parse(argv.slice(1), new Set(['--cursor', '--page-size'])); if (parsed.positionals.length !== 1) throw invalidInput('search read requires one job_id.'); return await runtime.search({ action: 'read', job_id: parsed.positionals[0]!, ...(one(parsed.options, '--cursor') === undefined ? {} : { cursor: one(parsed.options, '--cursor') }), ...(one(parsed.options, '--page-size') === undefined ? {} : { page_size: integer(one(parsed.options, '--page-size')!, '--page-size') }) }); } return await runSearchRun(runtime, action === 'run' ? argv.slice(1) : argv); }
async function runSearchRun(runtime: NbSearchRuntime, argv: readonly string[]): Promise<unknown> { const parsed = parse(argv, new Set(['--query', '--lane', '--lanes', '--preset', '--execution', '--idempotency-key', '--freshness', '--max-results', '--timeout-ms'])); const queries = [...parsed.positionals, ...(parsed.options['--query'] ?? [])]; if (queries.length < 1) throw invalidInput('search run requires at least one query.'); const execution = one(parsed.options, '--execution'); if (execution !== undefined && execution !== 'sync' && execution !== 'async') throw invalidInput('--execution must be sync or async.'); return await runtime.search({ action: 'run', query: queries.length === 1 ? queries[0]! : queries, ...selector(parsed.options), ...(execution === undefined ? {} : { execution }), ...(one(parsed.options, '--idempotency-key') === undefined ? {} : { idempotency_key: one(parsed.options, '--idempotency-key') }), ...(one(parsed.options, '--freshness') === undefined ? {} : { freshness: one(parsed.options, '--freshness') as 'pd' | 'pw' | 'pm' | 'py' }), ...(one(parsed.options, '--max-results') === undefined ? {} : { max_results: integer(one(parsed.options, '--max-results')!, '--max-results') }), ...(one(parsed.options, '--timeout-ms') === undefined ? {} : { timeout_ms: integer(one(parsed.options, '--timeout-ms')!, '--timeout-ms') }) }); }
async function runFetch(runtime: NbSearchRuntime, argv: readonly string[]): Promise<unknown> { const action = argv[0]; if (action === 'get') return await runtime.fetch({ action: 'get', job_id: exactlyOne(argv.slice(1), 'fetch get requires one job_id.') }); if (action === 'cancel') return await runtime.fetch({ action: 'cancel', job_id: exactlyOne(argv.slice(1), 'fetch cancel requires one job_id.') }); if (action === 'read') { const parsed = parse(argv.slice(1), new Set(['--cursor', '--page-size'])); if (parsed.positionals.length !== 1) throw invalidInput('fetch read requires one job_id.'); return await runtime.fetch({ action: 'read', job_id: parsed.positionals[0]!, ...(one(parsed.options, '--cursor') === undefined ? {} : { cursor: one(parsed.options, '--cursor') }), ...(one(parsed.options, '--page-size') === undefined ? {} : { page_size: integer(one(parsed.options, '--page-size')!, '--page-size') }) }); } const parsed = parse(action === 'run' ? argv.slice(1) : argv, new Set(['--pipeline', '--representation', '--execution', '--idempotency-key', '--timeout-ms', '--max-content-chars'])); if (parsed.positionals.length !== 1) throw invalidInput('fetch run requires one URL.'); const representation = one(parsed.options, '--representation'); if (representation !== undefined && representation !== 'markdown' && representation !== 'text') throw invalidInput('--representation must be markdown or text.'); const execution = one(parsed.options, '--execution'); if (execution !== undefined && execution !== 'sync' && execution !== 'async') throw invalidInput('--execution must be sync or async.'); return await runtime.fetch({ action: 'run', source: { kind: 'url', url: parsed.positionals[0]! }, ...(one(parsed.options, '--pipeline') === undefined ? {} : { pipeline: one(parsed.options, '--pipeline') }), ...(representation === undefined ? {} : { representation }), ...(execution === undefined ? {} : { execution }), ...(one(parsed.options, '--idempotency-key') === undefined ? {} : { idempotency_key: one(parsed.options, '--idempotency-key') }), ...(one(parsed.options, '--timeout-ms') === undefined ? {} : { timeout_ms: integer(one(parsed.options, '--timeout-ms')!, '--timeout-ms') }), ...(one(parsed.options, '--max-content-chars') === undefined ? {} : { max_content_chars: integer(one(parsed.options, '--max-content-chars')!, '--max-content-chars') }) }); }
function parse(argv: readonly string[], allowed: ReadonlySet<string>): { positionals: string[]; options: Record<string, string[]> } { const positionals: string[] = []; const options: Record<string, string[]> = {}; for (let index = 0; index < argv.length; index += 1) { const item = argv[index]!; if (!item.startsWith('--')) { positionals.push(item); continue; } if (!allowed.has(item)) throw invalidInput(`Unknown option: ${item}.`); const value = argv[index + 1]; if (value === undefined || value.startsWith('--')) throw invalidInput(`${item} requires a value.`); (options[item] ??= []).push(value); index += 1; } return { positionals, options }; }
function selector(options: Readonly<Record<string, string[]>>): { lane?: string; lanes?: string[]; preset?: string } { const repeated = options['--lane'] ?? []; const csv = one(options, '--lanes')?.split(',').filter(Boolean); const preset = one(options, '--preset'); if ([repeated.length > 0, csv !== undefined, preset !== undefined].filter(Boolean).length > 1) throw invalidInput('--lane, --lanes, and --preset are mutually exclusive.'); if (repeated.length === 1) return { lane: repeated[0]! }; if (repeated.length > 1) return { lanes: repeated }; if (csv !== undefined) return { lanes: csv }; return preset === undefined ? {} : { preset }; }
function one(options: Readonly<Record<string, string[]>>, name: string): string | undefined { const values = options[name]; if ((values?.length ?? 0) > 1 && name !== '--lane' && name !== '--query') throw invalidInput(`${name} may be provided once.`); return values?.[0]; }
function exactlyOne(values: readonly string[], message: string): string { const value = values[0]; if (values.length !== 1 || value === undefined || value.startsWith('-')) throw invalidInput(message); return value; }
function integer(value: string, name: string): number { const parsed = Number(value); if (!Number.isSafeInteger(parsed)) throw invalidInput(`${name} must be an integer.`); return parsed; }
function failed(value: unknown): boolean { if (value === null || typeof value !== 'object') return false; const item = value as { status?: unknown; state?: unknown }; return item.status === 'failed' || item.state === 'failed'; }
const HELP = `nb-search 0.1.0\n\nUsage:\n  nb-search search [run] <query> [--query <facet>] [--lane ID|--lanes A,B|--preset NAME] [--execution sync|async]\n  nb-search search get <job_id>\n  nb-search search read <job_id> [--cursor CURSOR] [--page-size N]\n  nb-search search cancel <job_id>\n  nb-search fetch [run] <url> [--pipeline ID] [--representation markdown|text] [--execution sync|async]\n  nb-search fetch get <job_id>\n  nb-search fetch read <job_id> [--cursor CURSOR] [--page-size N]\n  nb-search fetch cancel <job_id>\n  nb-search capabilities\n`;
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) process.exitCode = await runCli(process.argv.slice(2));
