import { createHash } from 'node:crypto';
import { z } from 'zod';
import { NbSearchError } from './errors.ts';
import type { FetchFileScope, FetchInputKind, FetchRepresentation, LaneCost, LaneLatency } from './types.ts';

export const CONFIG_SCHEMA_VERSION = '4' as const;
export function resultTtlSeconds(retentionHours: number): number { return Math.max(1, Math.round(retentionHours * 3600)); }
export interface ProviderInstanceConfig { provider_id: string; enabled: boolean; credential_slot_id?: string; base_url?: string; options: Readonly<Record<string, unknown>> }
export interface CredentialSlotConfig { provider_id: string; env: string }
export interface LaneConfig { provider_instance_id: string; operation_id: string; latency: LaneLatency; cost: LaneCost; evidence_groups?: readonly string[] }
export interface FetchChainConfig { input_kind: FetchInputKind; representation?: FetchRepresentation; pipelines: readonly string[] }
export interface DefaultsConfig { search_lane?: string; fetch_chain?: readonly FetchChainConfig[] }
export interface PresetConfig { lanes: readonly string[] }
export interface FetchQualityConfig { min_content_chars: number; blocked_markers: readonly string[] }
export interface ExecutionConfig { max_provider_calls: number; max_concurrency: number; retry_count: number; search_timeout_ms: number; fetch_timeout_ms: number; max_inline_bytes: number; fetch: { max_source_bytes: number; max_response_bytes: number; max_content_chars: number; max_redirects: number; quality: FetchQualityConfig } }
export type ExecutionConfigPatch = Partial<Omit<ExecutionConfig, 'fetch' | 'search_timeout_ms'>> & { search_timeout_ms?: number | null; fetch?: (Partial<Omit<ExecutionConfig['fetch'], 'quality'>> & { quality?: Partial<FetchQualityConfig> | null }) | null };
export interface CanonicalConfig {
  schema_version: typeof CONFIG_SCHEMA_VERSION; home?: string; jobs_root?: string; retention_hours: number; log_level: 'error' | 'warn' | 'info' | 'debug';
  provider_instances: Readonly<Record<string, ProviderInstanceConfig>>; credential_slots: Readonly<Record<string, CredentialSlotConfig>>;
  lanes: Readonly<Record<string, LaneConfig>>; defaults: DefaultsConfig; presets: Readonly<Record<string, PresetConfig>>; fetch: { file_scopes: readonly FetchFileScope[] }; execution: ExecutionConfig;
}
export type ProviderInstancePatch = Partial<Omit<ProviderInstanceConfig, 'options'>> & { options?: Readonly<Record<string, unknown>> | null };
export interface CanonicalConfigPatch {
  schema_version?: typeof CONFIG_SCHEMA_VERSION | null; home?: string | null; jobs_root?: string | null; retention_hours?: number | null; log_level?: CanonicalConfig['log_level'] | null;
  provider_instances?: Readonly<Record<string, ProviderInstancePatch | null>> | null; credential_slots?: Readonly<Record<string, CredentialSlotConfig | null>> | null;
  lanes?: Readonly<Record<string, LaneConfig | null>> | null; defaults?: { search_lane?: string | null; fetch_chain?: readonly FetchChainConfig[] | null } | null;
  presets?: Readonly<Record<string, PresetConfig | null>> | null; fetch?: { file_scopes?: readonly FetchFileScope[] | null } | null; execution?: ExecutionConfigPatch | null;
}
const providerInstanceSchema = z.object({ provider_id: z.string().trim().min(1).max(128), enabled: z.boolean(), credential_slot_id: z.string().trim().min(1).max(256).optional(), base_url: z.string().url().optional(), options: z.record(z.string(), z.unknown()) }).strict();
const credentialSlotSchema = z.object({ provider_id: z.string().trim().min(1).max(128), env: z.string().regex(/^[A-Za-z_][A-Za-z0-9_]*$/) }).strict();
const laneSchema = z.object({ provider_instance_id: z.string().trim().min(1).max(256), operation_id: z.string().trim().min(1).max(128), latency: z.enum(['fast', 'medium', 'slow']), cost: z.enum(['free', 'cheap', 'expensive']), evidence_groups: z.array(z.string().trim().min(1).max(128)).min(1).max(32).optional() }).strict();
const presetSchema = z.object({ lanes: z.array(z.string().trim().min(1).max(256)).min(1) }).strict().superRefine((value, context) => { if (new Set(value.lanes).size !== value.lanes.length) context.addIssue({ code: 'custom', path: ['lanes'], message: 'preset lanes must be unique' }); });
const fetchChainSchema = z.object({ input_kind: z.enum(['url', 'inline_text', 'inline_bytes', 'file']), representation: z.enum(['markdown', 'text']).optional(), pipelines: z.array(z.string().trim().min(1).max(256)).min(1) }).strict();
const fileScopeSchema = z.object({ id: z.string().trim().min(1).max(256), root: z.string().trim().min(1), media_types: z.array(z.string().trim().min(1).max(256)).min(1).optional() }).strict();
const fetchConfigSchema = z.object({ file_scopes: z.array(fileScopeSchema).max(64) }).strict().superRefine((value, context) => { if (new Set(value.file_scopes.map((item) => item.id)).size !== value.file_scopes.length) context.addIssue({ code: 'custom', path: ['file_scopes'], message: 'file scope ids must be unique' }); });
const qualitySchema = z.object({ min_content_chars: z.number().int().min(0).max(10_000_000), blocked_markers: z.array(z.string().min(1).max(256)).max(64) }).strict();
const fetchExecutionSchema = z.object({ max_source_bytes: z.number().int().min(1).max(64 * 1024 * 1024), max_response_bytes: z.number().int().min(1024).max(64 * 1024 * 1024), max_content_chars: z.number().int().min(256).max(10_000_000), max_redirects: z.number().int().min(0).max(20), quality: qualitySchema }).strict();
const executionSchema = z.object({ max_provider_calls: z.number().int().min(1).max(1024), max_concurrency: z.number().int().min(1).max(128), retry_count: z.number().int().min(0).max(9), search_timeout_ms: z.number().int().min(100).max(3_600_000), fetch_timeout_ms: z.number().int().min(100).max(120_000), max_inline_bytes: z.number().int().min(1024).max(16 * 1024 * 1024), fetch: fetchExecutionSchema }).strict();
const configSchema = z.object({ schema_version: z.literal(CONFIG_SCHEMA_VERSION), home: z.string().trim().min(1).optional(), jobs_root: z.string().trim().min(1).optional(), retention_hours: z.number().positive().max(24 * 3650), log_level: z.enum(['error', 'warn', 'info', 'debug']), provider_instances: z.record(z.string().min(1), providerInstanceSchema), credential_slots: z.record(z.string().min(1), credentialSlotSchema), lanes: z.record(z.string().min(1), laneSchema), defaults: z.object({ search_lane: z.string().min(1).optional(), fetch_chain: z.array(fetchChainSchema).min(1).optional() }).strict(), presets: z.record(z.string().min(1), presetSchema), fetch: fetchConfigSchema, execution: executionSchema }).strict().superRefine((value, context) => {
  for (const [id, instance] of Object.entries(value.provider_instances)) if (instance.credential_slot_id !== undefined) { const slot = value.credential_slots[instance.credential_slot_id]; if (slot === undefined) context.addIssue({ code: 'custom', path: ['provider_instances', id, 'credential_slot_id'], message: 'credential slot is not configured' }); else if (slot.provider_id !== instance.provider_id) context.addIssue({ code: 'custom', path: ['provider_instances', id, 'credential_slot_id'], message: 'credential slot provider does not match the provider instance' }); }
  for (const [id, lane] of Object.entries(value.lanes)) if (value.provider_instances[lane.provider_instance_id] === undefined) context.addIssue({ code: 'custom', path: ['lanes', id, 'provider_instance_id'], message: 'provider instance is not configured' });
  if (value.defaults.search_lane !== undefined && value.lanes[value.defaults.search_lane] === undefined) context.addIssue({ code: 'custom', path: ['defaults', 'search_lane'], message: 'default lane is not configured' });
  for (const [chainIndex, chain] of (value.defaults.fetch_chain ?? []).entries()) for (const [pipelineIndex, pipeline] of chain.pipelines.entries()) if (value.lanes[pipeline] === undefined) context.addIssue({ code: 'custom', path: ['defaults', 'fetch_chain', chainIndex, 'pipelines', pipelineIndex], message: 'default pipeline is not configured' });
});
const patchQualitySchema = qualitySchema.partial().strict();
const patchFetchExecutionSchema = fetchExecutionSchema.partial().extend({ quality: patchQualitySchema.nullable().optional() }).strict();
const patchSchema = z.object({ schema_version: z.literal(CONFIG_SCHEMA_VERSION).nullable().optional(), home: z.string().trim().min(1).nullable().optional(), jobs_root: z.string().trim().min(1).nullable().optional(), retention_hours: z.number().positive().max(24 * 3650).nullable().optional(), log_level: z.enum(['error', 'warn', 'info', 'debug']).nullable().optional(), provider_instances: z.record(z.string().min(1), providerInstanceSchema.partial().extend({ options: z.record(z.string(), z.unknown()).nullable().optional() }).strict().nullable()).nullable().optional(), credential_slots: z.record(z.string().min(1), credentialSlotSchema.nullable()).nullable().optional(), lanes: z.record(z.string().min(1), laneSchema.nullable()).nullable().optional(), defaults: z.object({ search_lane: z.string().min(1).nullable().optional(), fetch_chain: z.array(fetchChainSchema).min(1).nullable().optional() }).strict().nullable().optional(), presets: z.record(z.string().min(1), presetSchema.nullable()).nullable().optional(), fetch: z.object({ file_scopes: z.array(fileScopeSchema).max(64).nullable().optional() }).strict().nullable().optional(), execution: executionSchema.partial().extend({ search_timeout_ms: z.number().int().min(100).max(3_600_000).nullable().optional(), fetch: patchFetchExecutionSchema.nullable().optional() }).strict().nullable().optional() }).strict();
export function parseConfigPatch(value: unknown, source: string): CanonicalConfigPatch { const parsed = patchSchema.safeParse(value); if (!parsed.success) throw configurationError(source, parsed.error.issues); return parsed.data as CanonicalConfigPatch }
export function parseResolvedConfig(value: unknown): CanonicalConfig { const parsed = configSchema.safeParse(value); if (!parsed.success) throw configurationError('resolved configuration', parsed.error.issues); return parsed.data as CanonicalConfig }
export function stableFingerprint(value: unknown): string { return createHash('sha256').update(stableJson(value)).digest('hex') }
export function stableJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`; if (value !== null && typeof value === 'object') { const entries = Object.entries(value as Record<string, unknown>).filter(([, item]) => item !== undefined).sort(([left], [right]) => left.localeCompare(right)); return `{${entries.map(([key, item]) => `${JSON.stringify(key)}:${stableJson(item)}`).join(',')}}`; } return JSON.stringify(value) ?? 'null'; }
function configurationError(source: string, issues: readonly z.core.$ZodIssue[]): NbSearchError { return new NbSearchError('CONFIGURATION_ERROR', `${source} is invalid: ${issues.slice(0, 4).map((issue) => `${issue.path.join('.') || '<root>'}: ${issue.message}`).join('; ')}.`); }
