import type { FetchQualityConfig, LaneConfig, ProviderInstanceConfig } from './config-schema.ts';
import { stableFingerprint } from './config-schema.ts';
import type { ResolvedConfiguration, SecretBinding, WorkerGrant } from './config-sources.ts';
import { NbSearchError } from './errors.ts';
import type { ProviderRegistry } from './provider-registry.ts';
import type { FetchFileScope, FetchPipelineDescriptor, FetchRepresentation, FetchSource, Freshness, JobKind, QueryOperationDescriptor } from './types.ts';

export const EXECUTION_SNAPSHOT_VERSION = '1' as const;
export const ARTIFACT_CONTRACT_VERSION = '1' as const;
export interface QueryJobRequest { queries: string[]; lanes: string[]; freshness?: Freshness; max_results: number; timeout_ms: number; retry_count: number; max_provider_calls: number; max_concurrency: number; result_ttl_seconds: number }
export interface FetchJobRequest { source: FetchSource; selection: 'default' | 'pipeline'; pipelines: string[]; representation: FetchRepresentation; timeout_ms: number; max_content_chars: number; max_source_bytes: number; max_response_bytes: number; max_redirects: number; quality: FetchQualityConfig; retry_count: number; max_provider_calls: number; result_ttl_seconds: number; file_scopes: readonly FetchFileScope[] }
export type JobRequest = QueryJobRequest | FetchJobRequest;
export interface SnapshotCredentialBinding { credential_slot_id: string; provider_id: string; worker_grant: WorkerGrant }
export interface SnapshotSelection { lane_id: string; lane: LaneConfig; provider_instance_id: string; provider_instance: ProviderInstanceConfig; operation: QueryOperationDescriptor | FetchPipelineDescriptor; operation_fingerprint: string; credential_binding?: SnapshotCredentialBinding }
export interface ExecutionSnapshot { snapshot_version: typeof EXECUTION_SNAPSHOT_VERSION; artifact_contract_version: typeof ARTIFACT_CONTRACT_VERSION; kind: JobKind; request: JobRequest; selected: SnapshotSelection[]; snapshot_fingerprint: string }
export function createExecutionSnapshot(request: QueryJobRequest, laneIds: readonly string[], resolved: ResolvedConfiguration, registry: ProviderRegistry): ExecutionSnapshot { return createSnapshot('search', request, laneIds, resolved, registry); }
export function createFetchExecutionSnapshot(request: FetchJobRequest, pipelineIds: readonly string[], resolved: ResolvedConfiguration, registry: ProviderRegistry): ExecutionSnapshot { return createSnapshot('fetch', request, pipelineIds, resolved, registry); }
function createSnapshot(kind: JobKind, request: JobRequest, laneIds: readonly string[], resolved: ResolvedConfiguration, registry: ProviderRegistry): ExecutionSnapshot {
  const selected = laneIds.map((laneId): SnapshotSelection => { const lane = resolved.config.lanes[laneId]; if (lane === undefined) throw new NbSearchError('CONFIGURATION_ERROR', `Lane ${laneId} is missing.`); const instance = resolved.config.provider_instances[lane.provider_instance_id]; if (instance === undefined) throw new NbSearchError('CONFIGURATION_ERROR', `Provider instance ${lane.provider_instance_id} is missing.`); if (!registry.isBuiltIn(instance.provider_id)) throw new NbSearchError('LANE_EXECUTION_UNSUPPORTED', `Lane ${laneId} cannot be rebuilt by the worker.`); const descriptor = registry.requireDescriptor(instance.provider_id); const operation = kind === 'search' ? registry.operation(instance.provider_id, lane.operation_id) : registry.fetchOperation(instance.provider_id, lane.operation_id); const asyncSupported = kind === 'search' ? operation !== undefined && 'built_in_async' in operation && operation.built_in_async : operation !== undefined && 'execution_modes' in operation && operation.execution_modes.includes('async'); if (operation === undefined || !asyncSupported) throw new NbSearchError('LANE_EXECUTION_UNSUPPORTED', `Lane ${laneId} does not support async execution.`); const binding = instance.credential_slot_id === undefined ? undefined : resolved.secret_bindings.get(instance.credential_slot_id); if (binding !== undefined && (binding.provider_id !== instance.provider_id || binding.credential_slot_id !== instance.credential_slot_id)) throw new NbSearchError('CONFIGURATION_ERROR', `Credential binding for provider instance ${lane.provider_instance_id} does not match the provider.`); if (descriptor.activation.credential === 'required' && binding === undefined) throw new NbSearchError('LANE_NOT_CONFIGURED', `Credential grant ${instance.credential_slot_id} is unavailable.`); return { lane_id: laneId, lane: structuredClone(lane), provider_instance_id: lane.provider_instance_id, provider_instance: structuredClone(instance), operation: structuredClone(operation), operation_fingerprint: registry.operationFingerprint(instance.provider_id, lane.operation_id), ...(binding === undefined ? {} : { credential_binding: { credential_slot_id: binding.credential_slot_id, provider_id: binding.provider_id, worker_grant: structuredClone(binding.worker_grant) } }) }; });
  const base = { snapshot_version: EXECUTION_SNAPSHOT_VERSION, artifact_contract_version: ARTIFACT_CONTRACT_VERSION, kind, request: structuredClone(request), selected }; return deepFreeze({ ...base, snapshot_fingerprint: stableFingerprint(base) });
}
export function validateExecutionSnapshot(value: unknown): ExecutionSnapshot { if (!isRecord(value) || value['snapshot_version'] !== EXECUTION_SNAPSHOT_VERSION || value['artifact_contract_version'] !== ARTIFACT_CONTRACT_VERSION || (value['kind'] !== 'search' && value['kind'] !== 'fetch') || !Array.isArray(value['selected']) || !isRecord(value['request']) || !Number.isSafeInteger(value['request']['result_ttl_seconds']) || Number(value['request']['result_ttl_seconds']) < 1 || typeof value['snapshot_fingerprint'] !== 'string') throw new NbSearchError('JOB_STORE_ERROR', 'Execution snapshot is invalid.'); const candidate = value as unknown as ExecutionSnapshot; const { snapshot_fingerprint: fingerprint, ...base } = candidate; if (stableFingerprint(base) !== fingerprint || candidate.selected.length < 1) throw new NbSearchError('JOB_STORE_ERROR', 'Execution snapshot fingerprint does not match.'); if (candidate.selected.some((selected) => !snapshotCredentialMatches(selected))) throw new NbSearchError('JOB_STORE_ERROR', 'Execution snapshot credential binding does not match the provider.'); return deepFreeze(structuredClone(candidate)); }
export function assertSnapshotOperations(snapshot: ExecutionSnapshot, registry: ProviderRegistry): void { for (const selected of snapshot.selected) { if (!snapshotCredentialMatches(selected)) throw new NbSearchError('CONFIGURATION_ERROR', `Worker credential binding ${selected.lane_id} does not match the execution snapshot.`); if (!registry.isBuiltIn(selected.provider_instance.provider_id) || registry.operationFingerprint(selected.provider_instance.provider_id, selected.lane.operation_id) !== selected.operation_fingerprint) throw new NbSearchError('CONFIGURATION_ERROR', `Worker operation ${selected.lane_id} does not match the execution snapshot.`); } }
export function resolveSnapshotBindings(snapshot: ExecutionSnapshot, env: NodeJS.ProcessEnv, opaque: Readonly<Record<string, string>> = {}): ReadonlyMap<string, SecretBinding> { const bindings = new Map<string, SecretBinding>(); for (const selected of snapshot.selected) { if (!snapshotCredentialMatches(selected)) throw new NbSearchError('CONFIGURATION_ERROR', `Worker credential binding ${selected.lane_id} does not match the provider.`); const binding = selected.credential_binding; if (binding === undefined || bindings.has(binding.credential_slot_id)) continue; const value = binding.worker_grant.kind === 'environment' ? nonempty(env[binding.worker_grant.name]) : nonempty(opaque[binding.worker_grant.id]); if (value === undefined) throw new NbSearchError('CONFIGURATION_ERROR', `Worker credential grant ${binding.credential_slot_id} is unavailable.`); bindings.set(binding.credential_slot_id, { credential_slot_id: binding.credential_slot_id, provider_id: binding.provider_id, value, worker_grant: binding.worker_grant }); } return bindings; }
function snapshotCredentialMatches(selected: SnapshotSelection): boolean { const binding = selected.credential_binding; return binding === undefined || binding.provider_id === selected.provider_instance.provider_id && binding.credential_slot_id === selected.provider_instance.credential_slot_id }
function nonempty(value: string | undefined): string | undefined { const item = value?.trim(); return item === '' ? undefined : item }
function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value) }
function deepFreeze<T>(value: T): T { if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); for (const item of Object.values(value as Record<string, unknown>)) deepFreeze(item); } return value; }
