import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { constants } from 'node:fs';
import { access, appendFile, lstat, mkdir, open, readFile, readdir, rename, rm } from 'node:fs/promises';
import { basename, dirname, relative, resolve, sep } from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { stableJson } from './config-schema.ts';
import { validateExecutionSnapshot, type ExecutionSnapshot, type QueryJobRequest } from './execution-snapshot.ts';
import { NbSearchError, invalidInput } from './errors.ts';
import type { ArtifactChunk, ArtifactRef, JobState, OutputChannel, PublicError } from './types.ts';
import { SCHEMA_VERSION } from './types.ts';

export const UUID_V4_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
export const RESULT_CHUNK_BYTES = 12 * 1024;
const TERMINAL = new Set<JobState>(['succeeded', 'failed', 'cancelled']);
const TRANSITIONS: Readonly<Record<JobState, readonly JobState[]>> = { queued: ['running', 'failed', 'cancelled'], running: ['succeeded', 'failed', 'cancelled'], succeeded: [], failed: [], cancelled: [] };
export interface JobRecord { schema_version: typeof SCHEMA_VERSION; job_id: string; state: JobState; request: QueryJobRequest; channel: OutputChannel; schema_id: string; request_hash: string; idempotency_hash: string; created_at: string; updated_at: string; started_at?: string; completed_at?: string; cancel_requested_at?: string; lease?: { owner_token: string; heartbeat_at: string }; artifact?: ArtifactRef; error?: PublicError }
export interface CreateJobResult { job: JobRecord; reused: boolean }
export interface JobStoreOptions { rename_path?: typeof rename; sleep?: (ms: number) => Promise<void> }
interface ResultChunkManifest { index: number; offset: number; byte_length: number; file: string }
interface ResultManifest { manifest_version: '1'; artifact: ArtifactRef; chunks: ResultChunkManifest[] }
export class JobStore {
  private readonly renamePath: typeof rename; private readonly sleep: (ms: number) => Promise<void>;
  constructor(readonly root: string, private readonly now: () => Date = () => new Date(), options: JobStoreOptions = {}) { this.renamePath = options.rename_path ?? rename; this.sleep = options.sleep ?? (async (ms) => { await delay(ms); }); }
  async initialize(): Promise<void> { await mkdir(this.root, { recursive: true }); const info = await lstat(this.root); if (info.isSymbolicLink() || !info.isDirectory()) throw storeError('The jobs root must be a real directory.'); }
  async createOrReuse(request: QueryJobRequest, channel: OutputChannel, schemaId: string, idempotencyKey: string, snapshot: ExecutionSnapshot): Promise<CreateJobResult> { await this.initialize(); const requestHash = hash(stableJson({ request, channel, schema_id: schemaId, snapshot_fingerprint: snapshot.snapshot_fingerprint })); const idempotencyHash = hash(idempotencyKey); return await this.withLock(resolve(this.root, '.idempotency-lock'), async () => { for (const job of await this.listRecords()) if (job.idempotency_hash === idempotencyHash) { if (job.request_hash !== requestHash) throw new NbSearchError('JOB_CONFLICT', 'The idempotency key is already bound to a different request.'); return { job, reused: true }; } const jobId = randomUUID(); const dir = this.jobDir(jobId); await mkdir(dir, { recursive: false }); try { const at = this.now().toISOString(); const job: JobRecord = { schema_version: SCHEMA_VERSION, job_id: jobId, state: 'queued', request: structuredClone(request), channel, schema_id: schemaId, request_hash: requestHash, idempotency_hash: idempotencyHash, created_at: at, updated_at: at }; await this.atomicWrite(resolve(dir, 'execution.json'), JSON.stringify(snapshot)); await this.atomicWrite(resolve(dir, 'job.json'), JSON.stringify(job)); await this.appendEvent(jobId, { type: 'created', at }); return { job, reused: false }; } catch (error) { await rm(dir, { recursive: true, force: true }); throw error; } }); }
  async read(jobId: string): Promise<JobRecord> { const dir = await this.safeJobDir(jobId); try { const job = JSON.parse(await readFile(resolve(dir, 'job.json'), 'utf8')) as JobRecord; if (job.job_id !== jobId) throw storeError('Job identity mismatch.'); return job; } catch (error) { if (error instanceof NbSearchError) throw error; throw new NbSearchError('JOB_NOT_FOUND', 'Query job was not found.', false, undefined, { cause: error }); } }
  async readExecutionSnapshot(jobId: string): Promise<ExecutionSnapshot> { const dir = await this.safeJobDir(jobId); try { return validateExecutionSnapshot(JSON.parse(await readFile(resolve(dir, 'execution.json'), 'utf8')) as unknown); } catch (error) { if (error instanceof NbSearchError) throw error; throw storeError('Execution snapshot could not be read.', error); } }
  async mutate(jobId: string, update: (job: JobRecord) => JobRecord): Promise<JobRecord> { const dir = await this.safeJobDir(jobId); return await this.withLock(resolve(dir, '.lock'), async () => { const current = await this.read(jobId); const next = update(structuredClone(current)); if (next.job_id !== jobId) throw storeError('Job identity is immutable.'); await this.atomicWrite(resolve(dir, 'job.json'), JSON.stringify(next)); if (current.state !== next.state) await this.appendEvent(jobId, { type: 'state', from: current.state, state: next.state, at: next.updated_at }); return next; }); }
  async transition(jobId: string, state: JobState, patch: Partial<JobRecord> = {}): Promise<JobRecord> { return await this.mutate(jobId, (job) => { if (!TRANSITIONS[job.state].includes(state)) { if (job.state === state) return job; throw storeError(`Invalid job transition: ${job.state} -> ${state}.`); } const at = this.now().toISOString(); return { ...job, ...patch, state, updated_at: at, ...(TERMINAL.has(state) ? { completed_at: at } : {}) }; }); }
  async claim(jobId: string, ownerToken: string): Promise<JobRecord> { const at = this.now().toISOString(); return await this.mutate(jobId, (job) => { if (job.state !== 'queued') throw new NbSearchError('JOB_CONFLICT', 'Query job has already been claimed.'); return { ...job, state: 'running', started_at: at, updated_at: at, lease: { owner_token: ownerToken, heartbeat_at: at } }; }); }
  async heartbeat(jobId: string, ownerToken: string): Promise<JobRecord> { return await this.mutate(jobId, (job) => { if (job.state !== 'running' || job.lease?.owner_token !== ownerToken) throw storeError('Worker lease ownership does not match.'); const at = this.now().toISOString(); return { ...job, updated_at: at, lease: { owner_token: ownerToken, heartbeat_at: at } }; }); }
  async requestCancel(jobId: string): Promise<{ job: JobRecord; accepted: boolean }> { const dir = await this.safeJobDir(jobId); return await this.withLock(resolve(dir, '.lock'), async () => { const current = await this.read(jobId); if (TERMINAL.has(current.state)) return { job: current, accepted: false }; const at = this.now().toISOString(); await this.atomicWrite(resolve(dir, 'cancel.json'), JSON.stringify({ requested_at: at })); const next = current.state === 'queued' ? { ...current, state: 'cancelled' as const, cancel_requested_at: at, updated_at: at, completed_at: at } : { ...current, cancel_requested_at: at, updated_at: at }; await this.atomicWrite(resolve(dir, 'job.json'), JSON.stringify(next)); return { job: next, accepted: true }; }); }
  async cancelRequested(jobId: string): Promise<boolean> { await this.safeJobDir(jobId); try { await access(resolve(this.jobDir(jobId), 'cancel.json'), constants.F_OK); return true; } catch { return false; } }
  async writeResult(jobId: string, value: unknown, ttlSeconds: number): Promise<ArtifactRef> { const dir = await this.safeJobDir(jobId); const job = await this.read(jobId); if (job.artifact !== undefined) throw storeError('Result artifact is immutable.'); const bytes = Buffer.from(JSON.stringify(value), 'utf8'); const artifact: ArtifactRef = { media_type: 'application/json', byte_length: bytes.length, sha256: hashBytes(bytes), expires_at: new Date(this.now().getTime() + ttlSeconds * 1000).toISOString() }; const temporary = resolve(dir, `.result.${randomBytes(8).toString('hex')}.tmp`); const published = resolve(dir, 'result'); await mkdir(temporary); const chunks: ResultChunkManifest[] = []; try { for (let offset = 0, index = 0; offset < bytes.length; offset += RESULT_CHUNK_BYTES, index += 1) { const data = bytes.subarray(offset, Math.min(bytes.length, offset + RESULT_CHUNK_BYTES)); const file = `${String(index).padStart(6, '0')}.bin`; await this.atomicWrite(resolve(temporary, file), data); chunks.push({ index, offset, byte_length: data.length, file }); } const manifest: ResultManifest = { manifest_version: '1', artifact, chunks }; await this.atomicWrite(resolve(temporary, 'manifest.json'), JSON.stringify(manifest)); await this.renameWithRetry(temporary, published); await this.mutate(jobId, (current) => ({ ...current, artifact, updated_at: this.now().toISOString() })); return artifact; } catch (error) { await rm(temporary, { recursive: true, force: true }); throw error instanceof NbSearchError ? error : storeError('Atomic result publication failed.', error); } }
  async readResult(jobId: string, offset: number, pageSize: number): Promise<{ artifact: ArtifactRef; chunks: ArtifactChunk[]; next_offset?: number }> { const job = await this.read(jobId); if (job.artifact === undefined) throw storeError('Result artifact is unavailable.'); if (this.now().getTime() >= Date.parse(job.artifact.expires_at)) throw new NbSearchError('JOB_NOT_FOUND', 'Query result artifact has expired.'); const dir = resolve(await this.safeJobDir(jobId), 'result'); try { const manifest = validateResultManifest(JSON.parse(await readFile(resolve(dir, 'manifest.json'), 'utf8')) as unknown, job.artifact); const data: Buffer[] = []; const digest = createHash('sha256'); for (const chunk of manifest.chunks) { const bytes = await readFile(resolve(dir, chunk.file)); if (bytes.length !== chunk.byte_length) throw storeError('Result chunk length does not match the manifest.'); digest.update(bytes); data.push(bytes); } if (digest.digest('hex') !== manifest.artifact.sha256) throw storeError('Result artifact hash does not match the manifest.'); const start = manifest.chunks.findIndex((chunk) => chunk.offset === offset); if (start < 0) throw invalidInput('Cursor offset is not a result chunk boundary.'); const selected = manifest.chunks.slice(start, start + pageSize); const chunks = selected.map((item): ArtifactChunk => ({ index: item.index, offset: item.offset, byte_length: item.byte_length, data_base64: data[item.index]!.toString('base64') })); const next = start + selected.length; return { artifact: job.artifact, chunks, ...(next < manifest.chunks.length ? { next_offset: manifest.chunks[next]!.offset } : {}) }; } catch (error) { if (error instanceof NbSearchError) throw error; throw storeError('Result artifact could not be read.', error); } }
  async reconcileStale(jobId: string, staleMs = 30_000): Promise<JobRecord> { const job = await this.read(jobId); if (job.state !== 'running') return job; if (this.now().getTime() - Date.parse(job.lease?.heartbeat_at ?? job.updated_at) <= staleMs) return job; if (await this.cancelRequested(jobId)) return await this.transition(jobId, 'cancelled', { lease: undefined }); return await this.transition(jobId, 'failed', { lease: undefined, error: new NbSearchError('WORKER_LOST', 'The query worker lease expired.', true).toPublic() }); }
  async listRecords(): Promise<JobRecord[]> { await this.initialize(); const records: JobRecord[] = []; for (const entry of await readdir(this.root, { withFileTypes: true })) if (entry.isDirectory() && UUID_V4_PATTERN.test(entry.name)) try { records.push(await this.read(entry.name)); } catch {} return records.sort((a, b) => b.created_at.localeCompare(a.created_at)); }
  async prune(): Promise<number> { let removed = 0; for (const job of await this.listRecords()) { if (!TERMINAL.has(job.state)) continue; const expiresAt = job.state === 'succeeded' ? Date.parse(job.artifact!.expires_at) : Date.parse(job.completed_at!) + job.request.result_ttl_seconds * 1000; if (this.now().getTime() < expiresAt) continue; const dir = await this.safeJobDir(job.job_id); if ((await this.read(job.job_id)).job_id !== basename(dir)) continue; await rm(dir, { recursive: true, force: false }); removed += 1; } return removed; }
  private jobDir(jobId: string): string { if (!UUID_V4_PATTERN.test(jobId)) throw invalidInput('job_id must be a lowercase UUID v4.'); const candidate = resolve(this.root, jobId); const rel = relative(resolve(this.root), candidate); if (rel.startsWith(`..${sep}`) || rel === '..' || rel === '' || rel.includes(sep)) throw invalidInput('job_id resolves outside jobs root.'); return candidate; }
  private async safeJobDir(jobId: string): Promise<string> { await this.initialize(); const dir = this.jobDir(jobId); try { const info = await lstat(dir); if (info.isSymbolicLink() || !info.isDirectory()) throw new Error(); return dir; } catch (error) { throw new NbSearchError('JOB_NOT_FOUND', 'Query job was not found.', false, undefined, { cause: error }); } }
  private async renameWithRetry(from: string, to: string): Promise<void> { let last: unknown; for (let attempt = 0; attempt < 5; attempt += 1) try { await this.renamePath(from, to); return; } catch (error) { last = error; const code = (error as NodeJS.ErrnoException).code; if (attempt === 4 || (code !== 'EPERM' && code !== 'EACCES' && code !== 'EBUSY')) break; await this.sleep(10 * (attempt + 1)); } throw last; }
  private async atomicWrite(path: string, value: string | Uint8Array): Promise<void> { const temporary = resolve(dirname(path), `.${basename(path)}.${randomBytes(8).toString('hex')}.tmp`); const handle = await open(temporary, 'wx', 0o600); try { await handle.writeFile(value); await handle.sync(); } finally { await handle.close(); } try { await this.renameWithRetry(temporary, path); } catch (error) { await rm(temporary, { force: true }); throw storeError('Atomic job-store write failed.', error); } }
  private async appendEvent(jobId: string, event: unknown): Promise<void> { await appendFile(resolve(this.jobDir(jobId), 'events.ndjson'), `${JSON.stringify(event)}\n`, { encoding: 'utf8', mode: 0o600 }); }
  private async withLock<T>(path: string, operation: () => Promise<T>): Promise<T> { const token = randomBytes(16).toString('hex'); let acquired = false; for (let attempt = 0; attempt < 100; attempt += 1) try { await mkdir(path); acquired = true; await this.atomicWrite(resolve(path, 'owner'), token); break; } catch (error) { if (acquired) throw error; if (attempt === 99) throw storeError('Timed out waiting for job-store lock.', error); await this.sleep(10); } try { return await operation(); } finally { try { if ((await readFile(resolve(path, 'owner'), 'utf8')) === token) await rm(path, { recursive: true, force: true }); } catch {} } }
}
function validateResultManifest(value: unknown, expected: ArtifactRef): ResultManifest {
  if (!isRecord(value) || !exactKeys(value, ['artifact', 'chunks', 'manifest_version']) || value['manifest_version'] !== '1' || !isRecord(value['artifact']) || !Array.isArray(value['chunks'])) throw storeError('Result manifest is invalid.');
  const artifact = value['artifact'];
  if (!exactKeys(artifact, ['byte_length', 'expires_at', 'media_type', 'sha256']) || artifact['media_type'] !== 'application/json' || !Number.isSafeInteger(artifact['byte_length']) || Number(artifact['byte_length']) < 1 || typeof artifact['sha256'] !== 'string' || !/^[0-9a-f]{64}$/.test(artifact['sha256']) || typeof artifact['expires_at'] !== 'string' || !Number.isFinite(Date.parse(artifact['expires_at']))) throw storeError('Result manifest artifact metadata is invalid.');
  if (artifact['media_type'] !== expected.media_type || artifact['byte_length'] !== expected.byte_length || artifact['sha256'] !== expected.sha256 || artifact['expires_at'] !== expected.expires_at) throw storeError('Result manifest identity does not match the job artifact.');
  let offset = 0; const chunks: ResultChunkManifest[] = [];
  for (let index = 0; index < value['chunks'].length; index += 1) { const item = value['chunks'][index]; const file = `${String(index).padStart(6, '0')}.bin`; if (!isRecord(item) || !exactKeys(item, ['byte_length', 'file', 'index', 'offset']) || item['index'] !== index || item['offset'] !== offset || !Number.isSafeInteger(item['byte_length']) || Number(item['byte_length']) < 1 || Number(item['byte_length']) > RESULT_CHUNK_BYTES || item['file'] !== file) throw storeError('Result manifest chunk layout is invalid.'); const byteLength = Number(item['byte_length']); chunks.push({ index, offset, byte_length: byteLength, file }); offset += byteLength; }
  if (chunks.length < 1 || offset !== expected.byte_length) throw storeError('Result manifest byte length does not match the artifact.');
  return { manifest_version: '1', artifact: expected, chunks };
}
function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function exactKeys(value: Record<string, unknown>, keys: readonly string[]): boolean { const actual = Object.keys(value); return actual.length === keys.length && keys.every((key) => Object.prototype.hasOwnProperty.call(value, key)); }
function hash(value: string): string { return createHash('sha256').update(value).digest('hex') }
function hashBytes(value: Uint8Array): string { return createHash('sha256').update(value).digest('hex') }
function storeError(message: string, cause?: unknown): NbSearchError { return new NbSearchError('JOB_STORE_ERROR', message, false, undefined, cause === undefined ? undefined : { cause }) }
