import { setTimeout as delay } from 'node:timers/promises';
import type { AppConfiguration, LaneBinding } from './config.ts';
import type { SearchRunInput } from './contracts.ts';
import { NbSearchError, publicError } from './errors.ts';
import { normalizeUrl } from './url.ts';
import type { LaneAttempt, PublicError, QueryExecution, ResultProvenance, SearchResult, SearchSelection } from './types.ts';

export interface ResolvedSearchSelection { selection: SearchSelection; lanes: LaneBinding[]; channel: 'results' | 'typed'; schema_id: string }
export function resolveSearchSelection(input: SearchRunInput, app: AppConfiguration, execution: QueryExecution): ResolvedSearchSelection {
  let selection: SearchSelection;
  if (input.lane !== undefined) selection = { source: 'lane', lanes: [input.lane], requested: input.lane };
  else if (input.lanes !== undefined) { if (new Set(input.lanes).size !== input.lanes.length) throw new NbSearchError('INVALID_INPUT', 'lanes must contain unique IDs.'); selection = { source: 'lanes', lanes: [...input.lanes], requested: [...input.lanes] }; }
  else if (input.preset !== undefined) { const preset = app.resolved.config.presets[input.preset]; if (preset === undefined) throw new NbSearchError('PRESET_NOT_FOUND', `Preset ${input.preset} is not configured.`); selection = { source: 'preset', lanes: [...preset.lanes], requested: input.preset }; }
  else { const lane = app.resolved.config.defaults.search_lane; if (lane === undefined) throw new NbSearchError('DEFAULT_NOT_CONFIGURED', 'Default search lane is not configured.'); selection = { source: 'default', lanes: [lane] }; }
  const lanes = selection.lanes.map((id) => { const lane = app.lanes[id]; if (lane?.query_operation === undefined) throw new NbSearchError('LANE_NOT_REGISTERED', `Query lane ${id} is not registered.`); if (lane.availability !== 'ready') throw new NbSearchError('LANE_NOT_CONFIGURED', `Query lane ${id} is unavailable.`); if (!lane.execution_modes.includes(execution)) throw new NbSearchError('LANE_EXECUTION_UNSUPPORTED', `Query lane ${id} does not support ${execution}.`); return lane; });
  const channels = new Set(lanes.map((lane) => lane.query_operation!.output.channel)); if (channels.size !== 1) throw new NbSearchError('MIXED_OUTPUT_UNSUPPORTED', 'Mixed query output channels are not supported.'); const channel = lanes[0]!.query_operation!.output.channel;
  if (channel === 'typed' && lanes.length !== 1) throw new NbSearchError('MIXED_OUTPUT_UNSUPPORTED', 'Typed query operations require a single lane.');
  if ((input.lanes !== undefined || input.preset !== undefined) && channel !== 'results') throw new NbSearchError('MIXED_OUTPUT_UNSUPPORTED', 'lanes and preset support results operations only.');
  return { selection, lanes, channel, schema_id: lanes[0]!.query_operation!.output.schema_id };
}
export interface ResolvedFetchSelection { source: 'default' | 'lane'; lanes: LaneBinding[]; requested?: string }
export function resolveFetchLanes(laneId: string | undefined, app: AppConfiguration): ResolvedFetchSelection {
  if (laneId !== undefined) { const lane = app.lanes[laneId]; if (lane?.fetch_operation === undefined) throw new NbSearchError('LANE_NOT_REGISTERED', `Fetch lane ${laneId} is not registered.`); if (lane.availability !== 'ready') throw new NbSearchError('LANE_NOT_CONFIGURED', `Fetch lane ${laneId} is unavailable.`); return { source: 'lane', lanes: [lane], requested: laneId }; }
  const chain = app.resolved.config.defaults.fetch_chain; if (chain === undefined) throw new NbSearchError('FETCH_DEFAULT_NOT_CONFIGURED', 'Default fetch chain is not configured.'); return { source: 'default', lanes: chain.map((id) => { const lane = app.lanes[id]; if (lane?.fetch_operation === undefined) throw new NbSearchError('LANE_NOT_REGISTERED', `Fetch lane ${id} is not registered.`); return lane; }) };
}
export function assertAttemptBudget(unitCount: number, retryCount: number, maxProviderCalls: number): void { if (unitCount * (retryCount + 1) > maxProviderCalls) throw new NbSearchError('BUDGET_EXCEEDED', 'The execution plan exceeds the provider attempt limit.'); }
export interface ExecutionUnit<T> { lane: string; provider_instance_id: string; run(signal: AbortSignal): Promise<T> }
export interface UnitResult<T> { lane: string; provider_instance_id: string; value?: T; error?: PublicError; state: 'succeeded' | 'failed' | 'timeout' | 'cancelled'; duration_ms: number; attempts: LaneAttempt[] }
export interface SharedAttemptBudget { used: number }
export interface ExecuteUnitsOptions { timeout_ms: number; max_concurrency: number; retry_count: number; max_provider_calls: number; signal?: AbortSignal; now?: () => number; sleep?: (ms: number, signal: AbortSignal) => Promise<void>; deadline_at?: number; attempt_budget?: SharedAttemptBudget }
export async function executeUnits<T>(units: readonly ExecutionUnit<T>[], options: ExecuteUnitsOptions): Promise<UnitResult<T>[]> {
  if (options.attempt_budget === undefined) assertAttemptBudget(units.length, options.retry_count, options.max_provider_calls); const now = options.now ?? (() => performance.now()); const sleep = options.sleep ?? (async (ms, signal) => { await delay(ms, undefined, { signal }); }); const deadlineAt = options.deadline_at ?? now() + options.timeout_ms; const deadline = new AbortController(); const abortDeadline = (): void => deadline.abort(new NbSearchError('DEADLINE_EXCEEDED', 'Execution deadline was exceeded.', true)); if (now() >= deadlineAt) abortDeadline(); const timer = deadline.signal.aborted ? undefined : setTimeout(abortDeadline, Math.max(0, deadlineAt - now())); const signal = options.signal === undefined ? deadline.signal : AbortSignal.any([options.signal, deadline.signal]); const results = new Array<UnitResult<T>>(units.length); let cursor = 0; const budget = options.attempt_budget ?? { used: 0 };
  const worker = async (): Promise<void> => { for (;;) { const index = cursor; cursor += 1; const unit = units[index]; if (unit === undefined) return; const started = now(); const attempts: LaneAttempt[] = []; let final: UnitResult<T> | undefined;
    for (let attempt = 1; attempt <= options.retry_count + 1; attempt += 1) {
      if (!deadline.signal.aborted && now() >= deadlineAt) abortDeadline();
      if (signal.aborted) { const terminal = classifyAbort(options.signal, deadline.signal)!; final = { lane: unit.lane, provider_instance_id: unit.provider_instance_id, state: terminal.state, duration_ms: Math.max(0, Math.round(now() - started)), error: terminal.error, attempts }; break; }
      if (budget.used >= options.max_provider_calls) { const error = new NbSearchError('BUDGET_EXCEEDED', 'The provider attempt limit was reached.').toPublic(); final = { lane: unit.lane, provider_instance_id: unit.provider_instance_id, state: 'failed', duration_ms: Math.max(0, Math.round(now() - started)), error, attempts }; break; }
      budget.used += 1; const attemptStarted = now();
      try { const value = await raceAbort(unit.run(signal), signal); attempts.push({ lane: unit.lane, provider_instance_id: unit.provider_instance_id, attempt, state: 'succeeded', duration_ms: elapsed(attemptStarted, now()) }); final = { lane: unit.lane, provider_instance_id: unit.provider_instance_id, state: 'succeeded', duration_ms: elapsed(started, now()), value, attempts }; break; }
      catch (error) { const terminal = classifyAbort(options.signal, deadline.signal); const safe = terminal?.error ?? publicError(error, 'Provider execution failed.'); const state = terminal?.state ?? 'failed' as const; attempts.push({ lane: unit.lane, provider_instance_id: unit.provider_instance_id, attempt, state, duration_ms: elapsed(attemptStarted, now()), error: safe }); if (terminal !== undefined || attempt > options.retry_count || !safe.retryable) { final = { lane: unit.lane, provider_instance_id: unit.provider_instance_id, state, duration_ms: elapsed(started, now()), error: safe, attempts }; break; }
        try { await sleep(Math.min(2_000, 100 * (2 ** (attempt - 1))), signal); } catch (backoffError) { const backoff = classifyAbort(options.signal, deadline.signal); if (backoff === undefined) throw backoffError; const last = attempts.at(-1)!; last.state = backoff.state; last.error = backoff.error; last.duration_ms = elapsed(attemptStarted, now()); final = { lane: unit.lane, provider_instance_id: unit.provider_instance_id, state: backoff.state, duration_ms: elapsed(started, now()), error: backoff.error, attempts }; break; }
      }
    }
    results[index] = final!;
  } };
  try { await Promise.all(Array.from({ length: Math.min(options.max_concurrency, units.length) }, worker)); } finally { if (timer !== undefined) clearTimeout(timer); } return results;
}
function classifyAbort(externalSignal: AbortSignal | undefined, deadlineSignal: AbortSignal): { state: 'cancelled' | 'timeout' | 'failed'; error: PublicError } | undefined { if (externalSignal?.aborted === true) { const reason = externalSignal.reason; if (reason instanceof NbSearchError && reason.code !== 'CANCELLED') return { state: 'failed', error: reason.toPublic() }; return { state: 'cancelled', error: new NbSearchError('CANCELLED', 'Execution was cancelled.').toPublic() }; } if (deadlineSignal.aborted) return { state: 'timeout', error: new NbSearchError('DEADLINE_EXCEEDED', 'Execution deadline was exceeded.', true).toPublic() }; return undefined; }
async function raceAbort<T>(promise: Promise<T>, signal: AbortSignal): Promise<T> { if (signal.aborted) throw signal.reason; return await new Promise<T>((resolve, reject) => { const abort = (): void => reject(signal.reason); signal.addEventListener('abort', abort, { once: true }); promise.then(resolve, reject).finally(() => signal.removeEventListener('abort', abort)).catch(() => undefined); }); }
function elapsed(start: number, end: number): number { return Math.max(0, Math.round(end - start)); }

export interface ResultList { lane: LaneBinding; query_index: number; rows: readonly import('./types.ts').ProviderResult[] }
export function mergeResultLists(lists: readonly ResultList[], limit: number): { results: SearchResult[]; input_rows: number; canonical_dedup: number; independent_evidence_groups: number } {
  const single = lists.length === 1; const merged = new Map<string, SearchResult & { first_position: number; score_total: number }>(); let inputRows = 0; let validRows = 0;
  lists.forEach((list, listIndex) => { const within = new Map<string, { row: import('./types.ts').ProviderResult; rank: number; groups: string[]; provenance: ResultProvenance[] }>(); list.rows.forEach((row, rank) => { inputRows += 1; const canonical = normalizeUrl(row.url); if (canonical === undefined) return; validRows += 1; const groups = evidenceGroups(row, list.lane); const provenance: ResultProvenance = { lane: list.lane.id, provider_instance_id: list.lane.config.provider_instance_id, query_index: list.query_index, rank, original_url: row.url, evidence_groups: groups, ...(row.upstream_attribution === undefined ? {} : { upstream: row.upstream_attribution }) }; const existing = within.get(canonical); if (existing !== undefined) { existing.provenance.push(provenance); existing.groups = [...new Set([...existing.groups, ...groups])].sort(); if ((existing.row.snippet ?? '') === '' && row.snippet !== undefined) existing.row = { ...existing.row, snippet: row.snippet }; return; } within.set(canonical, { row, rank, groups, provenance: [provenance] }); });
    for (const [canonical, item] of within) { const score = single ? 0 : 1 / (60 + item.rank + 1); const position = listIndex * 1_000_000 + item.rank; const existing = merged.get(canonical); if (existing !== undefined) { existing.score_total += score; existing.provenance.push(...item.provenance); existing.evidence_groups = [...new Set([...existing.evidence_groups, ...item.groups])].sort(); if (existing.snippet === '' && item.row.snippet !== undefined) existing.snippet = clean(item.row.snippet); continue; } merged.set(canonical, { title: clean(item.row.title), url: canonical, snippet: clean(item.row.snippet ?? ''), ...(item.row.published_at === undefined ? {} : { published_at: item.row.published_at }), ...(item.row.site_name === undefined ? {} : { site_name: item.row.site_name }), evidence_groups: item.groups, provenance: item.provenance, first_position: position, score_total: score }); }
  });
  const values = [...merged.values()]; if (!single) values.sort((a, b) => b.score_total - a.score_total || a.first_position - b.first_position || a.url.localeCompare(b.url)); const results = values.slice(0, limit).map(({ first_position: _position, score_total, ...item }) => ({ ...item, ...(single ? {} : { rrf_score: score_total }) })); return { results, input_rows: inputRows, canonical_dedup: validRows - merged.size, independent_evidence_groups: new Set(results.flatMap((item) => item.evidence_groups).filter((group) => group !== 'unknown')).size };
}
function evidenceGroups(row: import('./types.ts').ProviderResult, lane: LaneBinding): string[] { const upstream = row.upstream_attribution?.map((item) => item.provider) ?? []; if (upstream.length > 0) return [...new Set(upstream)].sort(); if (lane.provider_id === 'search-gateway') return ['unknown']; if ((lane.config.evidence_groups?.length ?? 0) > 0) return [...new Set(lane.config.evidence_groups)].sort(); return [lane.config.provider_instance_id]; }
function clean(value: string): string { return value.replace(/\s+/g, ' ').trim(); }
