import type { ProviderInstanceConfig } from './config-schema.ts';
import { stableFingerprint } from './config-schema.ts';
import type { SecretBinding } from './config-sources.ts';
import { BrowserRenderProvider, playwrightBrowserRenderIo, type BrowserRenderIo } from './browser-render.ts';
import { NbSearchError } from './errors.ts';
import { ExaContentsFetchProvider, FirecrawlScrapeFetchProvider, JinaReaderFetchProvider, TavilyExtractFetchProvider, WaybackFetchProvider } from './fetch-providers.ts';
import { DirectFetchProvider, type DirectFetchIo } from './fetch-security.ts';
import { LocalFetchProvider } from './fetch-sources.ts';
import { BraveSearchProvider } from './providers/brave.ts';
import { Context7DocsProvider } from './providers/context7.ts';
import { FirecrawlSearchProvider } from './providers/firecrawl-search.ts';
import { GitHubRepositoriesProvider } from './providers/github.ts';
import { GrokResponsesProvider, resolveGrokResponsesUrl } from './providers/grok-responses.ts';
import { OpenAiCompatibleFetchProvider, OpenAiCompatibleSynthesisProvider, validateOpenAiCompatibleBaseUrl, validateOpenAiCompatibleFallbackModels, validateOpenAiCompatibleModel } from './providers/openai-compatible.ts';
import { ParallelSearchProvider } from './providers/parallel.ts';
import { SearxngSearchProvider, validateSearxngBaseUrl } from './providers/searxng.ts';
import { ZhipuSearchProvider } from './providers/zhipu.ts';
import { ExaProvider, ExaResearchLightProvider, GrokMultiAgentProvider, TavilyAnswerProvider, TavilyProvider, validateGmaEffort, validateGrokBaseUrl, validateGrokModel, validateProviderBaseUrl, validateSearchPath } from './providers.ts';
import type { HttpTransport } from './transport.ts';
import type { FetchOperationDescriptor, FetchProvider, JsonValue, ProviderId, QueryOperationDescriptor, QueryProvider, QueryProviderValue } from './types.ts';

export const REGISTRY_SCHEMA_VERSION = '1' as const;
export interface ProviderDescriptor { provider_id: ProviderId; adapter_version: string; query_operations: readonly QueryOperationDescriptor[]; fetch_operations: readonly FetchOperationDescriptor[]; activation: { credential: 'required' | 'none'; endpoint: 'required' | 'optional' | 'none' }; option_keys: readonly string[] }
export interface ProviderFactoryContext { instance_id: string; instance: ProviderInstanceConfig; credential?: SecretBinding; transports: { http: HttpTransport }; clock: () => Date }
export interface ProviderPorts { query: Readonly<Record<string, QueryProvider>>; fetch: Readonly<Record<string, FetchProvider>> }
export interface ProviderRegistration { descriptor: ProviderDescriptor; validate?(instanceId: string, instance: ProviderInstanceConfig): void; create(context: ProviderFactoryContext): ProviderPorts }
interface RegisteredProvider { registration: ProviderRegistration; built_in: boolean }
export class ProviderRegistry {
  private readonly registrations = new Map<ProviderId, RegisteredProvider>();
  constructor(builtIns: readonly ProviderRegistration[] = [], custom: readonly ProviderRegistration[] = []) { for (const item of builtIns) this.register(item, true); for (const item of custom) this.register(item, false); }
  private register(registration: ProviderRegistration, builtIn: boolean): void { validateRegistration(registration); const descriptor = deepFreeze(structuredClone(registration.descriptor)); const canonical: ProviderRegistration = Object.freeze({ descriptor, ...(registration.validate === undefined ? {} : { validate: registration.validate }), create: registration.create }); const id = descriptor.provider_id; if (this.registrations.has(id)) throw new NbSearchError('CONFIGURATION_ERROR', `Provider ${id} is registered more than once.`); this.registrations.set(id, { registration: canonical, built_in: builtIn }); }
  descriptor(providerId: ProviderId): ProviderDescriptor | undefined { return this.registrations.get(providerId)?.registration.descriptor }
  requireDescriptor(providerId: ProviderId): ProviderDescriptor { const descriptor = this.descriptor(providerId); if (descriptor === undefined) throw new NbSearchError('LANE_NOT_REGISTERED', `Provider ${providerId} is not registered.`); return descriptor }
  isBuiltIn(providerId: ProviderId): boolean { return this.registrations.get(providerId)?.built_in === true }
  descriptors(): readonly ProviderDescriptor[] { return [...this.registrations.values()].map((item) => item.registration.descriptor).sort((a, b) => a.provider_id.localeCompare(b.provider_id)); }
  create(instanceId: string, instance: ProviderInstanceConfig, context: Omit<ProviderFactoryContext, 'instance_id' | 'instance'>): ProviderPorts { const item = this.registrations.get(instance.provider_id); if (item === undefined) throw new NbSearchError('LANE_NOT_REGISTERED', `Provider ${instance.provider_id} is not registered.`); const credential = context.credential; if (credential !== undefined && (credential.provider_id !== instance.provider_id || credential.credential_slot_id !== instance.credential_slot_id)) throw new NbSearchError('CONFIGURATION_ERROR', `Credential binding for provider instance ${instanceId} does not match the provider.`); item.registration.validate?.(instanceId, instance); return item.registration.create({ ...context, instance_id: instanceId, instance }); }
  operation(providerId: ProviderId, operationId: string): QueryOperationDescriptor | undefined { return this.descriptor(providerId)?.query_operations.find((item) => item.operation_id === operationId) }
  fetchOperation(providerId: ProviderId, operationId: string): FetchOperationDescriptor | undefined { return this.descriptor(providerId)?.fetch_operations.find((item) => item.operation_id === operationId) }
  operationFingerprint(providerId: ProviderId, operationId: string): string { const descriptor = this.requireDescriptor(providerId); const operation = descriptor.query_operations.find((item) => item.operation_id === operationId) ?? descriptor.fetch_operations.find((item) => item.operation_id === operationId); if (operation === undefined) throw new NbSearchError('LANE_NOT_REGISTERED', `Operation ${providerId}:${operationId} is not registered.`); return stableFingerprint({ registry_schema: REGISTRY_SCHEMA_VERSION, provider_id: providerId, adapter_version: descriptor.adapter_version, operation }); }
}
const DESCRIPTOR_ID = /^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,255}$/;
function validateRegistration(registration: ProviderRegistration): void {
  const descriptor = (registration as unknown as { descriptor?: unknown; create?: unknown }).descriptor;
  if (!isRecord(descriptor) || typeof (registration as unknown as { create?: unknown }).create !== 'function') throw invalidDescriptor();
  const descriptorKeys = ['activation', 'adapter_version', 'fetch_operations', 'option_keys', 'provider_id', 'query_operations'];
  if (!exactKeys(descriptor, descriptorKeys) || !stableId(descriptor['provider_id']) || !stableId(descriptor['adapter_version']) || !Array.isArray(descriptor['query_operations']) || !Array.isArray(descriptor['fetch_operations']) || !Array.isArray(descriptor['option_keys']) || !isRecord(descriptor['activation'])) throw invalidDescriptor();
  const activation = descriptor['activation'];
  if (!exactKeys(activation, ['credential', 'endpoint']) || (activation['credential'] !== 'required' && activation['credential'] !== 'none') || (activation['endpoint'] !== 'required' && activation['endpoint'] !== 'optional' && activation['endpoint'] !== 'none')) throw invalidDescriptor();
  if (!descriptor['option_keys'].every(stableId) || new Set(descriptor['option_keys']).size !== descriptor['option_keys'].length) throw invalidDescriptor();
  const operationIds = new Set<string>();
  for (const candidate of descriptor['query_operations']) {
    if (!isRecord(candidate) || !exactKeys(candidate, ['built_in_async', 'operation_id', 'output']) || !stableId(candidate['operation_id']) || operationIds.has(candidate['operation_id']) || typeof candidate['built_in_async'] !== 'boolean' || !isRecord(candidate['output'])) throw invalidDescriptor();
    operationIds.add(candidate['operation_id']);
    const output = candidate['output'];
    if (!exactKeys(output, ['channel', 'schema_id'])) throw invalidDescriptor();
    if (output['channel'] === 'results') { if (output['schema_id'] !== 'nb-search.results@1') throw invalidDescriptor(); }
    else if (output['channel'] === 'typed') { if (!stableId(output['schema_id'])) throw invalidDescriptor(); }
    else throw invalidDescriptor();
  }
  for (const fetch of descriptor['fetch_operations']) {
    if (!isRecord(fetch) || !exactKeys(fetch, ['egress', 'execution_modes', 'input_kinds', 'media_types', 'operation_id', 'representations', 'schema_id', 'stages']) || !stableId(fetch['operation_id']) || fetch['schema_id'] !== 'nb-search.fetch@1' || operationIds.has(fetch['operation_id']) || !Array.isArray(fetch['input_kinds']) || !fetch['input_kinds'].every((value) => ['url', 'inline_text', 'inline_bytes', 'file'].includes(String(value))) || !Array.isArray(fetch['media_types']) || !fetch['media_types'].every((value) => typeof value === 'string' && value.length > 0) || !Array.isArray(fetch['representations']) || !fetch['representations'].every((value) => value === 'markdown' || value === 'text') || !Array.isArray(fetch['execution_modes']) || !fetch['execution_modes'].every((value) => value === 'sync' || value === 'async') || (fetch['egress'] !== 'none' && fetch['egress'] !== 'url' && fetch['egress'] !== 'content') || !Array.isArray(fetch['stages']) || !fetch['stages'].every((stage) => isRecord(stage) && exactKeys(stage, ['id', 'role']) && stableId(stage['id']) && ['acquire', 'extract', 'convert', 'reader'].includes(String(stage['role'])))) throw invalidDescriptor();
    operationIds.add(fetch['operation_id'] as string);
  }
}
function stableId(value: unknown): value is string { return typeof value === 'string' && DESCRIPTOR_ID.test(value); }
function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function exactKeys(value: Record<string, unknown>, keys: readonly string[]): boolean { const actual = Object.keys(value); return actual.length === keys.length && keys.every((key) => Object.prototype.hasOwnProperty.call(value, key)); }
function deepFreeze<T>(value: T): T { if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); for (const item of Object.values(value as Record<string, unknown>)) deepFreeze(item); } return value; }
function invalidDescriptor(): NbSearchError { return new NbSearchError('CONFIGURATION_ERROR', 'Provider registration descriptor is invalid.'); }
export function builtInProviderRegistrations(): readonly ProviderRegistration[] { return registrationsWithFetchIo(undefined, playwrightBrowserRenderIo); }
export function builtInProviderRegistrationsForInternalTest(testDirectIo?: DirectFetchIo, testBrowserIo: BrowserRenderIo = playwrightBrowserRenderIo): readonly ProviderRegistration[] { return registrationsWithFetchIo(testDirectIo, testBrowserIo); }
function registrationsWithFetchIo(directIo: DirectFetchIo | undefined, browserIo: BrowserRenderIo): readonly ProviderRegistration[] { return [directRegistration(directIo), waybackRegistration(directIo), browserRegistration(browserIo), jinaRegistration, exaRegistration, tavilyRegistration, firecrawlRegistration, braveRegistration, context7Registration, zhipuRegistration, githubRegistration, parallelRegistration, searxngRegistration, openAiCompatibleRegistration, grokRegistration, gmaRegistration]; }
const urlStages = [{ id: 'remote.acquire', role: 'acquire' as const }, { id: 'content.extract', role: 'extract' as const }];
const remoteFetch = (operation_id: string): FetchOperationDescriptor => ({ operation_id, schema_id: 'nb-search.fetch@1', input_kinds: ['url'], media_types: ['text/html', 'text/plain', 'text/markdown'], representations: ['markdown', 'text'], execution_modes: ['sync'], egress: 'url', stages: urlStages });
function directRegistration(io: DirectFetchIo | undefined): ProviderRegistration { return { descriptor: { provider_id: 'direct-http', adapter_version: '1', query_operations: [], fetch_operations: [{ ...remoteFetch('fetch'), media_types: ['text/html', 'application/xhtml+xml', 'text/plain', 'text/markdown', 'text/x-markdown', 'application/json', 'application/ld+json', 'application/xml', 'text/xml', 'application/rss+xml', 'application/atom+xml'], stages: [{ id: 'direct.http', role: 'acquire' }, { id: 'html.text', role: 'extract' }] }, { operation_id: 'local', schema_id: 'nb-search.fetch@1', input_kinds: ['inline_text', 'inline_bytes', 'file'], media_types: ['text/html', 'text/plain', 'text/markdown'], representations: ['markdown', 'text'], execution_modes: ['sync', 'async'], egress: 'none', stages: [{ id: 'local.acquire', role: 'acquire' }, { id: 'html.text', role: 'extract' }] }], activation: { credential: 'none', endpoint: 'none' }, option_keys: [] }, validate: (id, instance) => validateKnownOptions(id, instance, []), create: () => ({ query: {}, fetch: { fetch: new DirectFetchProvider(io), local: new LocalFetchProvider() } }) }; }
function waybackRegistration(directIo: DirectFetchIo | undefined): ProviderRegistration { return { descriptor: { provider_id: 'wayback', adapter_version: '1', query_operations: [], fetch_operations: [{ ...remoteFetch('fetch'), media_types: ['text/html', 'application/xhtml+xml', 'text/plain', 'text/markdown'], stages: [{ id: 'wayback.lookup', role: 'acquire' }, { id: 'wayback.snapshot', role: 'acquire' }, { id: 'html.text', role: 'extract' }] }], activation: { credential: 'none', endpoint: 'none' }, option_keys: [] }, validate: (id, instance) => validateKnownOptions(id, instance, []), create: (context) => ({ query: {}, fetch: { fetch: new WaybackFetchProvider({ transport: context.transports.http, ...(directIo === undefined ? {} : { directIo }) }) } }) }; }
function browserRegistration(io: BrowserRenderIo): ProviderRegistration { return { descriptor: { provider_id: 'browser-render', adapter_version: '1', query_operations: [], fetch_operations: [{ operation_id: 'render', schema_id: 'nb-search.fetch@1', input_kinds: ['url'], media_types: ['text/html', 'application/xhtml+xml', 'text/plain'], representations: ['markdown', 'text'], execution_modes: ['async'], egress: 'url', stages: [{ id: 'browser.chromium', role: 'acquire' }, { id: 'html.text', role: 'extract' }] }], activation: { credential: 'none', endpoint: 'none' }, option_keys: [] }, validate: (id, instance) => validateKnownOptions(id, instance, []), create: () => ({ query: {}, fetch: io.available ? { render: new BrowserRenderProvider(io) } : {} as Readonly<Record<string, FetchProvider>> }) }; }
const jinaRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'jina-reader', adapter_version: '1', query_operations: [], fetch_operations: [{ ...remoteFetch('reader'), stages: [{ id: 'jina.reader', role: 'reader' }] }], activation: { credential: 'none', endpoint: 'optional' }, option_keys: [] },
  validate(id, instance) { validateKnownOptions(id, instance, []); if (instance.base_url !== undefined) validateProviderBaseUrl(instance.base_url); },
  create(context) { return { query: {}, fetch: { reader: new JinaReaderFetchProvider({ ...(context.credential === undefined ? {} : { apiKey: context.credential.value }), transport: context.transports.http, ...(context.instance.base_url === undefined ? {} : { baseUrl: context.instance.base_url }) }) } }; },
};
const exaRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'exa', adapter_version: '1', query_operations: [{ operation_id: 'search', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }, { operation_id: 'synthesis', output: { channel: 'typed', schema_id: 'nb-search.synthesis@1' }, built_in_async: true }], fetch_operations: [remoteFetch('contents')], activation: { credential: 'required', endpoint: 'optional' }, option_keys: ['search_path', 'synthesis_path'] },
  validate: (id, instance) => validateRelay(id, instance, ['search_path', 'synthesis_path']),
  create(context) { const credential = requireCredential(context); const common = commonOptions(context, credential); const searchPath = option(context.instance, 'search_path'); const synthesisPath = option(context.instance, 'synthesis_path'); const results = new ExaProvider({ ...common, ...(searchPath === undefined ? {} : { searchPath }) }); const synthesis = new ExaResearchLightProvider({ ...common, ...(synthesisPath === undefined ? {} : { operationPath: synthesisPath }) }); return { query: { search: resultsProvider(results), synthesis: { name: 'exa', redactions: synthesis.redactions, async execute(request) { const value = await synthesis.researchLight({ capability: 'research-light', query: request.query, retrieval_result_count: request.limit, ...(request.freshness === undefined ? {} : { freshness: request.freshness }), request_time_utc: request.request_time_utc, signal: request.signal }); return typed({ text: value.synthesis ?? '', supporting_urls: value.supporting_urls, resolved_type: value.resolved_type, citation_status: citationStatus() }); } } }, fetch: { contents: new ExaContentsFetchProvider({ apiKey: credential.value, transport: context.transports.http, ...(context.instance.base_url === undefined ? {} : { baseUrl: context.instance.base_url }) }) } }; },
};
const tavilyRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'tavily', adapter_version: '1', query_operations: [{ operation_id: 'search', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }, { operation_id: 'synthesis', output: { channel: 'typed', schema_id: 'nb-search.synthesis@1' }, built_in_async: true }], fetch_operations: [remoteFetch('extract')], activation: { credential: 'required', endpoint: 'optional' }, option_keys: ['search_path', 'synthesis_path'] },
  validate: (id, instance) => validateRelay(id, instance, ['search_path', 'synthesis_path']),
  create(context) { const credential = requireCredential(context); const common = commonOptions(context, credential); const searchPath = option(context.instance, 'search_path'); const synthesisPath = option(context.instance, 'synthesis_path'); const results = new TavilyProvider({ ...common, ...(searchPath === undefined ? {} : { searchPath }) }); const synthesis = new TavilyAnswerProvider({ ...common, ...(synthesisPath === undefined ? {} : { operationPath: synthesisPath }) }); return { query: { search: resultsProvider(results), synthesis: { name: 'tavily', redactions: synthesis.redactions, async execute(request) { const value = await synthesis.answer({ capability: 'answer', query: request.query, limit: request.limit, ...(request.freshness === undefined ? {} : { freshness: request.freshness }), request_time_utc: request.request_time_utc, signal: request.signal }); return typed({ text: value.text ?? '', supporting_urls: value.supporting_results.map((item) => ({ url: item.url, ...(item.title === '' ? {} : { title: item.title }), source: 'provider-result' })), citation_status: citationStatus() }); } } }, fetch: { extract: new TavilyExtractFetchProvider({ apiKey: credential.value, transport: context.transports.http, ...(context.instance.base_url === undefined ? {} : { baseUrl: context.instance.base_url }) }) } }; },
};
const firecrawlRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'firecrawl', adapter_version: '1', query_operations: [{ operation_id: 'search', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }], fetch_operations: [remoteFetch('scrape')], activation: { credential: 'required', endpoint: 'optional' }, option_keys: [] },
  validate(id, instance) { validateKnownOptions(id, instance, []); if (instance.base_url !== undefined) validateProviderBaseUrl(instance.base_url); },
  create(context) { const credential = requireCredential(context); const common = commonOptions(context, credential); return { query: { search: resultsProvider(new FirecrawlSearchProvider(common)) }, fetch: { scrape: new FirecrawlScrapeFetchProvider({ apiKey: credential.value, transport: context.transports.http, ...(context.instance.base_url === undefined ? {} : { baseUrl: context.instance.base_url }) }) } }; },
};
const braveRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'brave', adapter_version: '1', query_operations: [{ operation_id: 'search', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }], fetch_operations: [], activation: { credential: 'required', endpoint: 'optional' }, option_keys: [] },
  validate(id, instance) { validateKnownOptions(id, instance, []); if (instance.base_url !== undefined) validateProviderBaseUrl(instance.base_url); },
  create(context) { const credential = requireCredential(context); return { query: { search: resultsProvider(new BraveSearchProvider(commonOptions(context, credential))) }, fetch: {} }; },
};
const context7Registration: ProviderRegistration = {
  descriptor: { provider_id: 'context7', adapter_version: '1', query_operations: [{ operation_id: 'docs', output: { channel: 'typed', schema_id: 'nb-search.docs-context@1' }, built_in_async: true }], fetch_operations: [], activation: { credential: 'none', endpoint: 'optional' }, option_keys: [] },
  validate: (id, instance) => validateKnownOptions(id, instance, []),
  create(context) { const provider = new Context7DocsProvider({ ...(context.credential === undefined ? {} : { apiKey: context.credential.value }), transport: context.transports.http, ...(context.instance.base_url === undefined ? {} : { baseUrl: context.instance.base_url }), clock: context.clock }); return { query: { docs: provider }, fetch: {} }; },
};
const zhipuRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'zhipu', adapter_version: '1', query_operations: [{ operation_id: 'search', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }], fetch_operations: [], activation: { credential: 'required', endpoint: 'optional' }, option_keys: [] },
  validate: (id, instance) => validateKnownOptions(id, instance, []),
  create(context) { const credential = requireCredential(context); const provider = new ZhipuSearchProvider({ apiKey: credential.value, transport: context.transports.http, ...(context.instance.base_url === undefined ? {} : { baseUrl: context.instance.base_url }), clock: context.clock }); return { query: { search: resultsProvider(provider) }, fetch: {} }; },
};
const githubRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'github', adapter_version: '1', query_operations: [{ operation_id: 'repositories', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }], fetch_operations: [], activation: { credential: 'none', endpoint: 'none' }, option_keys: [] },
  validate: (id, instance) => validateKnownOptions(id, instance, []),
  create(context) { const provider = new GitHubRepositoriesProvider({ ...(context.credential === undefined ? {} : { token: context.credential.value }), transport: context.transports.http, clock: context.clock }); return { query: { repositories: resultsProvider(provider) }, fetch: {} }; },
};
const parallelRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'parallel', adapter_version: '1', query_operations: [{ operation_id: 'search', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }], fetch_operations: [], activation: { credential: 'required', endpoint: 'none' }, option_keys: [] },
  validate: (id, instance) => validateKnownOptions(id, instance, []),
  create(context) { const credential = requireCredential(context); const provider = new ParallelSearchProvider({ apiKey: credential.value, transport: context.transports.http, providerInstanceId: context.instance_id, credentialSlotId: credential.credential_slot_id, clock: context.clock }); return { query: { search: resultsProvider(provider) }, fetch: {} }; },
};
const searxngRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'searxng', adapter_version: '1', query_operations: [{ operation_id: 'search', output: { channel: 'results', schema_id: 'nb-search.results@1' }, built_in_async: true }], fetch_operations: [], activation: { credential: 'none', endpoint: 'required' }, option_keys: [] },
  validate(id, instance) { validateKnownOptions(id, instance, []); if (instance.base_url !== undefined) validateSearxngBaseUrl(instance.base_url); },
  create(context) { if (context.instance.base_url === undefined) throw incomplete(context.instance_id); const provider = new SearxngSearchProvider({ baseUrl: context.instance.base_url, transport: context.transports.http, providerInstanceId: context.instance_id, clock: context.clock }); return { query: { search: resultsProvider(provider) }, fetch: {} }; },
};
const openAiCompatibleRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'openai-compatible', adapter_version: '1', query_operations: [{ operation_id: 'synthesis', output: { channel: 'typed', schema_id: 'nb-search.synthesis@1' }, built_in_async: true }], fetch_operations: [{ ...remoteFetch('fetch'), stages: [{ id: 'oac.reader', role: 'reader' }] }], activation: { credential: 'required', endpoint: 'required' }, option_keys: ['model', 'fallback_models'] },
  validate(id, instance) { validateKnownOptions(id, instance, ['model', 'fallback_models']); if (instance.base_url !== undefined) validateOpenAiCompatibleBaseUrl(instance.base_url); if (instance.options['model'] !== undefined) validateOpenAiCompatibleModel(instance.options['model']); validateOpenAiCompatibleFallbackModels(instance.options['fallback_models']); },
  create(context) { const credential = requireCredential(context); if (context.instance.base_url === undefined || context.instance.options['model'] === undefined) return { query: {} as Readonly<Record<string, QueryProvider>>, fetch: {} as Readonly<Record<string, FetchProvider>> }; const options = { apiKey: credential.value, baseUrl: context.instance.base_url, model: context.instance.options['model'] as string, fallbackModels: context.instance.options['fallback_models'] as readonly string[] | undefined, transport: context.transports.http, providerInstanceId: context.instance_id, credentialSlotId: credential.credential_slot_id, clock: context.clock }; const synthesis = new OpenAiCompatibleSynthesisProvider(options); const fetch = new OpenAiCompatibleFetchProvider(options); return { query: { synthesis: { name: synthesis.name, redactions: synthesis.redactions, async execute(request) { return typed(await synthesis.synthesize(request)); } } }, fetch: { fetch } }; },
};
const grokRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'grok', adapter_version: '2', query_operations: [{ operation_id: 'synthesis', output: { channel: 'typed', schema_id: 'nb-search.synthesis@1' }, built_in_async: true }, { operation_id: 'x-synthesis', output: { channel: 'typed', schema_id: 'nb-search.synthesis@1' }, built_in_async: true }], fetch_operations: [], activation: { credential: 'required', endpoint: 'optional' }, option_keys: ['model', 'synthesis_model', 'x_synthesis_model'] },
  validate(id, instance) { validateKnownOptions(id, instance, ['model', 'synthesis_model', 'x_synthesis_model']); if (instance.base_url !== undefined) resolveGrokResponsesUrl(instance.base_url); validateGrokModel(instance.options['model']); validateOptionalGrokModel(instance.options['synthesis_model']); validateOptionalGrokModel(instance.options['x_synthesis_model']); },
  create(context) { const credential = requireCredential(context); const common = { apiKey: credential.value, transport: context.transports.http, ...(context.instance.base_url === undefined ? {} : { baseUrl: context.instance.base_url }), providerInstanceId: context.instance_id, credentialSlotId: credential.credential_slot_id, clock: context.clock }; const defaultModel = context.instance.options['model'] as string; const synthesis = new GrokResponsesProvider({ ...common, model: option(context.instance, 'synthesis_model') ?? defaultModel, tool: 'web_search' }); const xSynthesis = new GrokResponsesProvider({ ...common, model: option(context.instance, 'x_synthesis_model') ?? defaultModel, tool: 'x_search' }); return { query: { synthesis: grokSynthesisProvider(synthesis), 'x-synthesis': grokSynthesisProvider(xSynthesis) }, fetch: {} }; },
};
const gmaRegistration: ProviderRegistration = {
  descriptor: { provider_id: 'grok-multi-agent', adapter_version: '1', query_operations: [{ operation_id: 'research', output: { channel: 'typed', schema_id: 'nb-search.multi-agent-research@1' }, built_in_async: true }], fetch_operations: [], activation: { credential: 'required', endpoint: 'required' }, option_keys: ['model', 'reasoning_effort'] },
  validate(id, instance) { validateKnownOptions(id, instance, ['model', 'reasoning_effort']); if (instance.base_url !== undefined) validateGrokBaseUrl(instance.base_url); validateGrokModel(instance.options['model']); validateGmaEffort(instance.options['reasoning_effort']); },
  create(context) { const credential = requireCredential(context); if (context.instance.base_url === undefined) throw incomplete(context.instance_id); const provider = new GrokMultiAgentProvider({ apiKey: credential.value, baseUrl: context.instance.base_url, model: context.instance.options['model'] as string, reasoningEffort: context.instance.options['reasoning_effort'] as import('./types.ts').GmaEffort, transport: context.transports.http, providerInstanceId: context.instance_id, credentialSlotId: credential.credential_slot_id, clock: context.clock }); return { query: { research: { name: 'grok-multi-agent', redactions: provider.redactions, async execute(request) { const value = await provider.research({ capability: 'multi-agent-research', query: request.query, brief: request.query, limit: request.limit, request_time_utc: request.request_time_utc, signal: request.signal }); return typed(value); } } }, fetch: {} }; },
};
function resultsProvider(provider: import('./types.ts').SearchProvider): QueryProvider { return { name: provider.name, redactions: provider.redactions, async execute(request) { const returned = await provider.search({ query: request.query, limit: request.limit, ...(request.freshness === undefined ? {} : { freshness: request.freshness }), request_time_utc: request.request_time_utc, signal: request.signal }); const value = Array.isArray(returned) ? { results: returned } : returned; return { channel: 'results', value: value as import('./types.ts').QueryResultsValue }; } }; }
function grokSynthesisProvider(provider: GrokResponsesProvider): QueryProvider { return { name: provider.name, redactions: provider.redactions, async execute(request) { return typed(await provider.synthesize(request)); } }; }
function typed(value: unknown): QueryProviderValue { return { channel: 'typed', data: toJson(value) } }
function toJson(value: unknown): JsonValue { const encoded = JSON.stringify(value); if (encoded === undefined) throw new NbSearchError('PROVIDER_UNAVAILABLE', 'Typed provider returned non-JSON output.'); try { return JSON.parse(encoded) as JsonValue; } catch (error) { throw new NbSearchError('PROVIDER_UNAVAILABLE', 'Typed provider returned non-JSON output.', false, undefined, { cause: error }); } }
function commonOptions(context: ProviderFactoryContext, credential: SecretBinding) { return { apiKey: credential.value, transport: context.transports.http, ...(context.instance.base_url === undefined ? {} : { baseUrl: context.instance.base_url }), providerInstanceId: context.instance_id, credentialSlotId: credential.credential_slot_id, clock: context.clock }; }
function validateRelay(id: string, instance: ProviderInstanceConfig, keys: readonly string[]): void { validateKnownOptions(id, instance, keys); if (instance.base_url !== undefined) validateProviderBaseUrl(instance.base_url); for (const key of keys) { const value = instance.options[key]; if (value !== undefined) { if (typeof value !== 'string') throw invalidOption(id); validateSearchPath(value); } } }
function validateKnownOptions(id: string, instance: ProviderInstanceConfig, keys: readonly string[]): void { if (Object.keys(instance.options).some((key) => !keys.includes(key))) throw invalidOption(id) }
function option(instance: ProviderInstanceConfig, key: string): string | undefined { return typeof instance.options[key] === 'string' ? instance.options[key] : undefined }
function validateOptionalGrokModel(value: unknown): void { if (value !== undefined) validateGrokModel(value) }
function invalidOption(id: string): NbSearchError { return new NbSearchError('CONFIGURATION_ERROR', `Provider instance ${id} has invalid options.`) }
function incomplete(id: string): NbSearchError { return new NbSearchError('LANE_NOT_CONFIGURED', `Provider instance ${id} is incomplete.`) }
function requireCredential(context: ProviderFactoryContext): SecretBinding { if (context.credential === undefined || context.credential.credential_slot_id !== context.instance.credential_slot_id) throw incomplete(context.instance_id); return context.credential }
function citationStatus(): { claim_linked_citations: false; evidence_map_available: false; semantic_verification: false } { return { claim_linked_citations: false, evidence_map_available: false, semantic_verification: false } }
