import { randomBytes } from 'node:crypto';
import { spawn, type ChildProcess, type SpawnOptions } from 'node:child_process';
import type { AppConfiguration } from './config.ts';
import { resultTtlSeconds } from './config-schema.ts';
import { resolveSearchTimeout } from './config-sources.ts';
import type { FetchCancelInput, FetchGetInput, FetchReadInput, FetchRunInput, SearchCancelInput, SearchGetInput, SearchReadInput, SearchRunInput } from './contracts.ts';
import { FetchService, QueryEngine } from './core.ts';
import { createExecutionSnapshot, createFetchExecutionSnapshot, type ExecutionSnapshot, type FetchJobRequest, type QueryJobRequest } from './execution-snapshot.ts';
import { NbSearchError } from './errors.ts';
import { JobStore } from './job-store.ts';
import type { ResolvedFetchSelection, ResolvedSearchSelection } from './planner.ts';
import type { FetchCancelEnvelope, FetchGetEnvelope, FetchReadEnvelope, FetchRunAsyncEnvelope, JobKind, SearchCancelEnvelope, SearchGetEnvelope, SearchReadEnvelope, SearchRunAsyncEnvelope } from './types.ts';
import { SCHEMA_VERSION } from './types.ts';

export interface WorkerLauncher { launch(jobId: string, jobsRoot: string): Promise<void> }
export type SpawnFunction = (command: string, args: readonly string[], options: SpawnOptions) => ChildProcess;
export class DetachedWorkerLauncher implements WorkerLauncher { constructor(private readonly workerPath: string, private readonly env: NodeJS.ProcessEnv, private readonly spawnProcess: SpawnFunction = spawn, private readonly platform: NodeJS.Platform = process.platform) {} async launch(jobId: string, jobsRoot: string): Promise<void> { await new Promise<void>((resolve, reject) => { const child = this.spawnProcess(process.execPath, [this.workerPath, jobId, jobsRoot], { detached: true, windowsHide: this.platform === 'win32', stdio: 'ignore', env: this.env }); child.once('error', reject); child.once('spawn', () => { child.unref(); resolve(); }); }); } }
export class QueryJobService {
  constructor(private readonly store: JobStore, private readonly launcher: WorkerLauncher, private readonly app: AppConfiguration) {}
  async start(input: SearchRunInput, selected: ResolvedSearchSelection): Promise<SearchRunAsyncEnvelope> { const execution = this.app.resolved.config.execution; const queries = typeof input.query === 'string' ? [input.query] : [...input.query]; const request: QueryJobRequest = { queries, lanes: selected.selection.lanes, ...(input.freshness === undefined ? {} : { freshness: input.freshness }), max_results: input.max_results ?? 8, timeout_ms: resolveSearchTimeout(input.timeout_ms, selected.lanes.map((lane) => ({ provider_id: lane.provider_id, operation_id: lane.query_operation!.operation_id })), execution.search_timeout_ms, this.app.resolved.explicit_search_timeout_ms), retry_count: execution.retry_count, max_provider_calls: execution.max_provider_calls, max_concurrency: execution.max_concurrency, result_ttl_seconds: resultTtlSeconds(this.app.retention_hours) }; const snapshot = createExecutionSnapshot(request, selected.selection.lanes, this.app.resolved, this.app.registry); const job = await this.create('search', request, selected.channel, selected.schema_id, input.idempotency_key!, snapshot); return { schema_version: SCHEMA_VERSION, action: 'run', execution: 'async', selection: selected.selection, status: job.record.state === 'failed' ? 'failed' : 'queued', channel: selected.channel, schema_id: selected.schema_id, ...(job.record.state === 'failed' ? { error: job.record.error, hints: job.record.error === undefined ? [] : [{ code: job.record.error.code, message: job.record.error.message }] } : { job: { job_id: job.record.job_id, state: job.record.state, created_at: job.record.created_at }, reused: job.reused, poll_after_ms: 1000, hints: [] }) }; }
  async startFetch(input: FetchRunInput, selected: ResolvedFetchSelection): Promise<FetchRunAsyncEnvelope> { const execution = this.app.resolved.config.execution; const policy = execution.fetch; const pipelines = selected.lanes.map((lane) => lane.id); const request: FetchJobRequest = { source: structuredClone(input.source), selection: selected.source, pipelines, representation: input.representation ?? 'markdown', timeout_ms: input.timeout_ms ?? execution.fetch_timeout_ms, max_content_chars: Math.min(input.max_content_chars ?? policy.max_content_chars, policy.max_content_chars), max_source_bytes: policy.max_source_bytes, max_response_bytes: policy.max_response_bytes, max_redirects: policy.max_redirects, quality: structuredClone(policy.quality), retry_count: execution.retry_count, max_provider_calls: execution.max_provider_calls, result_ttl_seconds: resultTtlSeconds(this.app.retention_hours), file_scopes: structuredClone(this.app.resolved.config.fetch.file_scopes) }; const snapshot = createFetchExecutionSnapshot(request, pipelines, this.app.resolved, this.app.registry); const job = await this.create('fetch', request, 'typed', 'nb-search.fetch@1', input.idempotency_key!, snapshot); return { schema_version: SCHEMA_VERSION, mode: 'fetch', action: 'run', execution: 'async', selection: selected.source === 'pipeline' ? { source: 'pipeline', pipeline: pipelines[0]! } : { source: 'default' }, status: job.record.state === 'failed' ? 'failed' : 'queued', schema_id: 'nb-search.fetch@1', ...(job.record.state === 'failed' ? { error: job.record.error, hints: job.record.error === undefined ? [] : [{ code: job.record.error.code, message: job.record.error.message }] } : { job: { job_id: job.record.job_id, state: job.record.state, created_at: job.record.created_at }, reused: job.reused, poll_after_ms: 1000, hints: [] }) }; }
  async get(input: SearchGetInput): Promise<SearchGetEnvelope> { return this.getEnvelope('search', input.job_id); }
  async getFetch(input: FetchGetInput): Promise<FetchGetEnvelope> { return { mode: 'fetch', ...(await this.getEnvelope('fetch', input.job_id)) }; }
  async read(input: SearchReadInput): Promise<SearchReadEnvelope> { return this.readEnvelope('search', input.job_id, input.cursor, input.page_size); }
  async readFetch(input: FetchReadInput): Promise<FetchReadEnvelope> { return { mode: 'fetch', ...(await this.readEnvelope('fetch', input.job_id, input.cursor, input.page_size)) }; }
  async cancel(input: SearchCancelInput): Promise<SearchCancelEnvelope> { return this.cancelEnvelope('search', input.job_id); }
  async cancelFetch(input: FetchCancelInput): Promise<FetchCancelEnvelope> { return { mode: 'fetch', ...(await this.cancelEnvelope('fetch', input.job_id)) }; }
  private async create(kind: JobKind, request: QueryJobRequest | FetchJobRequest, channel: 'results' | 'typed', schemaId: string, key: string, snapshot: ExecutionSnapshot) { await this.store.prune(); const created = await this.store.createOrReuse(kind, request, channel, schemaId, key, snapshot); if (!created.reused) try { await this.launcher.launch(created.job.job_id, this.store.root); } catch (error) { await this.store.transition(created.job.job_id, 'failed', { error: new NbSearchError('WORKER_START_FAILED', 'The worker could not be started.', true, undefined, { cause: error }).toPublic() }); } return { record: await this.store.read(created.job.job_id), reused: created.reused }; }
  private async getEnvelope(kind: JobKind, jobId: string): Promise<SearchGetEnvelope> { assertKind((await this.store.read(jobId)).kind, kind); const job = await this.store.reconcileStale(jobId); return { schema_version: SCHEMA_VERSION, action: 'get', job_id: job.job_id, state: job.state, cancel_requested: job.cancel_requested_at !== undefined, created_at: job.created_at, updated_at: job.updated_at, ...(job.started_at === undefined ? {} : { started_at: job.started_at }), ...(job.completed_at === undefined ? {} : { completed_at: job.completed_at }), ...(job.artifact === undefined ? {} : { artifact: job.artifact }), ...(job.error === undefined ? {} : { error: job.error }), ...(job.state === 'queued' || job.state === 'running' ? { poll_after_ms: 1000 } : {}) }; }
  private async readEnvelope(kind: JobKind, jobId: string, cursor?: string, pageSize?: number): Promise<SearchReadEnvelope> { assertKind((await this.store.read(jobId)).kind, kind); const job = await this.store.reconcileStale(jobId); if (job.artifact === undefined) return { schema_version: SCHEMA_VERSION, action: 'read', job_id: job.job_id, state: job.state, chunks: [] }; const offset = decodeCursor(cursor, job.artifact.sha256); const page = await this.store.readResult(job.job_id, offset, pageSize ?? 1); return { schema_version: SCHEMA_VERSION, action: 'read', job_id: job.job_id, state: job.state, artifact: page.artifact, chunks: page.chunks, ...(page.next_offset === undefined ? {} : { next_cursor: encodeCursor(page.artifact.sha256, page.next_offset) }) }; }
  private async cancelEnvelope(kind: JobKind, jobId: string): Promise<SearchCancelEnvelope> { const job = await this.store.read(jobId); assertKind(job.kind, kind); const result = await this.store.requestCancel(jobId); return { schema_version: SCHEMA_VERSION, action: 'cancel', job_id: jobId, state: result.job.state, cancel_requested: result.accepted || result.job.cancel_requested_at !== undefined }; }
}
export interface QueryJobRunnerTimings { heartbeat_interval_ms?: number; cancellation_poll_ms?: number }
export class QueryJobRunner {
  constructor(private readonly store: JobStore, private readonly engine: QueryEngine, private readonly selected: ResolvedSearchSelection, private readonly input: SearchRunInput, private readonly ttlSeconds: number, private readonly timings: QueryJobRunnerTimings = {}) {}
  async run(jobId: string): Promise<void> { await runWithLease(this.store, jobId, this.timings, async (signal) => { const output = await this.engine.execute(this.input, this.selected, signal); if (output.status === 'cancelled') return { state: 'cancelled' as const }; if (output.status === 'timed_out') return { state: 'failed' as const, error: new NbSearchError('DEADLINE_EXCEEDED', 'Query deadline was exceeded.', true).toPublic() }; if (output.status === 'failed') return { state: 'failed' as const, error: output.lane_outcomes.find((item) => item.error !== undefined)?.error ?? new NbSearchError('PROVIDER_UNAVAILABLE', 'Query execution failed.').toPublic() }; await this.store.writeResult(jobId, output, this.ttlSeconds); return { state: 'succeeded' as const }; }); }
}
export class FetchJobRunner {
  constructor(private readonly store: JobStore, private readonly service: FetchService, private readonly selected: ResolvedFetchSelection, private readonly input: FetchRunInput, private readonly ttlSeconds: number, private readonly timings: QueryJobRunnerTimings = {}) {}
  async run(jobId: string): Promise<void> { await runWithLease(this.store, jobId, this.timings, async (signal) => { const output = await this.service.fetch(this.input, this.selected, signal); if (output.status === 'cancelled') return { state: 'cancelled' as const }; if (output.status === 'timed_out') return { state: 'failed' as const, error: new NbSearchError('DEADLINE_EXCEEDED', 'Fetch deadline was exceeded.', true).toPublic() }; if (output.status === 'failed') return { state: 'failed' as const, error: output.lane_outcomes.find((item) => item.error !== undefined)?.error ?? new NbSearchError('PROVIDER_UNAVAILABLE', 'Fetch execution failed.').toPublic() }; await this.store.writeResult(jobId, output, this.ttlSeconds); return { state: 'succeeded' as const }; }); }
}
async function runWithLease(store: JobStore, jobId: string, timings: QueryJobRunnerTimings, execute: (signal: AbortSignal) => Promise<{ state: 'succeeded' | 'failed' | 'cancelled'; error?: import('./types.ts').PublicError }>): Promise<void> { const owner = randomBytes(16).toString('hex'); await store.claim(jobId, owner); const controller = new AbortController(); const heartbeat = setInterval(() => { void store.heartbeat(jobId, owner).catch(() => controller.abort(new NbSearchError('WORKER_LOST', 'Worker heartbeat failed.', true))); }, timings.heartbeat_interval_ms ?? 5_000); const cancellation = setInterval(() => { void store.cancelRequested(jobId).then((cancelled) => { if (cancelled) controller.abort(new NbSearchError('CANCELLED', 'Job was cancelled.')); }).catch(() => undefined); }, timings.cancellation_poll_ms ?? 25); try { const result = await execute(controller.signal); if (await store.cancelRequested(jobId) || result.state === 'cancelled') await store.transition(jobId, 'cancelled', { lease: undefined }); else await store.transition(jobId, result.state, { lease: undefined, ...(result.error === undefined ? {} : { error: result.error }) }); } catch (error) { if (await store.cancelRequested(jobId) || error instanceof NbSearchError && error.code === 'CANCELLED') await store.transition(jobId, 'cancelled', { lease: undefined }); else await store.transition(jobId, 'failed', { lease: undefined, error: error instanceof NbSearchError ? error.toPublic() : new NbSearchError('INTERNAL', 'Worker failed.', false, undefined, { cause: error }).toPublic() }); } finally { clearInterval(heartbeat); clearInterval(cancellation); } }
export function inputFromSnapshot(snapshot: ExecutionSnapshot): SearchRunInput { if (snapshot.kind !== 'search') throw new NbSearchError('JOB_STORE_ERROR', 'Expected a search execution snapshot.'); const request = snapshot.request as QueryJobRequest; return { action: 'run', query: request.queries, lanes: request.lanes, execution: 'async', idempotency_key: 'snapshot-replay', ...(request.freshness === undefined ? {} : { freshness: request.freshness }), max_results: request.max_results, timeout_ms: request.timeout_ms }; }
export function fetchInputFromSnapshot(snapshot: ExecutionSnapshot): FetchRunInput { if (snapshot.kind !== 'fetch') throw new NbSearchError('JOB_STORE_ERROR', 'Expected a fetch execution snapshot.'); const request = snapshot.request as FetchJobRequest; return { action: 'run', source: request.source, ...(request.selection === 'pipeline' ? { pipeline: request.pipelines[0]! } : {}), representation: request.representation, execution: 'async', idempotency_key: 'snapshot-replay', timeout_ms: request.timeout_ms, max_content_chars: request.max_content_chars }; }
function encodeCursor(sha256: string, offset: number): string { return Buffer.from(JSON.stringify({ v: 1, sha256, offset })).toString('base64url'); }
function decodeCursor(cursor: string | undefined, sha256: string): number { if (cursor === undefined) return 0; try { const value = JSON.parse(Buffer.from(cursor, 'base64url').toString('utf8')) as { v?: unknown; sha256?: unknown; offset?: unknown }; if (value.v !== 1 || value.sha256 !== sha256 || !Number.isSafeInteger(value.offset) || Number(value.offset) < 0) throw new Error(); return Number(value.offset); } catch { throw new NbSearchError('INVALID_INPUT', 'Cursor does not match the result artifact.'); } }
function assertKind(actual: JobKind, expected: JobKind): void { if (actual !== expected) throw new NbSearchError('JOB_NOT_FOUND', `${expected === 'search' ? 'Search' : 'Fetch'} job was not found.`); }
