import { randomBytes } from 'node:crypto';
import { spawn, type ChildProcess, type SpawnOptions } from 'node:child_process';
import type { AppConfiguration } from './config.ts';
import { resultTtlSeconds } from './config-schema.ts';
import type { SearchCancelInput, SearchGetInput, SearchReadInput, SearchRunInput } from './contracts.ts';
import { QueryEngine } from './core.ts';
import { createExecutionSnapshot, type ExecutionSnapshot, type QueryJobRequest } from './execution-snapshot.ts';
import { NbSearchError } from './errors.ts';
import { JobStore } from './job-store.ts';
import type { ResolvedSearchSelection } from './planner.ts';
import type { SearchCancelEnvelope, SearchGetEnvelope, SearchReadEnvelope, SearchRunAsyncEnvelope } from './types.ts';
import { SCHEMA_VERSION } from './types.ts';

export interface WorkerLauncher { launch(jobId: string, jobsRoot: string): Promise<void> }
export type SpawnFunction = (command: string, args: readonly string[], options: SpawnOptions) => ChildProcess;
export class DetachedWorkerLauncher implements WorkerLauncher { constructor(private readonly workerPath: string, private readonly env: NodeJS.ProcessEnv, private readonly spawnProcess: SpawnFunction = spawn, private readonly platform: NodeJS.Platform = process.platform) {} async launch(jobId: string, jobsRoot: string): Promise<void> { await new Promise<void>((resolve, reject) => { const child = this.spawnProcess(process.execPath, [this.workerPath, jobId, jobsRoot], { detached: true, windowsHide: this.platform === 'win32', stdio: 'ignore', env: this.env }); child.once('error', reject); child.once('spawn', () => { child.unref(); resolve(); }); }); } }
export class QueryJobService {
  constructor(private readonly store: JobStore, private readonly launcher: WorkerLauncher, private readonly app: AppConfiguration) {}
  async start(input: SearchRunInput, selected: ResolvedSearchSelection): Promise<SearchRunAsyncEnvelope> { const execution = this.app.resolved.config.execution; const queries = typeof input.query === 'string' ? [input.query] : [...input.query]; const request: QueryJobRequest = { queries, lanes: selected.selection.lanes, ...(input.freshness === undefined ? {} : { freshness: input.freshness }), max_results: input.max_results ?? 8, timeout_ms: input.timeout_ms ?? execution.search_timeout_ms, retry_count: execution.retry_count, max_provider_calls: execution.max_provider_calls, max_concurrency: execution.max_concurrency, result_ttl_seconds: resultTtlSeconds(this.app.retention_hours) }; const snapshot = createExecutionSnapshot(request, selected.selection.lanes, this.app.resolved, this.app.registry); await this.store.prune(); const created = await this.store.createOrReuse(request, selected.channel, selected.schema_id, input.idempotency_key!, snapshot); if (!created.reused) try { await this.launcher.launch(created.job.job_id, this.store.root); } catch (error) { await this.store.transition(created.job.job_id, 'failed', { error: new NbSearchError('WORKER_START_FAILED', 'The query worker could not be started.', true, undefined, { cause: error }).toPublic() }); } const job = await this.store.read(created.job.job_id); return { schema_version: SCHEMA_VERSION, action: 'run', execution: 'async', selection: selected.selection, status: job.state === 'failed' ? 'failed' : 'queued', channel: selected.channel, schema_id: selected.schema_id, ...(job.state === 'failed' ? { error: job.error, hints: job.error === undefined ? [] : [{ code: job.error.code, message: job.error.message }] } : { job: { job_id: job.job_id, state: job.state, created_at: job.created_at }, reused: created.reused, poll_after_ms: 1000, hints: [] }) }; }
  async get(input: SearchGetInput): Promise<SearchGetEnvelope> { const job = await this.store.reconcileStale(input.job_id); return { schema_version: SCHEMA_VERSION, action: 'get', job_id: job.job_id, state: job.state, cancel_requested: job.cancel_requested_at !== undefined, created_at: job.created_at, updated_at: job.updated_at, ...(job.started_at === undefined ? {} : { started_at: job.started_at }), ...(job.completed_at === undefined ? {} : { completed_at: job.completed_at }), ...(job.artifact === undefined ? {} : { artifact: job.artifact }), ...(job.error === undefined ? {} : { error: job.error }), ...(job.state === 'queued' || job.state === 'running' ? { poll_after_ms: 1000 } : {}) }; }
  async read(input: SearchReadInput): Promise<SearchReadEnvelope> { const job = await this.store.reconcileStale(input.job_id); if (job.artifact === undefined) return { schema_version: SCHEMA_VERSION, action: 'read', job_id: job.job_id, state: job.state, chunks: [] }; const offset = decodeCursor(input.cursor, job.artifact.sha256); const page = await this.store.readResult(job.job_id, offset, input.page_size ?? 1); return { schema_version: SCHEMA_VERSION, action: 'read', job_id: job.job_id, state: job.state, artifact: page.artifact, chunks: page.chunks, ...(page.next_offset === undefined ? {} : { next_cursor: encodeCursor(page.artifact.sha256, page.next_offset) }) }; }
  async cancel(input: SearchCancelInput): Promise<SearchCancelEnvelope> { const result = await this.store.requestCancel(input.job_id); return { schema_version: SCHEMA_VERSION, action: 'cancel', job_id: input.job_id, state: result.job.state, cancel_requested: result.accepted || result.job.cancel_requested_at !== undefined }; }
}
export interface QueryJobRunnerTimings { heartbeat_interval_ms?: number; cancellation_poll_ms?: number }
export class QueryJobRunner {
  constructor(private readonly store: JobStore, private readonly engine: QueryEngine, private readonly selected: ResolvedSearchSelection, private readonly input: SearchRunInput, private readonly ttlSeconds: number, private readonly timings: QueryJobRunnerTimings = {}) {}
  async run(jobId: string): Promise<void> { const owner = randomBytes(16).toString('hex'); await this.store.claim(jobId, owner); const controller = new AbortController(); const heartbeat = setInterval(() => { void this.store.heartbeat(jobId, owner).catch(() => controller.abort(new NbSearchError('WORKER_LOST', 'Worker heartbeat failed.', true))); }, this.timings.heartbeat_interval_ms ?? 5_000); const cancellation = setInterval(() => { void this.store.cancelRequested(jobId).then((cancelled) => { if (cancelled) controller.abort(new NbSearchError('CANCELLED', 'Query job was cancelled.')); }).catch(() => undefined); }, this.timings.cancellation_poll_ms ?? 25);
    try { const output = await this.engine.execute(this.input, this.selected, controller.signal); if (await this.store.cancelRequested(jobId) || output.status === 'cancelled') { await this.store.transition(jobId, 'cancelled', { lease: undefined }); return; } if (output.status === 'timed_out') { await this.store.transition(jobId, 'failed', { lease: undefined, error: new NbSearchError('DEADLINE_EXCEEDED', 'Query deadline was exceeded.', true).toPublic() }); return; } if (output.status === 'failed') { const error = output.lane_outcomes.find((item) => item.error !== undefined)?.error ?? new NbSearchError('PROVIDER_UNAVAILABLE', 'Query execution failed.').toPublic(); await this.store.transition(jobId, 'failed', { lease: undefined, error }); return; } await this.store.writeResult(jobId, output, this.ttlSeconds); await this.store.transition(jobId, 'succeeded', { lease: undefined }); }
    catch (error) { if (await this.store.cancelRequested(jobId) || error instanceof NbSearchError && error.code === 'CANCELLED') await this.store.transition(jobId, 'cancelled', { lease: undefined }); else await this.store.transition(jobId, 'failed', { lease: undefined, error: error instanceof NbSearchError ? error.toPublic() : new NbSearchError('INTERNAL', 'Query worker failed.', false, undefined, { cause: error }).toPublic() }); }
    finally { clearInterval(heartbeat); clearInterval(cancellation); }
  }
}
export function inputFromSnapshot(snapshot: ExecutionSnapshot): SearchRunInput { return { action: 'run', query: snapshot.request.queries, lanes: snapshot.request.lanes, execution: 'async', idempotency_key: 'snapshot-replay', ...(snapshot.request.freshness === undefined ? {} : { freshness: snapshot.request.freshness }), max_results: snapshot.request.max_results, timeout_ms: snapshot.request.timeout_ms }; }
function encodeCursor(sha256: string, offset: number): string { return Buffer.from(JSON.stringify({ v: 1, sha256, offset })).toString('base64url'); }
function decodeCursor(cursor: string | undefined, sha256: string): number { if (cursor === undefined) return 0; try { const value = JSON.parse(Buffer.from(cursor, 'base64url').toString('utf8')) as { v?: unknown; sha256?: unknown; offset?: unknown }; if (value.v !== 1 || value.sha256 !== sha256 || !Number.isSafeInteger(value.offset) || Number(value.offset) < 0) throw new Error(); return Number(value.offset); } catch { throw new NbSearchError('INVALID_INPUT', 'Cursor does not match the result artifact.'); } }
