import type { AppConfiguration } from './config.ts';
import { resultTtlSeconds, type ProviderInstanceConfig } from './config-schema.ts';
import { capabilitiesInputSchema, fetchInputSchema, searchInputSchema, type CapabilitiesInput, type FetchInput, type FetchParsedInput, type FetchRunInput, type OperationContext, type SearchInput } from './contracts.ts';
import { FetchService, outputExceedsInlineLimit, outputTooLargeError, QueryEngine } from './core.ts';
import { NbSearchError, publicError } from './errors.ts';
import { resolveSearchSelection } from './planner.ts';
import type { QueryJobService } from './query-jobs.ts';
import type { CapabilityEnvelope, CapabilityIssueCode, FetchEnvelope, FetchRunAsyncEnvelope, FetchRunSyncEnvelope, QueryExecution, QueryOperationOutput, SearchEnvelope, SearchRunAsyncEnvelope, SearchRunSyncEnvelope } from './types.ts';
import { FETCH_REPRESENTATIONS, SCHEMA_VERSION } from './types.ts';

export interface NbSearchRuntime { search(input: SearchInput, context?: OperationContext): Promise<SearchEnvelope>; fetch(input: FetchInput, context?: OperationContext): Promise<FetchEnvelope>; capabilities(input?: CapabilitiesInput, context?: OperationContext): Promise<CapabilityEnvelope> }
export class NbSearchRuntimeImpl implements NbSearchRuntime {
  private readonly engine: QueryEngine; private readonly fetcher: FetchService;
  constructor(private readonly app: AppConfiguration, private readonly jobs: QueryJobService, now?: () => Date, private readonly disableDetachedAsync = false) { this.engine = new QueryEngine(app, now); this.fetcher = new FetchService(app); }
  async search(input: SearchInput, context: OperationContext = {}): Promise<SearchEnvelope> { const parsed = searchInputSchema.parse(input); assertActive(context.signal); if (parsed.action === 'get') return await this.jobs.get(parsed); if (parsed.action === 'read') return await this.jobs.read(parsed); if (parsed.action === 'cancel') return await this.jobs.cancel(parsed); const execution = parsed.execution ?? 'sync'; if (execution === 'async' && this.disableDetachedAsync) return failedAsync(injectedTransportAsyncError()); let selected; try { selected = resolveSearchSelection(parsed, this.app, execution); } catch (error) { return execution === 'async' ? failedAsync(error) : failedSync(error); } if (execution === 'async') return await this.jobs.start(parsed, selected); try { const output = await this.engine.execute(parsed, selected, context.signal); const maximum = this.app.resolved.config.execution.max_inline_bytes; if (outputExceedsInlineLimit(output, maximum)) return failedSync(outputTooLargeError(maximum), selected.selection); return { schema_version: SCHEMA_VERSION, action: 'run', execution: 'sync', selection: selected.selection, status: output.status, output, hints: output.hints }; } catch (error) { return failedSync(error, selected.selection); } }
  async fetch(input: { url: string; pipeline?: string; representation?: 'markdown' | 'text'; timeout_ms?: number; max_content_chars?: number }, context?: OperationContext): Promise<FetchRunSyncEnvelope>;
  async fetch(input: FetchRunInput & { execution?: 'sync' }, context?: OperationContext): Promise<FetchRunSyncEnvelope>;
  async fetch(input: FetchInput, context?: OperationContext): Promise<FetchEnvelope>;
  async fetch(input: FetchInput, context: OperationContext = {}): Promise<FetchEnvelope> { const parsed = fetchInputSchema.parse(input) as FetchParsedInput; assertActive(context.signal); if (parsed.action === 'get') return await this.jobs.getFetch(parsed); if (parsed.action === 'read') return await this.jobs.readFetch(parsed); if (parsed.action === 'cancel') return await this.jobs.cancelFetch(parsed); const execution = parsed.execution ?? 'sync'; if (execution === 'async' && this.disableDetachedAsync) return failedFetchAsync(injectedTransportAsyncError()); let selected; try { selected = await this.fetcher.preflight(parsed, execution); } catch (error) { return execution === 'async' ? failedFetchAsync(error) : failedFetchSync(parsed, error); } if (execution === 'async') return await this.jobs.startFetch(parsed, selected); try { const output = await this.fetcher.fetch(parsed, selected, context.signal); const maximum = this.app.resolved.config.execution.max_inline_bytes; if (outputExceedsInlineLimit(output, maximum)) return failedFetchSync(parsed, outputTooLargeError(maximum), selected.source === 'pipeline' ? selected.requested : undefined); return output; } catch (error) { return failedFetchSync(parsed, error, selected.source === 'pipeline' ? selected.requested : undefined); } }
  async capabilities(input: CapabilitiesInput = {}, context: OperationContext = {}): Promise<CapabilityEnvelope> {
    capabilitiesInputSchema.parse(input); assertActive(context.signal); const config = this.app.resolved.config;
    const providerDescriptors = this.app.registry.descriptors().map((descriptor) => ({ provider_id: descriptor.provider_id, adapter_version: descriptor.adapter_version, query_operations: descriptor.query_operations.map((operation) => ({ ...operation, output: projectOutput(operation.output) })), fetch_operations: descriptor.fetch_operations.map((operation) => ({ ...operation, input_kinds: [...operation.input_kinds], media_types: [...operation.media_types], representations: [...operation.representations], execution_modes: [...operation.execution_modes], stages: operation.stages.map((stage) => ({ ...stage })) })), activation: { ...descriptor.activation }, option_keys: [...descriptor.option_keys] }));
    const providerInstances: CapabilityEnvelope['providers']['instances'] = Object.entries(config.provider_instances).sort(([a], [b]) => a.localeCompare(b)).map(([id, instance]) => projectProviderInstance(this.app, id, instance));
    const searchLanes = Object.values(this.app.lanes).filter((lane) => lane.query_operation !== undefined).sort((a, b) => a.id.localeCompare(b.id)).map((lane) => ({ id: lane.id, output: projectOutput(lane.query_operation!.output), execution_modes: lane.execution_modes, availability: lane.availability, issues: lane.issues.map((code) => ({ code })), latency: lane.config.latency, cost: lane.config.cost })); const presets = Object.entries(config.presets).sort(([a], [b]) => a.localeCompare(b)).map(([name, preset]) => { const bindings = preset.lanes.map((id) => this.app.lanes[id]!); const ready = bindings.every((lane) => lane.availability === 'ready'); const asyncReady = ready && bindings.every((lane) => lane.execution_modes.includes('async')); return { name, lanes: [...preset.lanes], execution_modes: (ready ? asyncReady ? ['sync', 'async'] : ['sync'] : []) as QueryExecution[], availability: ready ? 'ready' as const : 'unavailable' as const, issues: bindings.flatMap((lane) => lane.issues.map((code) => ({ code }))) }; });
    const pipelines = Object.values(this.app.lanes).filter((lane) => lane.fetch_operation !== undefined).sort((a, b) => a.id.localeCompare(b.id)).map((lane) => ({ id: lane.id, input_kinds: [...lane.fetch_operation!.input_kinds], media_types: [...lane.fetch_operation!.media_types], representations: [...lane.fetch_operation!.representations], execution_modes: [...lane.execution_modes], egress: lane.fetch_operation!.egress, stages: lane.fetch_operation!.stages.map((stage) => ({ ...stage })), availability: lane.availability, issues: lane.issues.map((code) => ({ code })), latency: lane.config.latency, cost: lane.config.cost }));
    const chains = (config.defaults.fetch_chain ?? []).flatMap((chain) => (chain.representation === undefined ? FETCH_REPRESENTATIONS : [chain.representation]).map((representation) => ({ input_kind: chain.input_kind, representation, pipelines: [...chain.pipelines] })));
    const scopes = config.fetch.file_scopes; const sourceLimit = config.execution.fetch.max_source_bytes; return { schema_version: SCHEMA_VERSION, revision: this.app.resolved.config_revision, providers: { descriptors: providerDescriptors, instances: providerInstances }, search: { ...(config.defaults.search_lane === undefined ? {} : { default_lane: config.defaults.search_lane }), lanes: searchLanes, presets, limits: { max_queries: 64, max_results: 100, max_timeout_ms: 3_600_000, max_inline_bytes: config.execution.max_inline_bytes } }, fetch: { default_representation: 'markdown', inputs: [{ kind: 'url', enabled: true, max_bytes: sourceLimit }, { kind: 'inline_text', enabled: true, max_bytes: sourceLimit, media_types: ['text/html', 'text/plain', 'text/markdown'] }, { kind: 'inline_bytes', enabled: true, max_bytes: sourceLimit, media_types: ['text/html', 'text/plain', 'text/markdown'] }, { kind: 'file', enabled: scopes.length > 0, max_bytes: sourceLimit, media_types: [...new Set(scopes.flatMap((scope) => scope.media_types ?? ['text/html', 'text/plain', 'text/markdown']))].sort(), scope_ids: scopes.map((scope) => scope.id).sort() }], chains, pipelines, limits: { max_source_bytes: sourceLimit, max_response_bytes: config.execution.fetch.max_response_bytes, max_content_chars: config.execution.fetch.max_content_chars, max_redirects: config.execution.fetch.max_redirects, max_timeout_ms: config.execution.fetch_timeout_ms, max_inline_bytes: config.execution.max_inline_bytes } }, jobs: { result_ttl_seconds: resultTtlSeconds(this.app.retention_hours), cancel_supported: true } };
  }
}
function projectProviderInstance(app: AppConfiguration, id: string, instance: ProviderInstanceConfig): CapabilityEnvelope['providers']['instances'][number] {
  const descriptor = app.registry.descriptor(instance.provider_id); const binding = instance.credential_slot_id === undefined ? undefined : app.resolved.secret_bindings.get(instance.credential_slot_id); const credentialConfigured = binding !== undefined && binding.provider_id === instance.provider_id && binding.credential_slot_id === instance.credential_slot_id; const endpointConfigured = instance.base_url !== undefined; const issues = new Set<CapabilityIssueCode>();
  if (descriptor === undefined) issues.add('PROVIDER_NOT_REGISTERED'); if (!instance.enabled) issues.add('PROVIDER_DISABLED'); if (descriptor?.activation.credential === 'required' && !credentialConfigured) issues.add('CREDENTIAL_NOT_CONFIGURED'); if (descriptor?.activation.endpoint === 'required' && !endpointConfigured) issues.add('ENDPOINT_NOT_CONFIGURED');
  const activationUnavailable = descriptor === undefined || !instance.enabled || descriptor.activation.credential === 'required' && !credentialConfigured || descriptor.activation.endpoint === 'required' && !endpointConfigured; const ports = app.ports_by_instance.get(id); const declaredOperations = descriptor === undefined ? 0 : descriptor.query_operations.length + descriptor.fetch_operations.length; const readyOperations = descriptor === undefined || ports === undefined ? 0 : descriptor.query_operations.filter((operation) => ports.query[operation.operation_id] !== undefined).length + descriptor.fetch_operations.filter((operation) => ports.fetch[operation.operation_id] !== undefined).length; const runtimeUnavailable = !activationUnavailable && readyOperations === 0;
  if (runtimeUnavailable) issues.add('PROVIDER_PORTS_UNAVAILABLE'); else if (!activationUnavailable && readyOperations < declaredOperations) issues.add('PROVIDER_PORTS_PARTIAL'); for (const lane of Object.values(app.lanes)) if (lane.config.provider_instance_id === id) for (const issue of lane.issues) issues.add(issue);
  return { id, provider_id: instance.provider_id, enabled: instance.enabled, availability: activationUnavailable || runtimeUnavailable ? 'unavailable' : 'ready', issues: [...issues].map((code) => ({ code })), credential: { requirement: descriptor?.activation.credential ?? 'unknown', configured: credentialConfigured, ...(instance.credential_slot_id === undefined ? {} : { slot_id: instance.credential_slot_id }) }, endpoint: { requirement: descriptor?.activation.endpoint ?? 'unknown', configured: endpointConfigured } };
}
function projectOutput(output: QueryOperationOutput): QueryOperationOutput { return output.channel === 'results' ? { channel: 'results', schema_id: 'nb-search.results@1' } : { channel: 'typed', schema_id: output.schema_id }; }
function failedSync(error: unknown, selection?: import('./types.ts').SearchSelection): SearchRunSyncEnvelope { const safe = publicError(error); return { schema_version: SCHEMA_VERSION, action: 'run', execution: 'sync', ...(selection === undefined ? {} : { selection }), status: 'failed', error: safe, hints: [{ code: safe.code, message: safe.message, data: { retryable: safe.retryable } }] }; }
function failedAsync(error: unknown): SearchRunAsyncEnvelope { const safe = publicError(error); return { schema_version: SCHEMA_VERSION, action: 'run', execution: 'async', status: 'failed', error: safe, hints: [{ code: safe.code, message: safe.message, data: { retryable: safe.retryable } }] }; }
function failedFetchSync(input: FetchRunInput, error: unknown, pipeline?: string): FetchRunSyncEnvelope { const safe = publicError(error); return { schema_version: SCHEMA_VERSION, mode: 'fetch', action: 'run', execution: 'sync', selection: pipeline === undefined ? input.pipeline === undefined ? { source: 'default' } : { source: 'pipeline', pipeline: input.pipeline } : { source: 'pipeline', pipeline }, status: 'failed', error: safe, lane_outcomes: [], documents: [], hints: [{ code: safe.code, message: safe.message, data: { retryable: safe.retryable } }] }; }
function failedFetchAsync(error: unknown): FetchRunAsyncEnvelope { const safe = publicError(error); return { schema_version: SCHEMA_VERSION, mode: 'fetch', action: 'run', execution: 'async', status: 'failed', error: safe, hints: [{ code: safe.code, message: safe.message, data: { retryable: safe.retryable } }] }; }
function injectedTransportAsyncError(): NbSearchError { return new NbSearchError('LANE_EXECUTION_UNSUPPORTED', 'Detached async is unavailable with an injected HTTP transport. Use sync execution on this runtime.'); }
function assertActive(signal: AbortSignal | undefined): void { if (signal?.aborted === true) throw new NbSearchError('CANCELLED', 'The operation was cancelled.'); }
