import type { AppConfiguration } from './config.ts';
import { resultTtlSeconds } from './config-schema.ts';
import { capabilitiesInputSchema, fetchInputSchema, searchInputSchema, type CapabilitiesInput, type FetchInput, type OperationContext, type SearchInput } from './contracts.ts';
import { outputExceedsInlineLimit, outputTooLargeError, QueryEngine, FetchService } from './core.ts';
import { NbSearchError, publicError } from './errors.ts';
import { resolveSearchSelection } from './planner.ts';
import type { QueryJobService } from './query-jobs.ts';
import type { CapabilityEnvelope, FetchEnvelope, QueryExecution, QueryOperationOutput, SearchEnvelope, SearchRunAsyncEnvelope, SearchRunSyncEnvelope } from './types.ts';
import { SCHEMA_VERSION } from './types.ts';

export interface NbSearchRuntime { search(input: SearchInput, context?: OperationContext): Promise<SearchEnvelope>; fetch(input: FetchInput, context?: OperationContext): Promise<FetchEnvelope>; capabilities(input?: CapabilitiesInput, context?: OperationContext): Promise<CapabilityEnvelope> }
export class NbSearchRuntimeImpl implements NbSearchRuntime {
  private readonly engine: QueryEngine; private readonly fetcher: FetchService;
  constructor(private readonly app: AppConfiguration, private readonly jobs: QueryJobService, now?: () => Date) { this.engine = new QueryEngine(app, now); this.fetcher = new FetchService(app); }
  async search(input: SearchInput, context: OperationContext = {}): Promise<SearchEnvelope> { const parsed = searchInputSchema.parse(input); assertActive(context.signal); if (parsed.action === 'get') return await this.jobs.get(parsed); if (parsed.action === 'read') return await this.jobs.read(parsed); if (parsed.action === 'cancel') return await this.jobs.cancel(parsed); const execution = parsed.execution ?? 'sync'; let selected; try { selected = resolveSearchSelection(parsed, this.app, execution); } catch (error) { return execution === 'async' ? failedAsync(error) : failedSync(error); } if (execution === 'async') return await this.jobs.start(parsed, selected); try { const output = await this.engine.execute(parsed, selected, context.signal); const maximum = this.app.resolved.config.execution.max_inline_bytes; if (outputExceedsInlineLimit(output, maximum)) return failedSync(outputTooLargeError(maximum), selected.selection); return { schema_version: SCHEMA_VERSION, action: 'run', execution: 'sync', selection: selected.selection, status: output.status, output, hints: output.hints }; } catch (error) { return failedSync(error, selected.selection); } }
  async fetch(input: FetchInput, context: OperationContext = {}): Promise<FetchEnvelope> { const parsed = fetchInputSchema.parse(input); assertActive(context.signal); return await this.fetcher.fetch(parsed, context.signal); }
  async capabilities(input: CapabilitiesInput = {}, context: OperationContext = {}): Promise<CapabilityEnvelope> { capabilitiesInputSchema.parse(input); assertActive(context.signal); const config = this.app.resolved.config; const searchLanes = Object.values(this.app.lanes).filter((lane) => lane.query_operation !== undefined).sort((a, b) => a.id.localeCompare(b.id)).map((lane) => ({ id: lane.id, output: projectOutput(lane.query_operation!.output), execution_modes: lane.execution_modes, availability: lane.availability, issues: lane.issues.map((code) => ({ code })), latency: lane.config.latency, cost: lane.config.cost })); const presets = Object.entries(config.presets).sort(([a], [b]) => a.localeCompare(b)).map(([name, preset]) => { const bindings = preset.lanes.map((id) => this.app.lanes[id]!); const ready = bindings.every((lane) => lane.availability === 'ready'); const asyncReady = ready && bindings.every((lane) => lane.execution_modes.includes('async')); return { name, lanes: [...preset.lanes], execution_modes: (ready ? asyncReady ? ['sync', 'async'] : ['sync'] : []) as QueryExecution[], availability: ready ? 'ready' as const : 'unavailable' as const, issues: bindings.flatMap((lane) => lane.issues.map((code) => ({ code }))) }; }); const fetchLanes = Object.values(this.app.lanes).filter((lane) => lane.fetch_operation !== undefined).sort((a, b) => a.id.localeCompare(b.id)).map((lane) => ({ id: lane.id, availability: lane.availability, issues: lane.issues.map((code) => ({ code })) })); return { schema_version: SCHEMA_VERSION, revision: this.app.resolved.config_revision, search: { ...(config.defaults.search_lane === undefined ? {} : { default_lane: config.defaults.search_lane }), lanes: searchLanes, presets, limits: { max_queries: 64, max_results: 100, max_timeout_ms: 3_600_000, max_inline_bytes: config.execution.max_inline_bytes } }, fetch: { ...(config.defaults.fetch_lane === undefined ? {} : { default_lane: config.defaults.fetch_lane }), lanes: fetchLanes, limits: { max_response_bytes: config.execution.fetch.max_response_bytes, max_content_chars: config.execution.fetch.max_content_chars, max_redirects: config.execution.fetch.max_redirects, max_timeout_ms: 120_000 } }, jobs: { result_ttl_seconds: resultTtlSeconds(config.retention_hours), cancel_supported: true } }; }
}
function projectOutput(output: QueryOperationOutput): QueryOperationOutput { return output.channel === 'results' ? { channel: 'results', schema_id: 'nb-search.results@1' } : { channel: 'typed', schema_id: output.schema_id }; }
function failedSync(error: unknown, selection?: import('./types.ts').SearchSelection): SearchRunSyncEnvelope { const safe = publicError(error); return { schema_version: SCHEMA_VERSION, action: 'run', execution: 'sync', ...(selection === undefined ? {} : { selection }), status: 'failed', error: safe, hints: [{ code: safe.code, message: safe.message, data: { retryable: safe.retryable } }] }; }
function failedAsync(error: unknown): SearchRunAsyncEnvelope { const safe = publicError(error); return { schema_version: SCHEMA_VERSION, action: 'run', execution: 'async', status: 'failed', error: safe, hints: [{ code: safe.code, message: safe.message, data: { retryable: safe.retryable } }] }; }
function assertActive(signal: AbortSignal | undefined): void { if (signal?.aborted === true) throw new NbSearchError('CANCELLED', 'The operation was cancelled.'); }
